# 03-1. 출시 후 LLM 분류 리뷰 전처리 및 결과 통합

이 코드는 `03_run_llm_postlaunch_analysis_final.ipynb`에서 생성한 LLM 분류 결과를 읽어, 후속 단계인 **LLM 기반 패치·운영 전략 제안**에 사용할 근거 데이터를 만든다.

흐름은 출시 전 분석의 `03-1`과 맞춘다.

```text
03. 리뷰 LLM 분류
→ 03-1. 분류된 리뷰 전처리 및 게임별 결과 통합
→ 03-2. LLM 기반 패치·운영 전략 제안
```

주의할 점은 다음과 같다.

- 이 코드에서는 LLM을 호출하지 않는다.
- LLM이 분류한 감정, 이슈 태그, urgency 후보를 그대로 최종 우선 검토 수준로 사용하지 않는다.
- 패치·운영 우선 검토 수준은 **이슈 반복 수, 부정·혼합 리뷰 수, Steam 비추천 리뷰 수, 최근 리뷰 반복 여부, 짧은 플레이타임 부정 반응**을 기준으로 규칙 기반 계산한다.
- `High urgency`는 03번 리뷰 분류 단계에서 LLM이 판단한 시급도 후보이므로, **우선 검토 수준 계산에는 직접 사용하지 않고 보조 설명 지표로만 유지한다.**
- 03-2에서는 이 코드에서 계산한 `action_group_hint`, `rule_priority_hint`, `priority_rule_detail`, `priority_reason`을 고정 근거로 사용한다.

# 1. 기본 설정

In [1]:
# ============================================================
# 기본 라이브러리
# ============================================================

from pathlib import Path
import re
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

In [2]:
# ============================================================
# 프로젝트 경로 설정
# ============================================================
ROOT = Path.cwd()

if not (ROOT / "data" / "preprocessed").exists():
    for parent in ROOT.parents:
        if (parent / "data" / "preprocessed").exists():
            ROOT = parent
            break

# ============================================================
# 출시 후 분석 대상 게임 설정
# ============================================================
# 여러 게임을 한 번에 실행하려면 RUN_MULTI_GAME_MODE=True로 두고,
# TARGET_GAME_KEYS에 실행할 게임 key를 넣으면 된다.
# 게임 1개만 실행하려면 RUN_MULTI_GAME_MODE=False로 바꾸고 TARGET_GAME_KEY만 변경한다.

RUN_MULTI_GAME_MODE = True
RUN_CHECK_CELLS = True

POSTLAUNCH_TARGET_GAMES = {
    "heroes_of_hammerwatch_2": {
        "appid": 619820,
        "game_name": "Heroes of Hammerwatch II",
        "game_slug": "heroes_of_hammerwatch_2",
    },
    "necrosmith_2": {
        "appid": 2277320,
        "game_name": "Necrosmith 2",
        "game_slug": "necrosmith_2",
    },
    "children_of_the_sun": {
        "appid": 1309950,
        "game_name": "Children of the Sun",
        "game_slug": "children_of_the_sun",
    },
    "laundry_store_simulator": {
        "appid": 3150440,
        "game_name": "Laundry Store Simulator",
        "game_slug": "laundry_store_simulator",
    },
    "endoparasitic_2": {
        "appid": 2990640,
        "game_name": "Endoparasitic 2",
        "game_slug": "endoparasitic_2",
    },
}

# 03-1번에서 한 번에 실행할 게임 목록
TARGET_GAME_KEYS = [
    "heroes_of_hammerwatch_2",
    "necrosmith_2",
    "children_of_the_sun",
    "laundry_store_simulator",
    "endoparasitic_2",
]

# 단일 실행 모드에서 사용할 게임
TARGET_GAME_KEY = TARGET_GAME_KEYS[0]

# ============================================================
# 출시 후 게임별 데이터 폴더
# ============================================================
POSTLAUNCH_OUTPUT_DIR = ROOT / "data" / "outputs" / "postlaunch"
RUNS_DIR = POSTLAUNCH_OUTPUT_DIR / "runs"


def set_target_game_context(game_key):
    """게임 key를 기준으로 03-1 전처리에 필요한 전역 경로와 설정값을 갱신한다."""
    global TARGET_GAME_KEY, TARGET_GAME, TARGET_APPID, TARGET_GAME_NAME, GAME_SLUG
    global RUN_DIR, RESULT_CSV_PATH, ISSUE_TAG_FLAT_PATH, LLM_INPUT_PATH
    global POSTLAUNCH_PREPROCESS_DIR
    global POSTLAUNCH_REVIEW_BASE_PATH, POSTLAUNCH_ISSUE_SUMMARY_PATH
    global POSTLAUNCH_PATCH_OPS_EVIDENCE_BASE_PATH, TABLEAU_POSTLAUNCH_SOURCE_PATH

    if game_key not in POSTLAUNCH_TARGET_GAMES:
        raise KeyError(f"POSTLAUNCH_TARGET_GAMES에 없는 game_key입니다: {game_key}")

    TARGET_GAME_KEY = game_key
    TARGET_GAME = POSTLAUNCH_TARGET_GAMES[TARGET_GAME_KEY]
    TARGET_APPID = TARGET_GAME["appid"]
    TARGET_GAME_NAME = TARGET_GAME["game_name"]
    GAME_SLUG = TARGET_GAME["game_slug"]

    RUN_DIR = RUNS_DIR / GAME_SLUG
    RUN_DIR.mkdir(parents=True, exist_ok=True)

    RESULT_CSV_PATH = RUN_DIR / "llm_review_analysis_result.csv"
    ISSUE_TAG_FLAT_PATH = RUN_DIR / "llm_issue_tags_flat.csv"
    LLM_INPUT_PATH = RUN_DIR / "llm_input_reviews.csv"

    POSTLAUNCH_PREPROCESS_DIR = RUN_DIR / "postlaunch_preprocess_data"
    POSTLAUNCH_PREPROCESS_DIR.mkdir(parents=True, exist_ok=True)

    POSTLAUNCH_REVIEW_BASE_PATH = POSTLAUNCH_PREPROCESS_DIR / "postlaunch_review_base.csv"
    POSTLAUNCH_ISSUE_SUMMARY_PATH = POSTLAUNCH_PREPROCESS_DIR / "postlaunch_issue_summary.csv"
    POSTLAUNCH_PATCH_OPS_EVIDENCE_BASE_PATH = POSTLAUNCH_PREPROCESS_DIR / "postlaunch_patch_ops_evidence_base.csv"
    TABLEAU_POSTLAUNCH_SOURCE_PATH = POSTLAUNCH_PREPROCESS_DIR / "tableau_postlaunch_patch_ops_source.csv"

    return {
        "game_key": TARGET_GAME_KEY,
        "appid": TARGET_APPID,
        "game_name": TARGET_GAME_NAME,
        "run_dir": RUN_DIR,
        "result_csv_path": RESULT_CSV_PATH,
        "issue_tag_flat_path": ISSUE_TAG_FLAT_PATH,
        "preprocess_dir": POSTLAUNCH_PREPROCESS_DIR,
    }


set_target_game_context(TARGET_GAME_KEY)

print("ROOT:", ROOT)
print("RUN_MULTI_GAME_MODE:", RUN_MULTI_GAME_MODE)
print("실행 대상 게임 key 목록:", TARGET_GAME_KEYS)
print("현재 미리보기 대상:", TARGET_GAME_NAME)
print("TARGET_APPID:", TARGET_APPID)
print("GAME_SLUG:", GAME_SLUG)
print("RUN_DIR:", RUN_DIR)
print("03번 LLM 결과 CSV:", RESULT_CSV_PATH)
print("03번 이슈 태그 CSV:", ISSUE_TAG_FLAT_PATH)
print("03번 LLM 입력 CSV:", LLM_INPUT_PATH)
print("03-1 전처리 저장 폴더:", POSTLAUNCH_PREPROCESS_DIR)
print("RESULT_CSV_PATH exists:", RESULT_CSV_PATH.exists())
print("ISSUE_TAG_FLAT_PATH exists:", ISSUE_TAG_FLAT_PATH.exists())
print("LLM_INPUT_PATH exists:", LLM_INPUT_PATH.exists())

ROOT: c:\Users\joon5\Documents\github\steam-indie-game-analysis
RUN_MULTI_GAME_MODE: True
실행 대상 게임 key 목록: ['heroes_of_hammerwatch_2', 'necrosmith_2', 'children_of_the_sun', 'laundry_store_simulator', 'endoparasitic_2']
현재 미리보기 대상: Heroes of Hammerwatch II
TARGET_APPID: 619820
GAME_SLUG: heroes_of_hammerwatch_2
RUN_DIR: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2
03번 LLM 결과 CSV: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\llm_review_analysis_result.csv
03번 이슈 태그 CSV: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\llm_issue_tags_flat.csv
03번 LLM 입력 CSV: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\llm_input_reviews.csv
03-1 전처리 저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postlaunch_preprocess_data
RESULT_CSV_PATH exists: True
ISSUE_TAG_FLAT_PATH exists: True
LLM_INPUT_PATH exists: True

# 2. 여러 게임 한 번에 전처리 실행

`TARGET_GAME_KEYS`에 들어 있는 게임을 순서대로 전처리한다.

In [3]:
def process_postlaunch_preprocess_for_game(game_key):
    """03-1번 전체 전처리/우선순위 근거 생성 흐름을 게임 1개 기준으로 실행한다."""
    print("\n" + "=" * 90)
    print(f"03-1번 출시 후 전처리 실행: {game_key}")
    print("=" * 90)

    set_target_game_context(game_key)

    missing_inputs = [
        path for path in [RESULT_CSV_PATH, ISSUE_TAG_FLAT_PATH]
        if not path.exists()
    ]
    if missing_inputs:
        raise FileNotFoundError(
            "03번 LLM 산출물이 없습니다. 먼저 03번을 실행하세요: "
            + ", ".join(str(path) for path in missing_inputs)
        )

    # ============================================================
    # 03번 LLM 분류 결과 불러오기
    # ============================================================

    result_df = pd.read_csv(RESULT_CSV_PATH, dtype={"recommendationid": "string"})
    issue_df = pd.read_csv(ISSUE_TAG_FLAT_PATH, dtype={"recommendationid": "string"})

    print("리뷰 단위 LLM 결과:", result_df.shape)
    print("이슈 태그 단위 결과:", issue_df.shape)

    if RUN_CHECK_CELLS:
        display(result_df.head())
    if RUN_CHECK_CELLS:
        display(issue_df.head())


    # ============================================================
    # 필수 컬럼 확인
    # ============================================================

    required_result_cols = [
        "recommendationid", "appid", "game_name",
        "review_datetime", "release_date", "days_from_release", "release_period",
        "steam_label_text", "playtime_at_review_hours",
        "llm_sentiment", "llm_primary_issue", "llm_urgency_candidate",
        "llm_review_summary", "llm_suggested_action",
    ]

    required_issue_cols = [
        "recommendationid", "appid", "game_name",
        "steam_label_text", "llm_sentiment", "llm_urgency_candidate",
        "release_period", "playtime_at_review_hours",
        "llm_issue_category", "issue_name_kor", "llm_issue_sentiment", "llm_issue_evidence",
    ]

    missing_result_cols = [col for col in required_result_cols if col not in result_df.columns]
    missing_issue_cols = [col for col in required_issue_cols if col not in issue_df.columns]

    if missing_result_cols:
        raise ValueError(f"리뷰 결과 파일에 필요한 컬럼이 없습니다: {missing_result_cols}")

    if missing_issue_cols:
        raise ValueError(f"이슈 태그 파일에 필요한 컬럼이 없습니다: {missing_issue_cols}")

    print("필수 컬럼 확인 완료")


    # ============================================================
    # 공통 함수
    # ============================================================

    def safe_rate(numerator, denominator):
        """0으로 나누는 경우를 방지한 비율 계산 함수."""
        if denominator is None or pd.isna(denominator) or denominator == 0:
            return 0.0
        return round(float(numerator) / float(denominator), 4)


    def classify_playtime_stage(hours):
        """리뷰 작성 시점 플레이타임을 출시 후 운영 해석용 구간으로 분류한다."""
        if pd.isna(hours):
            return "unknown"
        if hours < 1:
            return "0-1h"
        if hours < 5:
            return "1-5h"
        if hours < 20:
            return "5-20h"
        if hours < 50:
            return "20-50h"
        return "50h+"


    def classify_recency_group(review_dt, max_dt):
        """분석 데이터 내 최신 리뷰일 기준 최근성 구간을 만든다."""
        if pd.isna(review_dt) or pd.isna(max_dt):
            return "unknown"

        diff_days = (max_dt - review_dt).days

        if diff_days <= 30:
            return "last_30d"
        if diff_days <= 60:
            return "31-60d"
        if diff_days <= 90:
            return "61-90d"
        return "older_90d"


    def normalize_text_value(x):
        """결측/공백 텍스트를 안정적으로 처리한다."""
        if pd.isna(x):
            return ""
        return str(x).strip()


    # ============================================================
    # 리뷰 단위 기본 전처리
    # ============================================================

    review_base = result_df.copy()

    # 날짜/숫자 타입 정리
    for col in ["review_datetime", "release_date"]:
        review_base[col] = pd.to_datetime(review_base[col], errors="coerce")

    numeric_cols = [
        "days_from_release", "playtime_at_review_hours", "votes_up",
        "weighted_vote_score", "sentiment_score",
    ]
    for col in numeric_cols:
        if col in review_base.columns:
            review_base[col] = pd.to_numeric(review_base[col], errors="coerce")

    # 문자열 정리
    text_cols = [
        "recommendationid", "game_name", "release_period", "steam_label_text",
        "llm_sentiment", "llm_primary_issue", "llm_urgency_candidate",
        "llm_review_summary", "llm_suggested_action",
    ]
    for col in text_cols:
        if col in review_base.columns:
            review_base[col] = review_base[col].apply(normalize_text_value)

    # 분석 기준일
    # recent_30d는 실제 오늘 기준 최근 30일이 아니라,
    # 분석 데이터 내 최신 리뷰일을 기준으로 계산한 상대적 최근성 구간이다.
    MAX_REVIEW_DATETIME = review_base["review_datetime"].max()

    # 파생 구간/플래그
    review_base["playtime_stage"] = review_base["playtime_at_review_hours"].apply(classify_playtime_stage)
    review_base["review_recency_group"] = review_base["review_datetime"].apply(lambda x: classify_recency_group(x, MAX_REVIEW_DATETIME))

    review_base["steam_negative_flag"] = review_base["steam_label_text"].eq("negative")
    review_base["steam_positive_flag"] = review_base["steam_label_text"].eq("positive")
    review_base["llm_negative_or_mixed_flag"] = review_base["llm_sentiment"].isin(["negative", "mixed"])
    review_base["llm_positive_flag"] = review_base["llm_sentiment"].eq("positive")
    review_base["high_urgency_flag"] = review_base["llm_urgency_candidate"].eq("high")
    review_base["early_playtime_flag"] = review_base["playtime_stage"].isin(["0-1h", "1-5h"])
    review_base["recent_30d_flag"] = review_base["review_recency_group"].eq("last_30d")

    # 저장 컬럼 정리
    review_base_cols = [
        "analysis_status",
        "recommendationid", "appid", "game_name",
        "review_datetime", "release_date", "days_from_release", "release_period", "review_recency_group",
        "steam_label_text", "steam_positive_flag", "steam_negative_flag",
        "playtime_at_review_hours", "playtime_stage", "early_playtime_flag", "recent_30d_flag",
        "votes_up", "weighted_vote_score",
        "llm_sentiment", "sentiment_score", "llm_negative_or_mixed_flag", "llm_positive_flag",
        "llm_primary_issue", "llm_urgency_candidate", "high_urgency_flag",
        "llm_review_summary", "llm_suggested_action", "steam_llm_sentiment_relation",
    ]
    review_base_cols = [col for col in review_base_cols if col in review_base.columns]
    review_base = review_base[review_base_cols].copy()

    print("리뷰 단위 전처리 결과:", review_base.shape)
    print("최신 리뷰일:", MAX_REVIEW_DATETIME)
    if RUN_CHECK_CELLS:
        display(review_base.head())


    # ============================================================
    # 이슈 태그 단위 기본 전처리
    # ============================================================

    issue_base = issue_df.copy()

    # 날짜/최근성/리뷰 요약 등은 리뷰 단위 결과에서 가져온다.
    review_merge_cols = [
        "recommendationid", "review_datetime", "release_date", "days_from_release",
        "review_recency_group", "playtime_stage", "steam_negative_flag", "steam_positive_flag",
        "llm_negative_or_mixed_flag", "llm_positive_flag", "high_urgency_flag",
        "early_playtime_flag", "recent_30d_flag",
        "llm_review_summary", "llm_suggested_action", "steam_llm_sentiment_relation",
    ]
    review_merge_cols = [col for col in review_merge_cols if col in review_base.columns]

    issue_base = issue_base.merge(
        review_base[review_merge_cols].drop_duplicates("recommendationid"),
        on="recommendationid",
        how="left",
        suffixes=("", "_review"),
    )

    # 숫자 타입 정리
    for col in ["playtime_at_review_hours", "votes_up", "weighted_vote_score", "days_from_release"]:
        if col in issue_base.columns:
            issue_base[col] = pd.to_numeric(issue_base[col], errors="coerce")

    # 문자열 정리
    for col in [
        "recommendationid", "game_name", "steam_label_text", "llm_sentiment",
        "llm_primary_issue", "llm_urgency_candidate", "release_period",
        "llm_issue_category", "issue_name_kor", "llm_issue_sentiment", "llm_issue_evidence",
    ]:
        if col in issue_base.columns:
            issue_base[col] = issue_base[col].apply(normalize_text_value)

    # 이슈 태그 기준 감정 플래그
    issue_base["issue_positive_flag"] = issue_base["llm_issue_sentiment"].eq("positive")
    issue_base["issue_negative_or_mixed_flag"] = issue_base["llm_issue_sentiment"].isin(["negative", "mixed"])
    issue_base["issue_negative_flag"] = issue_base["llm_issue_sentiment"].eq("negative")
    issue_base["issue_mixed_flag"] = issue_base["llm_issue_sentiment"].eq("mixed")

    # 같은 리뷰 안에서 같은 이슈가 중복으로 들어온 경우 제거
    issue_review_base = issue_base.drop_duplicates(["recommendationid", "llm_issue_category"]).copy()

    print("이슈 태그 원본 행 수:", len(issue_base))
    print("리뷰-이슈 중복 제거 후 행 수:", len(issue_review_base))
    if RUN_CHECK_CELLS:
        display(issue_review_base.head())


    # ============================================================
    # 게임 단위 기본 요약
    # ============================================================

    def make_game_base(review_df, issue_review_df):
        rows = []

        for (appid, game_name), g in review_df.groupby(["appid", "game_name"], dropna=False):
            issue_g = issue_review_df[issue_review_df["appid"] == appid]

            review_count = g["recommendationid"].nunique()
            steam_positive_count = int(g["steam_positive_flag"].sum())
            steam_negative_count = int(g["steam_negative_flag"].sum())
            llm_positive_count = int(g["llm_positive_flag"].sum())
            llm_negative_mixed_count = int(g["llm_negative_or_mixed_flag"].sum())
            high_urgency_count = int(g["high_urgency_flag"].sum())

            rows.append({
                "appid": appid,
                "game_name": game_name,
                "review_count": review_count,
                "issue_tag_count": len(issue_g),
                "steam_positive_review_count": steam_positive_count,
                "steam_negative_review_count": steam_negative_count,
                "steam_positive_rate": safe_rate(steam_positive_count, review_count),
                "llm_positive_review_count": llm_positive_count,
                "llm_negative_mixed_review_count": llm_negative_mixed_count,
                "llm_negative_mixed_rate": safe_rate(llm_negative_mixed_count, review_count),
                "high_urgency_review_count": high_urgency_count,
                "high_urgency_rate": safe_rate(high_urgency_count, review_count),
                "first_review_datetime": g["review_datetime"].min(),
                "last_review_datetime": g["review_datetime"].max(),
                "mean_playtime_at_review_hours": round(g["playtime_at_review_hours"].mean(), 2),
                "median_playtime_at_review_hours": round(g["playtime_at_review_hours"].median(), 2),
            })

        return pd.DataFrame(rows)


    game_base = make_game_base(review_base, issue_review_base)

    print("게임 단위 요약:", game_base.shape)
    if RUN_CHECK_CELLS:
        display(game_base)


    # ============================================================
    # 대응 구분/우선 검토 힌트 함수
    # ============================================================
    # 튜터님 피드백 반영:
    # 패치·운영 우선순위는 LLM이 직접 판단하지 않는다.
    # 이 셀에서 사전에 정한 데이터 기준으로 action_group_hint와 rule_priority_hint를 계산한다.
    #
    # 수정 포인트:
    # - 기존 절대 기준만 사용하면 리뷰 수가 많은 게임에서 대부분 '상'으로 분류될 수 있다.
    # - 따라서 절대 기준으로 먼저 priority_candidate를 만들고,
    #   최종 rule_priority_hint는 이번 게임 안에서 상대적으로 먼저 봐야 할 상위 이슈만 '상'으로 제한한다.
    # - High urgency는 LLM 기반 보조 지표이므로 우선 검토 수준 계산에는 직접 사용하지 않는다.
    #
    # 핵심 기준:
    # 1. 해당 이슈가 리뷰에서 반복적으로 나타났는가
    # 2. 부정·혼합 맥락으로 자주 언급되었는가
    # 3. Steam 비추천 리뷰에서도 함께 나타났는가
    # 4. 최근 30일에도 반복되는가
    # 5. 이슈 성격상 즉시 확인이 필요한 기술/진행 방해 이슈인가

    # ------------------------------------------------------------
    # 실제 03번 LLM 결과의 llm_issue_category 값과 맞춘 이슈 그룹
    # ------------------------------------------------------------
    IMMEDIATE_ISSUES = {
        "crash",
        "save_progression",
        "save_progress",
        "bug",
        "performance",
        "optimization",
    }

    SHORT_TERM_ISSUES = {
        "gameplay_loop",
        "balance",
        "difficulty",
        "ui_ux",
        "control",
        "controls",
        "progression_grind",
    }

    LONG_TERM_ISSUES = {
        "content_volume",
        "content_amount",
        "story",
        "graphics_audio",
        "multiplayer",
        "monetization",
        "pricing",
        "price_value",
        "translation_localization",
    }

    STRENGTH_ISSUES = {"positive_praise"}
    OPS_ISSUES = {"developer_communication"}

    # ------------------------------------------------------------
    # 절대 기준 기반 우선순위 후보 기준
    # ------------------------------------------------------------
    # get_rule_priority_hint는 최종 우선순위가 아니라 priority_candidate 후보값을 만드는 데 사용한다.
    # 최종 rule_priority_hint는 apply_relative_priority에서 상대 순위 보정을 거쳐 결정한다.

    HIGH_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS = 20
    HIGH_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS = 10
    HIGH_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS = 5
    HIGH_PRIORITY_MIN_AFFECTED_REVIEWS = 50

    MID_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS = 10
    MID_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS = 5
    MID_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS = 3
    MID_PRIORITY_MIN_AFFECTED_REVIEWS = 20

    # ------------------------------------------------------------
    # 최종 '상' 개수 제한 기준
    # ------------------------------------------------------------
    # '상'은 단순히 문제가 있다는 뜻이 아니라,
    # 이번 분석 대상 게임에서 먼저 확인해야 하는 상위 이슈라는 의미로 제한한다.
    # - 최대 6개
    # - 전체 개선 대상 이슈의 30% 이내
    MAX_HIGH_ISSUES = 6
    MAX_HIGH_RATE = 0.30

    # 'other'는 원인이 명확하지 않으므로 수치가 커도 바로 '상'으로 올리지 않는다.
    # positive_praise는 강점 유지 항목이므로 개선 우선순위 '상'에서 제외한다.
    NO_HIGH_ISSUES = {
        "positive_praise",
        "other",
    }

    ACTION_GROUP_RANK = {
        "즉시 확인": 0,
        "단기 개선": 1,
        "운영 커뮤니케이션 개선": 2,
        "장기 검토": 3,
        "검토 필요": 4,
        "강점 유지": 5,
    }

    PATCH_OPS_NOTE_MAP = {
        "crash": "크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다.",
        "save_progression": "저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다.",
        "save_progress": "저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다.",
        "bug": "반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다.",
        "performance": "프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다.",
        "optimization": "최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.",
        "gameplay_loop": "반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다.",
        "balance": "전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다.",
        "difficulty": "초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.",
        "ui_ux": "메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다.",
        "control": "이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다.",
        "controls": "이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다.",
        "progression_grind": "반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.",
        "content_volume": "콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.",
        "content_amount": "콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.",
        "story": "서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다.",
        "graphics_audio": "그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.",
        "multiplayer": "멀티플레이 요구가 반복되는 경우 개발 범위와 수요를 장기 로드맵에서 검토한다.",
        "monetization": "가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다.",
        "pricing": "가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.",
        "price_value": "가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.",
        "translation_localization": "번역/현지화 불만이 실제 이해도와 진행 경험에 영향을 주는지 검토한다.",
        "developer_communication": "패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다.",
        "positive_praise": "긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",
        "other": "세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.",
    }


    def get_action_group_hint(row):
        """이슈 성격과 부정 맥락을 기준으로 대응 구분을 계산한다."""
        issue = row["llm_issue_category"]
        affected = int(row["affected_review_count"])
        positive = int(row["positive_review_count"])
        neg_mixed = int(row["negative_mixed_review_count"])
        steam_negative = int(row["steam_negative_review_count"])

        # 긍정 칭찬은 개선 우선순위가 아니라 유지할 강점으로 분리한다.
        if issue in STRENGTH_ISSUES and positive >= neg_mixed:
            return "강점 유지"

        # 즉시 확인은 크래시/저장/버그/성능/최적화처럼 플레이를 직접 방해할 수 있는 이슈로 제한한다.
        # High urgency만으로 즉시 확인으로 올리지 않는다.
        if issue in IMMEDIATE_ISSUES and neg_mixed >= 5 and steam_negative >= 3:
            return "즉시 확인"

        if issue in SHORT_TERM_ISSUES and neg_mixed >= 5:
            return "단기 개선"

        if issue in OPS_ISSUES and (neg_mixed >= 3 or steam_negative >= 3):
            return "운영 커뮤니케이션 개선"

        if issue in LONG_TERM_ISSUES and neg_mixed >= 5:
            return "장기 검토"

        if positive > neg_mixed and positive >= max(10, affected * 0.5):
            return "강점 유지"

        return "검토 필요"


    def get_rule_priority_hint(row):
        """절대 기준 기반 우선 검토 후보값을 계산한다.

        주의:
        - 이 함수의 결과는 최종 rule_priority_hint가 아니라 priority_candidate로 사용한다.
        - 최종 rule_priority_hint는 apply_relative_priority에서 상대 순위 보정을 거친다.
        - High urgency는 LLM 기반 보조 지표이므로 이 함수의 계산식에 넣지 않는다.
        """
        action_group = row["action_group_hint"]
        affected = int(row["affected_review_count"])
        neg_mixed = int(row["negative_mixed_review_count"])
        steam_negative = int(row["steam_negative_review_count"])
        recent_negative = int(row["recent_30d_negative_mixed_review_count"])

        if action_group == "강점 유지":
            return "하"

        # 상 후보: 부정·혼합 반복 + Steam 비추천 맥락 + 최근성 또는 큰 반복 규모가 함께 확인되는 경우
        high_by_recent = (
            neg_mixed >= HIGH_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS
            and steam_negative >= HIGH_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS
            and recent_negative >= HIGH_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS
        )

        high_by_volume = (
            affected >= HIGH_PRIORITY_MIN_AFFECTED_REVIEWS
            and neg_mixed >= HIGH_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS
            and steam_negative >= HIGH_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS
        )

        # 즉시 확인 그룹은 기술/진행 차단 가능성이 있으므로 최근성 기준이 조금 약해도 상 후보로 둔다.
        high_by_blocking_issue = (
            action_group == "즉시 확인"
            and neg_mixed >= 15
            and steam_negative >= 10
        )

        if high_by_recent or high_by_volume or high_by_blocking_issue:
            return "상"

        # 중 후보: 부정·혼합 또는 Steam 비추천 맥락이 일정 수준 확인되는 경우
        mid_by_negative = (
            neg_mixed >= MID_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS
            and steam_negative >= MID_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS
        )

        mid_by_recent = (
            recent_negative >= MID_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS
            and steam_negative >= 1
        )

        mid_by_volume = (
            affected >= MID_PRIORITY_MIN_AFFECTED_REVIEWS
            and neg_mixed >= 5
        )

        if mid_by_negative or mid_by_recent or mid_by_volume:
            return "중"

        return "하"


    def apply_relative_priority(issue_summary):
        """절대 기준 후보값을 바탕으로 최종 상/중/하를 상대적으로 보정한다.

        목적:
        - 리뷰 수가 많은 게임에서 대부분의 이슈가 '상'으로 나오는 문제를 줄인다.
        - '상'은 이번 게임에서 먼저 확인할 상위 이슈로 제한한다.
        - LLM의 High urgency는 직접 사용하지 않는다.
        """
        out = issue_summary.copy()

        # 1. 절대 기준 기반 후보값 생성
        if "priority_candidate" not in out.columns:
            out["priority_candidate"] = out.apply(get_rule_priority_hint, axis=1)

        # 2. 기본값은 하
        out["rule_priority_hint"] = "하"
        out["priority_selection_note"] = "절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함"

        # 3. 개선 우선순위 산정 대상
        priority_target_mask = (
            out["action_group_hint"].ne("강점 유지")
            & ~out["llm_issue_category"].isin(STRENGTH_ISSUES)
        )

        target_count = int(priority_target_mask.sum())
        max_high_count = min(
            MAX_HIGH_ISSUES,
            max(1, int(np.ceil(target_count * MAX_HIGH_RATE)))
        )

        # 4. 기존 절대 기준에서 '상' 후보였던 이슈 중,
        #    기타/강점 항목은 최종 '상'에서 제외한다.
        high_candidate_mask = (
            priority_target_mask
            & out["priority_candidate"].eq("상")
            & ~out["llm_issue_category"].isin(NO_HIGH_ISSUES)
        )

        high_candidates = out[high_candidate_mask].copy()

        if len(high_candidates) > 0:
            high_candidates["action_group_rank"] = (
                high_candidates["action_group_hint"]
                .map(ACTION_GROUP_RANK)
                .fillna(9)
            )

            # 대응 긴급도가 높은 그룹을 먼저 보고,
            # 같은 그룹 안에서는 부정·혼합, Steam 비추천, 최근 반복, 전체 언급 규모가 큰 순서로 정렬한다.
            high_candidates = high_candidates.sort_values(
                [
                    "action_group_rank",
                    "negative_mixed_review_count",
                    "steam_negative_review_count",
                    "recent_30d_negative_mixed_review_count",
                    "affected_review_count",
                ],
                ascending=[True, False, False, False, False],
            )

            high_index = high_candidates.head(max_high_count).index
            out.loc[high_index, "rule_priority_hint"] = "상"
            out.loc[high_index, "priority_selection_note"] = (
                f"절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 {max_high_count}개로 유지"
            )

        # 5. 절대 기준에서는 상 후보였지만 최종 상위 이슈에 들지 못한 항목은 중으로 내린다.
        #    문제 근거가 없다는 뜻이 아니라, 이번 게임에서 최우선 확인 대상은 아니라는 의미다.
        demoted_high_mask = (
            priority_target_mask
            & out["priority_candidate"].eq("상")
            & out["rule_priority_hint"].ne("상")
        )
        out.loc[demoted_high_mask, "rule_priority_hint"] = "중"
        out.loc[demoted_high_mask, "priority_selection_note"] = (
            "절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정"
        )

        # 6. 절대 기준 중 후보는 중으로 유지한다.
        mid_mask = (
            priority_target_mask
            & out["priority_candidate"].eq("중")
            & out["rule_priority_hint"].ne("상")
        )
        out.loc[mid_mask, "rule_priority_hint"] = "중"
        out.loc[mid_mask, "priority_selection_note"] = "절대 기준상 '중' 후보로 분류"

        # 7. 기타 이슈는 원인이 명확하지 않으므로 최종 상으로 올리지 않는다.
        other_mask = out["llm_issue_category"].eq("other")
        out.loc[other_mask & out["rule_priority_hint"].eq("상"), "rule_priority_hint"] = "중"
        out.loc[other_mask, "priority_selection_note"] = (
            "기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리"
        )

        # 8. 강점 유지 항목은 개선 우선순위가 아니므로 하로 둔다.
        strength_mask = out["action_group_hint"].eq("강점 유지")
        out.loc[strength_mask, "rule_priority_hint"] = "하"
        out.loc[strength_mask, "priority_selection_note"] = "강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리"

        return out


    def get_priority_rule_detail(row):
        """우선순위가 어떤 규칙 때문에 부여되었는지 설명용 라벨을 만든다."""
        priority = row["rule_priority_hint"]
        candidate = row.get("priority_candidate", priority)
        action_group = row["action_group_hint"]
        affected = int(row["affected_review_count"])
        neg_mixed = int(row["negative_mixed_review_count"])
        steam_negative = int(row["steam_negative_review_count"])
        recent_negative = int(row["recent_30d_negative_mixed_review_count"])

        if action_group == "강점 유지":
            return "강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리"

        if row["llm_issue_category"] == "other":
            return "기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리"

        if priority == "상":
            return "절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈"

        if priority == "중" and candidate == "상":
            return "절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정"

        if priority == "중":
            if neg_mixed >= MID_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS and steam_negative >= MID_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS:
                return "부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인"
            if recent_negative >= MID_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS:
                return "최근 30일 부정·혼합 반복이 일부 확인"
            if affected >= MID_PRIORITY_MIN_AFFECTED_REVIEWS:
                return "전체 반복 규모는 있으나 상 기준에는 미달"
            return "중 우선순위 규칙 충족"

        return "반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함"


    def build_priority_reason(row):
        """표와 LLM 입력에 넣을 근거 문장을 만든다."""
        affected = int(row["affected_review_count"])
        neg_mixed = int(row["negative_mixed_review_count"])
        steam_negative = int(row["steam_negative_review_count"])
        recent_negative = int(row["recent_30d_negative_mixed_review_count"])
        early_negative = int(row["early_playtime_negative_mixed_review_count"])
        high = int(row["high_urgency_review_count"])

        parts = [
            f"영향 리뷰 {affected}개",
            f"부정·혼합 {neg_mixed}개",
            f"Steam 비추천 맥락 {steam_negative}개",
        ]

        if recent_negative > 0:
            parts.append(f"최근 30일 부정·혼합 {recent_negative}개")

        if early_negative > 0:
            parts.append(f"초반 플레이타임 부정·혼합 {early_negative}개")

        # High urgency는 우선순위 계산값이 아니라 보조 참고 지표로만 적는다.
        if high > 0:
            parts.append(f"High urgency 후보 {high}개(보조 참고)")

        if "priority_candidate" in row.index:
            parts.append(f"절대 기준 후보 {row['priority_candidate']}")

        parts.append(f"규칙 근거: {row['priority_rule_detail']}")
        return ", ".join(parts)


    # ============================================================
    # 이슈 단위 요약 생성
    # ============================================================

    def summarize_issue_group(g):
        affected = g["recommendationid"].nunique()

        positive_ids = g.loc[g["issue_positive_flag"], "recommendationid"].nunique()
        negative_ids = g.loc[g["issue_negative_flag"], "recommendationid"].nunique()
        mixed_ids = g.loc[g["issue_mixed_flag"], "recommendationid"].nunique()
        negative_mixed_ids = g.loc[g["issue_negative_or_mixed_flag"], "recommendationid"].nunique()

        high_ids = g.loc[g["high_urgency_flag"], "recommendationid"].nunique()
        high_negative_mixed_ids = g.loc[
            g["high_urgency_flag"] & g["issue_negative_or_mixed_flag"],
            "recommendationid"
        ].nunique()

        steam_negative_ids = g.loc[g["steam_negative_flag"], "recommendationid"].nunique()

        recent_30_ids = g.loc[g["recent_30d_flag"], "recommendationid"].nunique()
        recent_30_neg_mixed_ids = g.loc[
            g["recent_30d_flag"] & g["issue_negative_or_mixed_flag"],
            "recommendationid"
        ].nunique()

        early_neg_mixed_ids = g.loc[
            g["early_playtime_flag"] & g["issue_negative_or_mixed_flag"],
            "recommendationid"
        ].nunique()

        return pd.Series({
            "appid": g["appid"].iloc[0],
            "game_name": g["game_name"].iloc[0],
            "issue_name_kor": g["issue_name_kor"].iloc[0],
            "affected_review_count": affected,
            "positive_review_count": positive_ids,
            "negative_review_count": negative_ids,
            "mixed_review_count": mixed_ids,
            "negative_mixed_review_count": negative_mixed_ids,
            "steam_negative_review_count": steam_negative_ids,
            "high_urgency_review_count": high_ids,
            "high_urgency_negative_mixed_review_count": high_negative_mixed_ids,
            "recent_30d_review_count": recent_30_ids,
            "recent_30d_negative_mixed_review_count": recent_30_neg_mixed_ids,
            "early_playtime_negative_mixed_review_count": early_neg_mixed_ids,
            "avg_playtime_at_review_hours": round(g["playtime_at_review_hours"].mean(), 2),
            "median_playtime_at_review_hours": round(g["playtime_at_review_hours"].median(), 2),
        })


    issue_summary = (
        issue_review_base
        .groupby("llm_issue_category", dropna=False)
        .apply(summarize_issue_group, include_groups=False)
        .reset_index()
    )

    issue_summary["high_urgency_rate"] = issue_summary.apply(
        lambda row: safe_rate(row["high_urgency_review_count"], row["affected_review_count"]),
        axis=1,
    )
    issue_summary["negative_mixed_rate"] = issue_summary.apply(
        lambda row: safe_rate(row["negative_mixed_review_count"], row["affected_review_count"]),
        axis=1,
    )
    issue_summary["steam_negative_rate"] = issue_summary.apply(
        lambda row: safe_rate(row["steam_negative_review_count"], row["affected_review_count"]),
        axis=1,
    )
    issue_summary["recent_30d_negative_mixed_rate"] = issue_summary.apply(
        lambda row: safe_rate(row["recent_30d_negative_mixed_review_count"], row["recent_30d_review_count"]),
        axis=1,
    )

    # ------------------------------------------------------------
    # 대응 구분과 우선 검토 수준 계산
    # ------------------------------------------------------------
    # 1. action_group_hint: 이슈 성격 기반 대응 구분
    # 2. priority_candidate: 절대 기준으로 만든 우선 검토 후보
    # 3. rule_priority_hint: 후보값을 게임 내 상대 우선순위로 보정한 최종 상/중/하
    issue_summary["action_group_hint"] = issue_summary.apply(get_action_group_hint, axis=1)
    issue_summary["priority_candidate"] = issue_summary.apply(get_rule_priority_hint, axis=1)
    issue_summary = apply_relative_priority(issue_summary)

    issue_summary["priority_rule_detail"] = issue_summary.apply(get_priority_rule_detail, axis=1)
    issue_summary["priority_reason"] = issue_summary.apply(build_priority_reason, axis=1)
    issue_summary["patch_ops_note"] = issue_summary["llm_issue_category"].map(PATCH_OPS_NOTE_MAP).fillna("세부 리뷰 확인 후 대응 방향을 검토한다.")

    # 보고서에서 보기 좋은 정렬
    priority_order = {"상": 0, "중": 1, "하": 2}
    action_order = {"즉시 확인": 0, "단기 개선": 1, "운영 커뮤니케이션 개선": 2, "장기 검토": 3, "검토 필요": 4, "강점 유지": 5}

    issue_summary["priority_order"] = issue_summary["rule_priority_hint"].map(priority_order).fillna(9)
    issue_summary["action_order"] = issue_summary["action_group_hint"].map(action_order).fillna(9)

    issue_summary = issue_summary.sort_values(
        [
            "priority_order",
            "action_order",
            "negative_mixed_review_count",
            "steam_negative_review_count",
            "recent_30d_negative_mixed_review_count",
            "affected_review_count",
        ],
        ascending=[True, True, False, False, False, False],
    ).drop(columns=["priority_order", "action_order"])

    print("이슈 단위 요약:", issue_summary.shape)
    print("최종 우선 검토 수준 분포")
    if RUN_CHECK_CELLS:
        display(issue_summary["rule_priority_hint"].value_counts().rename_axis("rule_priority_hint").reset_index(name="issue_count"))
    print("절대 기준 후보 분포")
    if RUN_CHECK_CELLS:
        display(issue_summary["priority_candidate"].value_counts().rename_axis("priority_candidate").reset_index(name="issue_count"))
    if RUN_CHECK_CELLS:
        display(issue_summary.head(20))


    # ============================================================
    # 플레이타임 구간별 이슈 요약
    # ============================================================

    playtime_order = ["0-1h", "1-5h", "5-20h", "20-50h", "50h+", "unknown"]

    playtime_issue_summary = (
        issue_review_base
        .groupby(["playtime_stage", "llm_issue_category", "issue_name_kor"], dropna=False)
        .agg(
            affected_review_count=("recommendationid", "nunique"),
            negative_mixed_review_count=("issue_negative_or_mixed_flag", "sum"),
            high_urgency_review_count=("high_urgency_flag", "sum"),
            steam_negative_review_count=("steam_negative_flag", "sum"),
        )
        .reset_index()
    )

    playtime_issue_summary["playtime_stage"] = pd.Categorical(
        playtime_issue_summary["playtime_stage"],
        categories=playtime_order,
        ordered=True,
    )
    playtime_issue_summary = playtime_issue_summary.sort_values(
        ["playtime_stage", "negative_mixed_review_count", "high_urgency_review_count"],
        ascending=[True, False, False],
    )

    print("플레이타임 구간별 이슈 요약:", playtime_issue_summary.shape)
    if RUN_CHECK_CELLS:
        display(playtime_issue_summary.head(20))


    # ============================================================
    # 최근성 구간별 이슈 요약
    # ============================================================

    recency_order = ["last_30d", "31-60d", "61-90d", "older_90d", "unknown"]

    recency_issue_summary = (
        issue_review_base
        .groupby(["review_recency_group", "llm_issue_category", "issue_name_kor"], dropna=False)
        .agg(
            affected_review_count=("recommendationid", "nunique"),
            negative_mixed_review_count=("issue_negative_or_mixed_flag", "sum"),
            high_urgency_review_count=("high_urgency_flag", "sum"),
            steam_negative_review_count=("steam_negative_flag", "sum"),
        )
        .reset_index()
    )

    recency_issue_summary["review_recency_group"] = pd.Categorical(
        recency_issue_summary["review_recency_group"],
        categories=recency_order,
        ordered=True,
    )
    recency_issue_summary = recency_issue_summary.sort_values(
        ["review_recency_group", "negative_mixed_review_count", "high_urgency_review_count"],
        ascending=[True, False, False],
    )

    print("최근성 구간별 이슈 요약:", recency_issue_summary.shape)
    if RUN_CHECK_CELLS:
        display(recency_issue_summary.head(20))


    # ============================================================
    # 03-2 LLM 입력용 근거 문장 생성 함수
    # ============================================================

    def clean_evidence_text(x, max_len=180):
        text = normalize_text_value(x)
        text = re.sub(r"\s+", " ", text)
        if len(text) > max_len:
            return text[:max_len].rstrip() + "..."
        return text


    def collect_examples(issue_category, max_examples=5):
        """이슈별 대표 리뷰 요약/근거/개선 제안을 가져온다."""
        g = issue_review_base[issue_review_base["llm_issue_category"] == issue_category].copy()

        if len(g) == 0:
            return ""

        # 부정/혼합 + 최근 리뷰 + Steam 비추천 리뷰를 우선적으로 보여준다.
        # High urgency는 보조 참고 지표이므로 대표 리뷰 정렬에서 가장 앞 기준으로 쓰지 않는다.
        g["sort_negative"] = g["issue_negative_or_mixed_flag"].astype(int)
        g["sort_steam_negative"] = g["steam_negative_flag"].astype(int)
        g["sort_recent"] = g["recent_30d_flag"].astype(int)
        g["sort_votes"] = pd.to_numeric(g.get("votes_up", 0), errors="coerce").fillna(0)

        g = g.sort_values(
            ["sort_negative", "sort_steam_negative", "sort_recent", "sort_votes"],
            ascending=[False, False, False, False],
        )

        examples = []
        used = set()

        for _, row in g.iterrows():
            rec_id = row["recommendationid"]
            if rec_id in used:
                continue
            used.add(rec_id)

            evidence = clean_evidence_text(row.get("llm_issue_evidence", ""))
            summary = clean_evidence_text(row.get("llm_review_summary", ""))
            suggested = clean_evidence_text(row.get("llm_suggested_action", ""))

            example = (
                f"- steam_label={row.get('steam_label_text', '')}, "
                f"issue_sentiment={row.get('llm_issue_sentiment', '')}, "
                f"urgency_candidate={row.get('llm_urgency_candidate', '')}, "
                f"playtime={row.get('playtime_stage', '')}, "
                f"recency={row.get('review_recency_group', '')} | "
                f"근거: {evidence} | 요약: {summary} | LLM 개선 제안 후보: {suggested}"
            )
            examples.append(example)

            if len(examples) >= max_examples:
                break

        return "\n".join(examples)


    def build_llm_evidence_text(row):
        """03-2 프롬프트에 바로 넣기 쉬운 이슈별 근거 블록을 만든다."""
        examples = collect_examples(row["llm_issue_category"], max_examples=5)

        return f"""
    [ISSUE]
    issue_category: {row['llm_issue_category']}
    issue_name_kor: {row['issue_name_kor']}
    action_group_hint: {row['action_group_hint']}
    priority_candidate: {row.get('priority_candidate', '')}  # 절대 기준 후보
    rule_priority_hint: {row['rule_priority_hint']}  # 상대 보정 후 최종 우선 검토 수준
    priority_selection_note: {row.get('priority_selection_note', '')}
    priority_rule_detail: {row['priority_rule_detail']}
    affected_review_count: {int(row['affected_review_count'])}
    negative_mixed_review_count: {int(row['negative_mixed_review_count'])}
    steam_negative_review_count: {int(row['steam_negative_review_count'])}
    recent_30d_negative_mixed_review_count: {int(row['recent_30d_negative_mixed_review_count'])}
    early_playtime_negative_mixed_review_count: {int(row['early_playtime_negative_mixed_review_count'])}
    high_urgency_review_count: {int(row['high_urgency_review_count'])}  # 보조 참고 지표
    high_urgency_rate: {row['high_urgency_rate']}  # 보조 참고 지표
    priority_reason: {row['priority_reason']}
    patch_ops_note: {row['patch_ops_note']}
    대표 근거:
    {examples}
    [/ISSUE]
    """.strip()


    # ============================================================
    # 03-2 LLM 입력용 근거 테이블 생성
    # ============================================================

    patch_ops_evidence_base = issue_summary.copy()
    patch_ops_evidence_base["llm_evidence_text"] = patch_ops_evidence_base.apply(build_llm_evidence_text, axis=1)

    # 03-2에서 너무 많은 이슈를 모두 넣지 않도록 기본 정렬 상태로 저장한다.
    # 필요하면 03-2에서 상/중 우선순위만 필터링해서 사용할 수 있다.

    print("패치·운영 전략 생성용 근거 테이블:", patch_ops_evidence_base.shape)
    if RUN_CHECK_CELLS:
        display(patch_ops_evidence_base[[
        "llm_issue_category", "issue_name_kor", "action_group_hint",
        "priority_candidate", "rule_priority_hint", "priority_selection_note",
        "priority_rule_detail", "affected_review_count", "negative_mixed_review_count",
        "steam_negative_review_count", "high_urgency_review_count",
        "recent_30d_negative_mixed_review_count", "early_playtime_negative_mixed_review_count",
        "priority_reason", "patch_ops_note",
    ]].head(20))


    # ============================================================
    # Tableau/보고서용 원천 데이터 생성
    # ============================================================

    summary_cols_for_merge = [
        "llm_issue_category", "action_group_hint", "priority_candidate", "rule_priority_hint",
        "priority_selection_note", "priority_rule_detail", "priority_reason",
        "affected_review_count", "negative_mixed_review_count", "steam_negative_review_count",
        "high_urgency_review_count", "high_urgency_rate",
        "negative_mixed_rate", "steam_negative_rate",
        "recent_30d_negative_mixed_review_count",
        "early_playtime_negative_mixed_review_count",
        "patch_ops_note",
    ]

    summary_cols_for_merge = [col for col in summary_cols_for_merge if col in issue_summary.columns]

    tableau_source = issue_review_base.merge(
        issue_summary[summary_cols_for_merge],
        on="llm_issue_category",
        how="left",
        suffixes=("", "_issue_summary"),
    )

    # Tableau에서 쓰기 좋은 컬럼만 선택
    keep_cols = [
        "appid", "game_name", "recommendationid",
        "review_datetime", "release_date", "days_from_release", "release_period", "review_recency_group",
        "steam_label_text", "llm_sentiment", "steam_llm_sentiment_relation",
        "playtime_at_review_hours", "playtime_stage", "early_playtime_flag",
        "votes_up", "weighted_vote_score",
        "llm_urgency_candidate", "high_urgency_flag",
        "llm_issue_category", "issue_name_kor", "llm_issue_sentiment",
        "issue_positive_flag", "issue_negative_or_mixed_flag",
        "action_group_hint", "priority_candidate", "rule_priority_hint",
        "priority_selection_note", "priority_rule_detail", "priority_reason",
        "affected_review_count", "negative_mixed_review_count", "steam_negative_review_count",
        "high_urgency_review_count", "high_urgency_rate", "negative_mixed_rate", "steam_negative_rate",
        "recent_30d_negative_mixed_review_count", "early_playtime_negative_mixed_review_count",
        "patch_ops_note", "llm_issue_evidence",
    ]
    keep_cols = [col for col in keep_cols if col in tableau_source.columns]
    tableau_source = tableau_source[keep_cols].copy()

    print("Tableau/보고서 원천 데이터:", tableau_source.shape)
    if RUN_CHECK_CELLS:
        display(tableau_source.head())


    # ============================================================
    # CSV 저장
    # ============================================================
    # 03-1 산출물은 03-2에서 실제로 사용할 최소 파일만 저장한다.

    review_base.to_csv(POSTLAUNCH_REVIEW_BASE_PATH, index=False, encoding="utf-8-sig")
    issue_summary.to_csv(POSTLAUNCH_ISSUE_SUMMARY_PATH, index=False, encoding="utf-8-sig")
    patch_ops_evidence_base.to_csv(POSTLAUNCH_PATCH_OPS_EVIDENCE_BASE_PATH, index=False, encoding="utf-8-sig")
    tableau_source.to_csv(TABLEAU_POSTLAUNCH_SOURCE_PATH, index=False, encoding="utf-8-sig")

    saved_files = pd.DataFrame([
        {"파일명": POSTLAUNCH_REVIEW_BASE_PATH.name, "행 수": len(review_base), "역할": "리뷰 1개 단위 전처리 결과"},
        {"파일명": POSTLAUNCH_ISSUE_SUMMARY_PATH.name, "행 수": len(issue_summary), "역할": "이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약"},
        {"파일명": POSTLAUNCH_PATCH_OPS_EVIDENCE_BASE_PATH.name, "행 수": len(patch_ops_evidence_base), "역할": "03-2 LLM 패치·운영 전략 생성용 근거 데이터"},
        {"파일명": TABLEAU_POSTLAUNCH_SOURCE_PATH.name, "행 수": len(tableau_source), "역할": "Tableau/보고서용 원천 데이터"},
    ])

    print("저장 완료")
    print("저장 폴더:", POSTLAUNCH_PREPROCESS_DIR)
    if RUN_CHECK_CELLS:
        display(saved_files)

    # ============================================================
    # 우선순위 산정 로직 검증
    # ============================================================
    # 목적:
    # 튜터님 피드백이 코드에 실제로 반영되었는지 확인한다.
    #
    # 검증 방향:
    # 1. LLM의 High urgency가 rule_priority_hint 계산에 직접 들어가지 않았는지 확인한다.
    # 2. 최종 '상'은 반드시 rule 기반 priority_candidate == '상' 후보에서만 나오도록 확인한다.
    # 3. '즉시 확인' 이슈는 기술/진행 차단 가능성이 있는 이슈로만 제한한다.
    # 4. 리뷰 수가 많은 게임에서 '상'이 과도하게 많이 나오지 않도록 상대 보정이 적용되었는지 확인한다.
    # 5. 03-2 입력용 근거 텍스트가 비어 있지 않은지 확인한다.

    # ------------------------------------------------------------
    # 0. 검증용 기준
    # ------------------------------------------------------------
    # get_rule_priority_hint 내부의 blocking 예외 기준과 맞춘다.
    # 즉시 확인 이슈는 크래시/저장/진행/버그/성능처럼 플레이를 직접 막을 수 있으므로
    # 일반 '상' 기준보다 부정·혼합 기준을 조금 낮게 둔다.
    BLOCKING_HIGH_MIN_NEGATIVE_MIXED_REVIEWS = 15
    BLOCKING_HIGH_MIN_STEAM_NEGATIVE_REVIEWS = 10

    FORBIDDEN_PRIORITY_REFS = {
        "high_urgency_review_count",
        "high_urgency",
    }

    # ------------------------------------------------------------
    # 1. 리뷰 단위 결과는 recommendationid가 중복되면 안 된다.
    # ------------------------------------------------------------
    assert review_base["recommendationid"].is_unique, "review_base에 recommendationid 중복이 있습니다."

    # ------------------------------------------------------------
    # 2. 이슈 요약의 affected_review_count는 전체 분석 리뷰 수보다 클 수 없다.
    # ------------------------------------------------------------
    total_review_count = review_base["recommendationid"].nunique()

    affected_invalid = issue_summary[
        issue_summary["affected_review_count"] > total_review_count
    ]
    assert len(affected_invalid) == 0, affected_invalid[[
        "llm_issue_category",
        "issue_name_kor",
        "affected_review_count",
    ]]

    # ------------------------------------------------------------
    # 3. 부정·혼합 리뷰 수는 영향 리뷰 수보다 클 수 없다.
    # ------------------------------------------------------------
    negative_count_invalid = issue_summary[
        issue_summary["negative_mixed_review_count"] > issue_summary["affected_review_count"]
    ]
    assert len(negative_count_invalid) == 0, negative_count_invalid[[
        "llm_issue_category",
        "issue_name_kor",
        "affected_review_count",
        "negative_mixed_review_count",
    ]]

    # ------------------------------------------------------------
    # 4. High urgency 리뷰 수는 영향 리뷰 수보다 클 수 없다.
    # ------------------------------------------------------------
    high_urgency_count_invalid = issue_summary[
        issue_summary["high_urgency_review_count"] > issue_summary["affected_review_count"]
    ]
    assert len(high_urgency_count_invalid) == 0, high_urgency_count_invalid[[
        "llm_issue_category",
        "issue_name_kor",
        "affected_review_count",
        "high_urgency_review_count",
    ]]

    # ------------------------------------------------------------
    # 5. get_rule_priority_hint 함수 내부에서 High urgency 계열 컬럼을 직접 참조하지 않는지 확인한다.
    # ------------------------------------------------------------
    priority_func_names = {str(x) for x in get_rule_priority_hint.__code__.co_names}
    priority_func_consts = {
        str(x)
        for x in get_rule_priority_hint.__code__.co_consts
        if isinstance(x, str)
    }
    priority_func_refs = priority_func_names | priority_func_consts

    priority_forbidden_refs = [
        ref
        for ref in priority_func_refs
        if any(forbidden in ref for forbidden in FORBIDDEN_PRIORITY_REFS)
    ]

    assert len(priority_forbidden_refs) == 0, (
        "get_rule_priority_hint 계산 함수에서 High urgency 계열 참조가 발견되었습니다: "
        f"{priority_forbidden_refs}"
    )

    # ------------------------------------------------------------
    # 6. apply_relative_priority 함수 내부에서도 High urgency 계열 컬럼을 직접 참조하지 않는지 확인한다.
    # ------------------------------------------------------------
    relative_func_names = {str(x) for x in apply_relative_priority.__code__.co_names}
    relative_func_consts = {
        str(x)
        for x in apply_relative_priority.__code__.co_consts
        if isinstance(x, str)
    }
    relative_func_refs = relative_func_names | relative_func_consts

    relative_forbidden_refs = [
        ref
        for ref in relative_func_refs
        if any(forbidden in ref for forbidden in FORBIDDEN_PRIORITY_REFS)
    ]

    assert len(relative_forbidden_refs) == 0, (
        "apply_relative_priority 계산 함수에서 High urgency 계열 참조가 발견되었습니다: "
        f"{relative_forbidden_refs}"
    )

    # ------------------------------------------------------------
    # 7. priority_candidate == '상'은 명확한 rule 근거가 있어야 한다.
    # ------------------------------------------------------------
    # 일반 '상' 기준 1:
    # 부정·혼합 반복 + Steam 비추천 맥락 + 최근 30일 부정·혼합 반복
    candidate_high_by_recent = (
        (issue_summary["negative_mixed_review_count"] >= HIGH_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS)
        & (issue_summary["steam_negative_review_count"] >= HIGH_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS)
        & (issue_summary["recent_30d_negative_mixed_review_count"] >= HIGH_PRIORITY_MIN_RECENT_NEGATIVE_MIXED_REVIEWS)
    )

    # 일반 '상' 기준 2:
    # 영향 리뷰 규모가 크고, 부정·혼합 + Steam 비추천 근거가 함께 있는 경우
    candidate_high_by_volume = (
        (issue_summary["affected_review_count"] >= HIGH_PRIORITY_MIN_AFFECTED_REVIEWS)
        & (issue_summary["negative_mixed_review_count"] >= HIGH_PRIORITY_MIN_NEGATIVE_MIXED_REVIEWS)
        & (issue_summary["steam_negative_review_count"] >= HIGH_PRIORITY_MIN_STEAM_NEGATIVE_REVIEWS)
    )

    # 즉시 확인 예외 기준:
    # 기술/진행 차단 가능성이 있는 이슈는 일반 기준보다 낮은 부정·혼합 기준을 허용한다.
    candidate_high_by_blocking_issue = (
        (issue_summary["action_group_hint"] == "즉시 확인")
        & (issue_summary["negative_mixed_review_count"] >= BLOCKING_HIGH_MIN_NEGATIVE_MIXED_REVIEWS)
        & (issue_summary["steam_negative_review_count"] >= BLOCKING_HIGH_MIN_STEAM_NEGATIVE_REVIEWS)
    )

    candidate_high_has_rule_basis = (
        candidate_high_by_recent
        | candidate_high_by_volume
        | candidate_high_by_blocking_issue
    )

    candidate_high_without_rule_basis = issue_summary[
        (issue_summary["priority_candidate"] == "상")
        & ~candidate_high_has_rule_basis
    ]

    assert len(candidate_high_without_rule_basis) == 0, candidate_high_without_rule_basis[[
        "llm_issue_category",
        "issue_name_kor",
        "action_group_hint",
        "affected_review_count",
        "negative_mixed_review_count",
        "steam_negative_review_count",
        "recent_30d_negative_mixed_review_count",
        "priority_candidate",
    ]]

    # ------------------------------------------------------------
    # 8. 최종 '상'은 반드시 priority_candidate == '상' 후보에서만 나와야 한다.
    # ------------------------------------------------------------
    final_high_without_candidate = issue_summary[
        (issue_summary["rule_priority_hint"] == "상")
        & (issue_summary["priority_candidate"] != "상")
    ]

    assert len(final_high_without_candidate) == 0, final_high_without_candidate[[
        "llm_issue_category",
        "issue_name_kor",
        "priority_candidate",
        "rule_priority_hint",
        "priority_selection_note",
    ]]

    # ------------------------------------------------------------
    # 9. High urgency만 많고 rule 근거가 없는데 최종 '상'으로 올라간 이슈가 없어야 한다.
    # ------------------------------------------------------------
    # 여기서는 부정·혼합 20개 미만을 무조건 금지하지 않는다.
    # save_progression 같은 즉시 확인 이슈는 blocking 기준을 만족하면 '상'이 될 수 있기 때문이다.
    high_urgency_only_high = issue_summary[
        (issue_summary["rule_priority_hint"] == "상")
        & (issue_summary["high_urgency_review_count"] >= 10)
        & ~candidate_high_has_rule_basis
    ]

    assert len(high_urgency_only_high) == 0, high_urgency_only_high[[
        "llm_issue_category",
        "issue_name_kor",
        "action_group_hint",
        "high_urgency_review_count",
        "affected_review_count",
        "negative_mixed_review_count",
        "steam_negative_review_count",
        "recent_30d_negative_mixed_review_count",
        "priority_candidate",
        "rule_priority_hint",
    ]]

    # ------------------------------------------------------------
    # 10. 즉시 확인은 기술/진행 차단 가능성이 있는 이슈 그룹으로만 제한한다.
    # ------------------------------------------------------------
    immediate_invalid = issue_summary[
        (issue_summary["action_group_hint"] == "즉시 확인")
        & (~issue_summary["llm_issue_category"].isin(IMMEDIATE_ISSUES))
    ]

    assert len(immediate_invalid) == 0, immediate_invalid[[
        "llm_issue_category",
        "issue_name_kor",
        "action_group_hint",
    ]]

    # ------------------------------------------------------------
    # 11. 강점 유지 항목은 개선 우선순위 '상'으로 들어가면 안 된다.
    # ------------------------------------------------------------
    strength_high = issue_summary[
        (issue_summary["action_group_hint"] == "강점 유지")
        & (issue_summary["rule_priority_hint"] == "상")
    ]

    assert len(strength_high) == 0, strength_high[[
        "llm_issue_category",
        "issue_name_kor",
        "action_group_hint",
        "rule_priority_hint",
    ]]

    # ------------------------------------------------------------
    # 12. 기타 이슈는 원인이 명확하지 않으므로 최종 '상'으로 들어가면 안 된다.
    # ------------------------------------------------------------
    other_high = issue_summary[
        (issue_summary["llm_issue_category"] == "other")
        & (issue_summary["rule_priority_hint"] == "상")
    ]

    assert len(other_high) == 0, other_high[[
        "llm_issue_category",
        "issue_name_kor",
        "rule_priority_hint",
        "priority_selection_note",
    ]]

    # ------------------------------------------------------------
    # 13. 최종 '상' 개수는 상대 보정 기준을 넘으면 안 된다.
    # ------------------------------------------------------------
    priority_target_count = int((
        issue_summary["action_group_hint"].ne("강점 유지")
        & ~issue_summary["llm_issue_category"].isin(STRENGTH_ISSUES)
    ).sum())

    max_high_count = min(
        MAX_HIGH_ISSUES,
        max(1, int(np.ceil(priority_target_count * MAX_HIGH_RATE)))
    )

    actual_high_count = int((issue_summary["rule_priority_hint"] == "상").sum())

    assert actual_high_count <= max_high_count, (
        f"최종 '상' 이슈 수가 제한 기준을 초과했습니다: {actual_high_count} > {max_high_count}"
    )

    # ------------------------------------------------------------
    # 14. 절대 기준 상 후보였으나 최종 상이 아닌 항목은 중으로 조정되어야 한다.
    # ------------------------------------------------------------
    # 단, 강점 유지/기타 이슈는 별도 분리 대상이므로 예외로 둔다.
    demoted_invalid = issue_summary[
        (issue_summary["priority_candidate"] == "상")
        & (issue_summary["rule_priority_hint"] == "하")
        & (issue_summary["action_group_hint"] != "강점 유지")
        & (~issue_summary["llm_issue_category"].isin(NO_HIGH_ISSUES))
    ]

    assert len(demoted_invalid) == 0, demoted_invalid[[
        "llm_issue_category",
        "issue_name_kor",
        "priority_candidate",
        "rule_priority_hint",
        "priority_selection_note",
    ]]

    # ------------------------------------------------------------
    # 15. 03-2 입력용 근거 텍스트가 비어 있지 않은지 확인한다.
    # ------------------------------------------------------------
    evidence_empty = patch_ops_evidence_base[
        patch_ops_evidence_base["llm_evidence_text"].isna()
        | patch_ops_evidence_base["llm_evidence_text"].astype(str).str.strip().eq("")
    ]

    assert len(evidence_empty) == 0, evidence_empty[[
        "llm_issue_category",
        "issue_name_kor",
        "llm_evidence_text",
    ]]

    # ------------------------------------------------------------
    # 검증 결과 출력
    # ------------------------------------------------------------
    print("검증 통과")
    print("리뷰 수:", review_base["recommendationid"].nunique())
    print("리뷰-이슈 수:", len(issue_review_base))
    print("이슈 종류 수:", issue_summary["llm_issue_category"].nunique())

    print("절대 기준 후보 분포:")
    if RUN_CHECK_CELLS:
        display(
        issue_summary["priority_candidate"]
        .value_counts()
        .rename_axis("priority_candidate")
        .reset_index(name="issue_count")
    )

    print("최종 우선 검토 수준 분포:")
    if RUN_CHECK_CELLS:
        display(
        issue_summary["rule_priority_hint"]
        .value_counts()
        .rename_axis("rule_priority_hint")
        .reset_index(name="issue_count")
    )

    print(f"최종 '상' 제한 기준: 최대 {max_high_count}개")
    print("High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.")

    return {
        "game_key": game_key,
        "appid": TARGET_APPID,
        "game_name": TARGET_GAME_NAME,
        "status": "success",
        "review_base_rows": len(review_base),
        "issue_summary_rows": len(issue_summary),
        "patch_ops_evidence_rows": len(patch_ops_evidence_base),
        "tableau_source_rows": len(tableau_source),
        "preprocess_dir": str(POSTLAUNCH_PREPROCESS_DIR),
        "review_base_path": str(POSTLAUNCH_REVIEW_BASE_PATH),
        "issue_summary_path": str(POSTLAUNCH_ISSUE_SUMMARY_PATH),
        "patch_ops_evidence_base_path": str(POSTLAUNCH_PATCH_OPS_EVIDENCE_BASE_PATH),
        "tableau_source_path": str(TABLEAU_POSTLAUNCH_SOURCE_PATH),
        "error_message": "",
    }


def run_postlaunch_preprocess_multi_games(game_keys):
    """03-1번 출시 후 전처리를 여러 게임에 대해 순서대로 실행한다."""
    batch_logs = []

    for game_key in game_keys:
        try:
            log = process_postlaunch_preprocess_for_game(game_key)
        except Exception as e:
            log = {
                "game_key": game_key,
                "appid": None,
                "game_name": POSTLAUNCH_TARGET_GAMES.get(game_key, {}).get("game_name", ""),
                "status": "failed",
                "review_base_rows": None,
                "issue_summary_rows": None,
                "patch_ops_evidence_rows": None,
                "tableau_source_rows": None,
                "preprocess_dir": "",
                "review_base_path": "",
                "issue_summary_path": "",
                "patch_ops_evidence_base_path": "",
                "tableau_source_path": "",
                "error_message": str(e),
            }
            print(f"[실패] {game_key}: {e}")

        batch_logs.append(log)

    batch_log_df = pd.DataFrame(batch_logs)
    batch_log_path = RUNS_DIR / "03-1_postlaunch_preprocess_batch_log.csv"
    batch_log_df.to_csv(batch_log_path, index=False, encoding="utf-8-sig")

    print("\n" + "=" * 90)
    print("03-1번 여러 게임 실행 요약")
    print("=" * 90)
    print("batch log 저장:", batch_log_path)
    display(batch_log_df)

    return batch_log_df


if RUN_MULTI_GAME_MODE:
    batch_log_df = run_postlaunch_preprocess_multi_games(TARGET_GAME_KEYS)
else:
    single_log = process_postlaunch_preprocess_for_game(TARGET_GAME_KEY)
    display(pd.DataFrame([single_log]))

==========================================================================================
03-1번 출시 후 전처리 실행: heroes_of_hammerwatch_2
==========================================================================================
리뷰 단위 LLM 결과: (1000, 20)
이슈 태그 단위 결과: (1948, 15)

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,steam_label_text,playtime_at_review_hours,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_primary_issue,llm_issue_tags,llm_urgency_candidate,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,189880229,619820,Heroes of Hammerwatch II,2025-03-10 15:54:38,2025-01-14,55,D31-D90,negative,2.416667,3,0.510774,negative,1,save_progression,"[{""category"": ""save_progression"", ""sentiment"": ""negative"", ""evidence"": ""last 2 days I got my saved wiped out twice""}]",high,최근 2일 동안 세이브 데이터가 두 번이나 삭제되어 게임을 플레이할 수 없음.,"세이브 데이터 손실 원인 파악 및 클라우드 저장 시스템 점검, 데이터 복구 방안 검토.",exact_match
1,success,213786980,619820,Heroes of Hammerwatch II,2025-12-21 03:28:01,2025-01-14,341,D181+,positive,18.450000,12,0.655379,positive,5,positive_praise,"[{""category"": ""progression_grind"", ""sentiment"": ""neutral"", ""evidence"": ""This game can appear to be very grindy at fi...",low,"초반에는 성장이 더뎌 지루할 수 있으나, 캐릭터와 마을을 육성할수록 매우 재미있어지는 게임. 싱글 플레이 경험에 만족함.","초반 진입 장벽을 낮추기 위한 튜토리얼 강화 또는 가이드 제공, 현재의 성장 루프 유지 및 강화.",exact_match
2,success,215844634,619820,Heroes of Hammerwatch II,2026-01-12 19:36:41,2025-01-14,363,D181+,positive,30.783333,0,0.500000,mixed,3,save_progression,"[{""category"": ""save_progression"", ""sentiment"": ""negative"", ""evidence"": ""switched to linux and I lost all my data in ...",high,"게임 자체는 매우 재미있으나, 리눅스로 OS를 변경하는 과정에서 세이브 데이터가 모두 소실되어 플레이를 중단함.",OS 변경 또는 PC 교체 시 세이브 데이터 호환성 및 클라우드 동기화 문제 조사 및 수정.,partial_match
3,success,185667334,619820,Heroes of Hammerwatch II,2025-01-15 20:08:55,2025-01-14,1,D0-D30,positive,5.750000,2,0.505464,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""새로운 그래픽과 유연한 클래스 시스템, 훌륭한 협동 게임 경험""}, {""categ...",low,"그래픽과 클래스 시스템이 개선되었으며, 가격 대비 플레이 타임이 훌륭한 협동 게임으로 평가함.","현재의 그래픽 스타일과 유연한 클래스 시스템을 유지하고, 협동 플레이의 재미를 강화하는 업데이트를 지속할 것.",exact_match
4,success,186334804,619820,Heroes of Hammerwatch II,2025-01-25 00:44:23,2025-01-14,11,D0-D30,negative,3.200000,2,0.536785,negative,1,content_volume,"[{""category"": ""gameplay_loop"", ""sentiment"": ""negative"", ""evidence"": ""매우 반복적이고 게임플레이 다양성이 부족함""}, {""category"": ""conten...",high,"게임플레이가 반복적이고 콘텐츠가 부족하며, 현대적인 경쟁작들에 비해 전반적으로 수준이 낮다고 평가함.","적 종류 추가, 스킬 트리 확장, 게임플레이 다양성을 높일 수 있는 콘텐츠 업데이트 고려 필요.",exact_match

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence
0,189880229,619820,Heroes of Hammerwatch II,negative,negative,save_progression,high,D31-D90,2.416667,3,0.510774,save_progression,저장/진행,negative,last 2 days I got my saved wiped out twice
1,213786980,619820,Heroes of Hammerwatch II,positive,positive,positive_praise,low,D181+,18.450000,12,0.655379,progression_grind,성장/반복 노가다,neutral,This game can appear to be very grindy at first
2,213786980,619820,Heroes of Hammerwatch II,positive,positive,positive_praise,low,D181+,18.450000,12,0.655379,positive_praise,긍정 칭찬,positive,I find myself keep coming back and having a great time
3,215844634,619820,Heroes of Hammerwatch II,positive,mixed,save_progression,high,D181+,30.783333,0,0.500000,save_progression,저장/진행,negative,switched to linux and I lost all my data in the game
4,215844634,619820,Heroes of Hammerwatch II,positive,mixed,save_progression,high,D181+,30.783333,0,0.500000,positive_praise,긍정 칭찬,positive,I played the game for 30 hours and it was really fun!

필수 컬럼 확인 완료
리뷰 단위 전처리 결과: (1000, 28)
최신 리뷰일: 2026-04-26 14:59:21

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,steam_positive_flag,steam_negative_flag,playtime_at_review_hours,playtime_stage,early_playtime_flag,recent_30d_flag,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_negative_or_mixed_flag,llm_positive_flag,llm_primary_issue,llm_urgency_candidate,high_urgency_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,189880229,619820,Heroes of Hammerwatch II,2025-03-10 15:54:38,2025-01-14,55,D31-D90,older_90d,negative,False,True,2.416667,1-5h,True,False,3,0.510774,negative,1,True,False,save_progression,high,True,최근 2일 동안 세이브 데이터가 두 번이나 삭제되어 게임을 플레이할 수 없음.,"세이브 데이터 손실 원인 파악 및 클라우드 저장 시스템 점검, 데이터 복구 방안 검토.",exact_match
1,success,213786980,619820,Heroes of Hammerwatch II,2025-12-21 03:28:01,2025-01-14,341,D181+,older_90d,positive,True,False,18.450000,5-20h,False,False,12,0.655379,positive,5,False,True,positive_praise,low,False,"초반에는 성장이 더뎌 지루할 수 있으나, 캐릭터와 마을을 육성할수록 매우 재미있어지는 게임. 싱글 플레이 경험에 만족함.","초반 진입 장벽을 낮추기 위한 튜토리얼 강화 또는 가이드 제공, 현재의 성장 루프 유지 및 강화.",exact_match
2,success,215844634,619820,Heroes of Hammerwatch II,2026-01-12 19:36:41,2025-01-14,363,D181+,older_90d,positive,True,False,30.783333,20-50h,False,False,0,0.500000,mixed,3,True,False,save_progression,high,True,"게임 자체는 매우 재미있으나, 리눅스로 OS를 변경하는 과정에서 세이브 데이터가 모두 소실되어 플레이를 중단함.",OS 변경 또는 PC 교체 시 세이브 데이터 호환성 및 클라우드 동기화 문제 조사 및 수정.,partial_match
3,success,185667334,619820,Heroes of Hammerwatch II,2025-01-15 20:08:55,2025-01-14,1,D0-D30,older_90d,positive,True,False,5.750000,5-20h,False,False,2,0.505464,positive,5,False,True,positive_praise,low,False,"그래픽과 클래스 시스템이 개선되었으며, 가격 대비 플레이 타임이 훌륭한 협동 게임으로 평가함.","현재의 그래픽 스타일과 유연한 클래스 시스템을 유지하고, 협동 플레이의 재미를 강화하는 업데이트를 지속할 것.",exact_match
4,success,186334804,619820,Heroes of Hammerwatch II,2025-01-25 00:44:23,2025-01-14,11,D0-D30,older_90d,negative,False,True,3.200000,1-5h,True,False,2,0.536785,negative,1,True,False,content_volume,high,True,"게임플레이가 반복적이고 콘텐츠가 부족하며, 현대적인 경쟁작들에 비해 전반적으로 수준이 낮다고 평가함.","적 종류 추가, 스킬 트리 확장, 게임플레이 다양성을 높일 수 있는 콘텐츠 업데이트 고려 필요.",exact_match

이슈 태그 원본 행 수: 1948
리뷰-이슈 중복 제거 후 행 수: 1903

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence,review_datetime,release_date,days_from_release,review_recency_group,playtime_stage,steam_negative_flag,steam_positive_flag,llm_negative_or_mixed_flag,llm_positive_flag,high_urgency_flag,early_playtime_flag,recent_30d_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation,issue_positive_flag,issue_negative_or_mixed_flag,issue_negative_flag,issue_mixed_flag
0,189880229,619820,Heroes of Hammerwatch II,negative,negative,save_progression,high,D31-D90,2.416667,3,0.510774,save_progression,저장/진행,negative,last 2 days I got my saved wiped out twice,2025-03-10 15:54:38,2025-01-14,55,older_90d,1-5h,True,False,True,False,True,True,False,최근 2일 동안 세이브 데이터가 두 번이나 삭제되어 게임을 플레이할 수 없음.,"세이브 데이터 손실 원인 파악 및 클라우드 저장 시스템 점검, 데이터 복구 방안 검토.",exact_match,False,True,True,False
1,213786980,619820,Heroes of Hammerwatch II,positive,positive,positive_praise,low,D181+,18.450000,12,0.655379,progression_grind,성장/반복 노가다,neutral,This game can appear to be very grindy at first,2025-12-21 03:28:01,2025-01-14,341,older_90d,5-20h,False,True,False,True,False,False,False,"초반에는 성장이 더뎌 지루할 수 있으나, 캐릭터와 마을을 육성할수록 매우 재미있어지는 게임. 싱글 플레이 경험에 만족함.","초반 진입 장벽을 낮추기 위한 튜토리얼 강화 또는 가이드 제공, 현재의 성장 루프 유지 및 강화.",exact_match,False,False,False,False
2,213786980,619820,Heroes of Hammerwatch II,positive,positive,positive_praise,low,D181+,18.450000,12,0.655379,positive_praise,긍정 칭찬,positive,I find myself keep coming back and having a great time,2025-12-21 03:28:01,2025-01-14,341,older_90d,5-20h,False,True,False,True,False,False,False,"초반에는 성장이 더뎌 지루할 수 있으나, 캐릭터와 마을을 육성할수록 매우 재미있어지는 게임. 싱글 플레이 경험에 만족함.","초반 진입 장벽을 낮추기 위한 튜토리얼 강화 또는 가이드 제공, 현재의 성장 루프 유지 및 강화.",exact_match,True,False,False,False
3,215844634,619820,Heroes of Hammerwatch II,positive,mixed,save_progression,high,D181+,30.783333,0,0.500000,save_progression,저장/진행,negative,switched to linux and I lost all my data in the game,2026-01-12 19:36:41,2025-01-14,363,older_90d,20-50h,False,True,True,False,True,False,False,"게임 자체는 매우 재미있으나, 리눅스로 OS를 변경하는 과정에서 세이브 데이터가 모두 소실되어 플레이를 중단함.",OS 변경 또는 PC 교체 시 세이브 데이터 호환성 및 클라우드 동기화 문제 조사 및 수정.,partial_match,False,True,True,False
4,215844634,619820,Heroes of Hammerwatch II,positive,mixed,save_progression,high,D181+,30.783333,0,0.500000,positive_praise,긍정 칭찬,positive,I played the game for 30 hours and it was really fun!,2026-01-12 19:36:41,2025-01-14,363,older_90d,20-50h,False,True,True,False,True,False,False,"게임 자체는 매우 재미있으나, 리눅스로 OS를 변경하는 과정에서 세이브 데이터가 모두 소실되어 플레이를 중단함.",OS 변경 또는 PC 교체 시 세이브 데이터 호환성 및 클라우드 동기화 문제 조사 및 수정.,partial_match,True,False,False,False

게임 단위 요약: (1, 16)

,appid,game_name,review_count,issue_tag_count,steam_positive_review_count,steam_negative_review_count,steam_positive_rate,llm_positive_review_count,llm_negative_mixed_review_count,llm_negative_mixed_rate,high_urgency_review_count,high_urgency_rate,first_review_datetime,last_review_datetime,mean_playtime_at_review_hours,median_playtime_at_review_hours
0,619820,Heroes of Hammerwatch II,1000,1903,462,538,0.462,372,625,0.625,288,0.288,2025-01-15 00:49:00,2026-04-26 14:59:21,32.03,16.14

이슈 단위 요약: (20, 28)
최종 우선 검토 수준 분포

  rule_priority_hint  issue_count
0                  중           10
1                  상            6
2                  하            4

절대 기준 후보 분포

  priority_candidate  issue_count
0                  상           12
1                  중            4
2                  하            4

,llm_issue_category,appid,game_name,issue_name_kor,affected_review_count,positive_review_count,negative_review_count,mixed_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_negative_mixed_review_count,recent_30d_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,avg_playtime_at_review_hours,median_playtime_at_review_hours,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_rate,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,patch_ops_note
17,save_progression,619820,Heroes of Hammerwatch II,저장/진행,85,2,82,0,82,77,78,78,1,1,15,44.89,26.97,0.9176,0.9647,0.9059,1.0000,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 85개, 부정·혼합 82개, Steam 비추천 맥락 77개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 78개(보조 참고), 절대 기준 후보 상,...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
1,bug,619820,Heroes of Hammerwatch II,버그,82,0,79,0,79,61,61,61,0,0,17,39.17,22.98,0.7439,0.9634,0.7439,0.0000,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 82개, 부정·혼합 79개, Steam 비추천 맥락 61개, 초반 플레이타임 부정·혼합 17개, High urgency 후보 61개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
13,performance,619820,Heroes of Hammerwatch II,성능,33,2,29,1,30,22,28,28,1,1,8,23.43,10.10,0.8485,0.9091,0.6667,1.0000,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 33개, 부정·혼합 30개, Steam 비추천 맥락 22개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 28개(보조 참고), 절대 기준 후보 상, ...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
4,crash,619820,Heroes of Hammerwatch II,크래시,21,0,21,0,21,21,21,21,0,0,8,20.37,9.53,1.0000,1.0000,1.0000,0.0000,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 21개, 부정·혼합 21개, Steam 비추천 맥락 21개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 21개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
7,gameplay_loop,619820,Heroes of Hammerwatch II,게임플레이 루프,306,24,263,5,268,240,82,80,9,7,69,31.17,14.18,0.2680,0.8758,0.7843,0.7778,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 306개, 부정·혼합 268개, Steam 비추천 맥락 240개, 최근 30일 부정·혼합 7개, 초반 플레이타임 부정·혼합 69개, High urgency 후보 82개(보조 참고), 절대 기준 후보...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
0,balance,619820,Heroes of Hammerwatch II,밸런스,178,4,171,0,171,137,74,74,3,3,16,45.97,31.02,0.4157,0.9607,0.7697,1.0000,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 178개, 부정·혼합 171개, Steam 비추천 맥락 137개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 16개, High urgency 후보 74개(보조 참고), 절대 기준 후보...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
16,progression_grind,619820,Heroes of Hammerwatch II,성장/반복 노가다,179,11,149,3,152,136,46,46,3,3,32,36.55,16.62,0.2570,0.8492,0.7598,1.0000,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 179개, 부정·혼합 152개, Steam 비추천 맥락 136개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 32개, High urgency 후보 46개(보조 참고), 절대 기준 후보...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
19,ui_ux,619820,Heroes of Hammerwatch II,UI/UX,69,0,66,0,66,46,31,31,1,1,20,23.60,13.08,0.4493,0.9565,0.6667,1.0000,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 69개, 부정·혼합 66개, Steam 비추천 맥락 46개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 20개, High urgency 후보 31개(보조 참고), 절대 기준 후보 상,...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
6,difficulty,619820,Heroes of Hammerwatch II,난이도,58,8,43,1,44,36,19,19,1,1,14,23.29,10.72,0.3276,0.7586,0.6207,1.0000,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 58개, 부정·혼합 44개, Steam 비추천 맥락 36개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 19개(보조 참고), 절대 기준 후보 상,...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
3,control,619820,Heroes of Hammerwatch II,조작감,16,0,16,0,16,14,13,13,0,0,8,11.92,4.72,0.8125,1.0000,0.8750,0.0000,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 16개, 부정·혼합 16개, Steam 비추천 맥락 14개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 13개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
5,developer_communication,619820,Heroes of Hammerwatch II,개발사 소통,26,2,23,0,23,23,21,21,0,0,2,51.66,30.21,0.8077,0.8846,0.8846,0.0000,운영 커뮤니케이션 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 26개, 부정·혼합 23개, Steam 비추천 맥락 23개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 21개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
2,content_volume,619820,Heroes of Hammerwatch II,콘텐츠 분량,166,9,136,1,137,112,33,33,0,0,16,38.20,22.00,0.1988,0.8253,0.6747,0.0000,장기 검토,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 166개, 부정·혼합 137개, Steam 비추천 맥락 112개, 초반 플레이타임 부정·혼합 16개, High urgency 후보 33개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 ...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
8,graphics_audio,619820,Heroes of Hammerwatch II,그래픽/사운드,72,18,52,1,53,56,24,20,2,2,21,16.53,11.03,0.3333,0.7361,0.7778,1.0000,장기 검토,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 72개, 부정·혼합 53개, Steam 비추천 맥락 56개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 24개(보조 참고), 절대 기준 후보 상,...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
15,price_value,619820,Heroes of Hammerwatch II,가격/가치,30,9,21,0,21,21,8,8,0,0,3,30.07,16.53,0.2667,0.7000,0.7000,0.0000,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 21개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
10,multiplayer_network,619820,Heroes of Hammerwatch II,멀티/네트워크,81,13,64,1,65,55,52,52,1,1,17,40.97,14.57,0.6420,0.8025,0.6790,1.0000,검토 필요,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 81개, 부정·혼합 65개, Steam 비추천 맥락 55개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 17개, High urgency 후보 52개(보조 참고), 절대 기준 후보 상,...",세부 리뷰 확인 후 대응 방향을 검토한다.
12,other,619820,Heroes of Hammerwatch II,기타,42,0,37,0,37,36,13,13,0,0,9,29.32,19.17,0.3095,0.8810,0.8571,0.0000,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,"영향 리뷰 42개, 부정·혼합 37개, Steam 비추천 맥락 36개, 초반 플레이타임 부정·혼합 9개, High urgency 후보 13개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 ...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
11,optimization,619820,Heroes of Hammerwatch II,최적화,8,1,6,0,6,5,6,6,0,0,1,69.59,31.81,0.7500,0.7500,0.6250,0.0000,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 8개, 부정·혼합 6개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
18,story,619820,Heroes of Hammerwatch II,스토리,6,2,4,0,4,4,1,0,0,0,2,7.37,4.32,0.1667,0.6667,0.6667,0.0000,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 6개, 부정·혼합 4개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
9,monetization,619820,Heroes of Hammerwatch II,과금,5,1,4,0,4,4,2,2,0,0,1,24.45,14.18,0.4000,0.8000,0.8000,0.0000,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 5개, 부정·혼합 4개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 2개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
14,positive_praise,619820,Heroes of Hammerwatch II,긍정 칭찬,440,440,0,0,0,29,16,0,5,0,0,33.00,17.53,0.0364,0.0000,0.0659,0.0000,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 440개, 부정·혼합 0개, Steam 비추천 맥락 29개, High urgency 후보 16개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

플레이타임 구간별 이슈 요약: (94, 7)

,playtime_stage,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
6,0-1h,gameplay_loop,게임플레이 루프,14,13,4,13
7,0-1h,graphics_audio,그래픽/사운드,12,10,8,11
1,0-1h,bug,버그,9,9,9,9
8,0-1h,multiplayer_network,멀티/네트워크,7,7,7,7
3,0-1h,control,조작감,5,5,5,5
16,0-1h,ui_ux,UI/UX,5,5,5,5
4,0-1h,crash,크래시,4,4,4,4
14,0-1h,save_progression,저장/진행,4,4,3,4
2,0-1h,content_volume,콘텐츠 분량,4,4,2,4
9,0-1h,other,기타,4,4,1,4
10,0-1h,performance,성능,2,2,2,2
5,0-1h,difficulty,난이도,3,2,1,2
13,0-1h,progression_grind,성장/반복 노가다,3,2,0,2
0,0-1h,balance,밸런스,1,1,1,1
12,0-1h,price_value,가격/가치,1,1,1,1
15,0-1h,story,스토리,1,0,1,1
11,0-1h,positive_praise,긍정 칭찬,6,0,0,0
24,1-5h,gameplay_loop,게임플레이 루프,59,56,17,54
33,1-5h,progression_grind,성장/반복 노가다,32,30,6,29
17,1-5h,balance,밸런스,16,15,9,14

최근성 구간별 이슈 요약: (49, 7)

,review_recency_group,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
21,last_30d,gameplay_loop,게임플레이 루프,9,7,2,7
19,last_30d,balance,밸런스,3,3,2,3
26,last_30d,progression_grind,성장/반복 노가다,3,3,1,3
22,last_30d,graphics_audio,그래픽/사운드,2,2,1,2
20,last_30d,difficulty,난이도,1,1,1,1
23,last_30d,multiplayer_network,멀티/네트워크,1,1,1,1
24,last_30d,performance,성능,1,1,1,1
27,last_30d,save_progression,저장/진행,1,1,1,1
28,last_30d,ui_ux,UI/UX,1,1,1,1
25,last_30d,positive_praise,긍정 칭찬,5,0,0,0
5,31-60d,gameplay_loop,게임플레이 루프,5,4,1,3
6,31-60d,multiplayer_network,멀티/네트워크,2,2,1,1
8,31-60d,progression_grind,성장/반복 노가다,2,2,1,1
1,31-60d,content_volume,콘텐츠 분량,2,2,0,1
2,31-60d,crash,크래시,1,1,1,1
3,31-60d,developer_communication,개발사 소통,1,1,1,1
9,31-60d,ui_ux,UI/UX,1,1,1,1
0,31-60d,balance,밸런스,1,1,0,1
4,31-60d,difficulty,난이도,2,1,0,0
7,31-60d,positive_praise,긍정 칭찬,3,0,0,0

패치·운영 전략 생성용 근거 테이블: (20, 29)

,llm_issue_category,issue_name_kor,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,priority_reason,patch_ops_note
17,save_progression,저장/진행,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,85,82,77,78,1,15,"영향 리뷰 85개, 부정·혼합 82개, Steam 비추천 맥락 77개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 78개(보조 참고), 절대 기준 후보 상,...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
1,bug,버그,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,82,79,61,61,0,17,"영향 리뷰 82개, 부정·혼합 79개, Steam 비추천 맥락 61개, 초반 플레이타임 부정·혼합 17개, High urgency 후보 61개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
13,performance,성능,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,33,30,22,28,1,8,"영향 리뷰 33개, 부정·혼합 30개, Steam 비추천 맥락 22개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 28개(보조 참고), 절대 기준 후보 상, ...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
4,crash,크래시,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,21,21,21,21,0,8,"영향 리뷰 21개, 부정·혼합 21개, Steam 비추천 맥락 21개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 21개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
7,gameplay_loop,게임플레이 루프,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,306,268,240,82,7,69,"영향 리뷰 306개, 부정·혼합 268개, Steam 비추천 맥락 240개, 최근 30일 부정·혼합 7개, 초반 플레이타임 부정·혼합 69개, High urgency 후보 82개(보조 참고), 절대 기준 후보...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
0,balance,밸런스,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,178,171,137,74,3,16,"영향 리뷰 178개, 부정·혼합 171개, Steam 비추천 맥락 137개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 16개, High urgency 후보 74개(보조 참고), 절대 기준 후보...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
16,progression_grind,성장/반복 노가다,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,179,152,136,46,3,32,"영향 리뷰 179개, 부정·혼합 152개, Steam 비추천 맥락 136개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 32개, High urgency 후보 46개(보조 참고), 절대 기준 후보...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
19,ui_ux,UI/UX,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,69,66,46,31,1,20,"영향 리뷰 69개, 부정·혼합 66개, Steam 비추천 맥락 46개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 20개, High urgency 후보 31개(보조 참고), 절대 기준 후보 상,...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
6,difficulty,난이도,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,58,44,36,19,1,14,"영향 리뷰 58개, 부정·혼합 44개, Steam 비추천 맥락 36개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 19개(보조 참고), 절대 기준 후보 상,...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
3,control,조작감,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,16,16,14,13,0,8,"영향 리뷰 16개, 부정·혼합 16개, Steam 비추천 맥락 14개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 13개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
5,developer_communication,개발사 소통,운영 커뮤니케이션 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,26,23,23,21,0,2,"영향 리뷰 26개, 부정·혼합 23개, Steam 비추천 맥락 23개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 21개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
2,content_volume,콘텐츠 분량,장기 검토,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,166,137,112,33,0,16,"영향 리뷰 166개, 부정·혼합 137개, Steam 비추천 맥락 112개, 초반 플레이타임 부정·혼합 16개, High urgency 후보 33개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 ...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
8,graphics_audio,그래픽/사운드,장기 검토,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,72,53,56,24,2,21,"영향 리뷰 72개, 부정·혼합 53개, Steam 비추천 맥락 56개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 24개(보조 참고), 절대 기준 후보 상,...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
15,price_value,가격/가치,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,30,21,21,8,0,3,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 21개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
10,multiplayer_network,멀티/네트워크,검토 필요,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,81,65,55,52,1,17,"영향 리뷰 81개, 부정·혼합 65개, Steam 비추천 맥락 55개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 17개, High urgency 후보 52개(보조 참고), 절대 기준 후보 상,...",세부 리뷰 확인 후 대응 방향을 검토한다.
12,other,기타,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,42,37,36,13,0,9,"영향 리뷰 42개, 부정·혼합 37개, Steam 비추천 맥락 36개, 초반 플레이타임 부정·혼합 9개, High urgency 후보 13개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 ...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
11,optimization,최적화,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,8,6,5,6,0,1,"영향 리뷰 8개, 부정·혼합 6개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
18,story,스토리,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,6,4,4,1,0,2,"영향 리뷰 6개, 부정·혼합 4개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
9,monetization,과금,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,5,4,4,2,0,1,"영향 리뷰 5개, 부정·혼합 4개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 2개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
14,positive_praise,긍정 칭찬,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,440,0,29,16,0,0,"영향 리뷰 440개, 부정·혼합 0개, Steam 비추천 맥락 29개, High urgency 후보 16개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

Tableau/보고서 원천 데이터: (1903, 40)

,appid,game_name,recommendationid,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,llm_sentiment,steam_llm_sentiment_relation,playtime_at_review_hours,playtime_stage,early_playtime_flag,votes_up,weighted_vote_score,llm_urgency_candidate,high_urgency_flag,llm_issue_category,issue_name_kor,llm_issue_sentiment,issue_positive_flag,issue_negative_or_mixed_flag,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,patch_ops_note,llm_issue_evidence
0,619820,Heroes of Hammerwatch II,189880229,2025-03-10 15:54:38,2025-01-14,55,D31-D90,older_90d,negative,negative,exact_match,2.416667,1-5h,True,3,0.510774,high,True,save_progression,저장/진행,negative,False,True,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 85개, 부정·혼합 82개, Steam 비추천 맥락 77개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 78개(보조 참고), 절대 기준 후보 상,...",85,82,77,78,0.9176,0.9647,0.9059,1,15,"저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다.",last 2 days I got my saved wiped out twice
1,619820,Heroes of Hammerwatch II,213786980,2025-12-21 03:28:01,2025-01-14,341,D181+,older_90d,positive,positive,exact_match,18.450000,5-20h,False,12,0.655379,low,False,progression_grind,성장/반복 노가다,neutral,False,False,단기 개선,상,중,"절대 기준상 '상' 후보였으나, 최종 '상' 개수 제한 기준에 따라 '중'으로 조정",절대 기준 상 후보였으나 최종 상위 이슈 제한 기준에 따라 중으로 조정,"영향 리뷰 179개, 부정·혼합 152개, Steam 비추천 맥락 136개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 32개, High urgency 후보 46개(보조 참고), 절대 기준 후보...",179,152,136,46,0.2570,0.8492,0.7598,3,32,반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.,This game can appear to be very grindy at first
2,619820,Heroes of Hammerwatch II,213786980,2025-12-21 03:28:01,2025-01-14,341,D181+,older_90d,positive,positive,exact_match,18.450000,5-20h,False,12,0.655379,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 440개, 부정·혼합 0개, Steam 비추천 맥락 29개, High urgency 후보 16개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",440,0,29,16,0.0364,0.0000,0.0659,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",I find myself keep coming back and having a great time
3,619820,Heroes of Hammerwatch II,215844634,2026-01-12 19:36:41,2025-01-14,363,D181+,older_90d,positive,mixed,partial_match,30.783333,20-50h,False,0,0.500000,high,True,save_progression,저장/진행,negative,False,True,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 85개, 부정·혼합 82개, Steam 비추천 맥락 77개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 78개(보조 참고), 절대 기준 후보 상,...",85,82,77,78,0.9176,0.9647,0.9059,1,15,"저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다.",switched to linux and I lost all my data in the game
4,619820,Heroes of Hammerwatch II,215844634,2026-01-12 19:36:41,2025-01-14,363,D181+,older_90d,positive,mixed,partial_match,30.783333,20-50h,False,0,0.500000,high,True,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 440개, 부정·혼합 0개, Steam 비추천 맥락 29개, High urgency 후보 16개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",440,0,29,16,0.0364,0.0000,0.0659,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",I played the game for 30 hours and it was really fun!

저장 완료
저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postlaunch_preprocess_data

,파일명,행 수,역할
0,postlaunch_review_base.csv,1000,리뷰 1개 단위 전처리 결과
1,postlaunch_issue_summary.csv,20,이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약
2,postlaunch_patch_ops_evidence_base.csv,20,03-2 LLM 패치·운영 전략 생성용 근거 데이터
3,tableau_postlaunch_patch_ops_source.csv,1903,Tableau/보고서용 원천 데이터

검증 통과
리뷰 수: 1000
리뷰-이슈 수: 1903
이슈 종류 수: 20
절대 기준 후보 분포:

  priority_candidate  issue_count
0                  상           12
1                  중            4
2                  하            4

최종 우선 검토 수준 분포:

  rule_priority_hint  issue_count
0                  중           10
1                  상            6
2                  하            4

최종 '상' 제한 기준: 최대 6개
High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.

==========================================================================================
03-1번 출시 후 전처리 실행: necrosmith_2
==========================================================================================
리뷰 단위 LLM 결과: (324, 20)
이슈 태그 단위 결과: (630, 15)

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,steam_label_text,playtime_at_review_hours,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_primary_issue,llm_issue_tags,llm_urgency_candidate,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,161594776,2277320,Necrosmith 2,2024-03-27 17:08:08,2024-03-27,0,D0-D30,positive,0.333333,7,0.350343,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""extraordinary, captivating allure, immersive ...",low,전작의 매력을 잘 계승한 매우 훌륭하고 몰입감 있는 게임이라고 평가함.,"현재의 게임 플레이 경험과 몰입감을 유지하고, 전작 팬들이 기대하는 핵심 재미 요소를 지속적으로 강화할 것.",exact_match
1,success,161596192,2277320,Necrosmith 2,2024-03-27 17:32:24,2024-03-27,0,D0-D30,positive,0.550000,79,0.812617,mixed,3,ui_ux,"[{""category"": ""gameplay_loop"", ""sentiment"": ""negative"", ""evidence"": ""minions AI seems much worse than it used to be""...",medium,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match
2,success,161597154,2277320,Necrosmith 2,2024-03-27 17:48:54,2024-03-27,0,D0-D30,positive,1.000000,8,0.497289,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""beautiful and high-quality roguelike, funny, ...",low,"고품질의 로그라이크 게임이며, 유머러스한 요소와 음악이 매우 만족스럽다고 평가함.","현재의 아트 스타일, 유머 요소, 음악적 분위기를 유지하며 플레이어의 긍정적인 경험을 지속할 것.",exact_match
3,success,161601521,2277320,Necrosmith 2,2024-03-27 19:02:15,2024-03-27,0,D0-D30,positive,1.833333,8,0.501608,positive,4,ui_ux,"[{""category"": ""gameplay_loop"", ""sentiment"": ""positive"", ""evidence"": ""tower defense + roguelite auto-battler survivor...",medium,"다양한 장르가 혼합된 게임 플레이는 만족스러우나, 신체 부위 필터링 및 세트 보너스 시스템의 가시성이 부족하여 개선이 필요함.",신체 부위 필터링 기능 추가 및 세트 보너스 효과를 직관적으로 확인할 수 있는 UI/UX 개선 검토.,exact_match
4,success,161601777,2277320,Necrosmith 2,2024-03-27 19:06:50,2024-03-27,0,D0-D30,positive,1.983333,6,0.523810,mixed,3,control,"[{""category"": ""control"", ""sentiment"": ""negative"", ""evidence"": ""units only do one thing at a time which is absolutely...",high,전작 대비 소환수 조작 방식이 퇴보함. 유닛이 한 번에 하나의 작업만 수행하는 현재 시스템 대신 다중 작업 허용 또는 이전 시스템 복구를 요청함.,소환수 조작 시스템에 대한 사용자 피드백 재검토 및 다중 작업 수행 가능 여부 또는 이전 조작 방식 도입 고려.,partial_match

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence
0,161594776,2277320,Necrosmith 2,positive,positive,positive_praise,low,D0-D30,0.333333,7,0.350343,positive_praise,긍정 칭찬,positive,"extraordinary, captivating allure, immersive world"
1,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,gameplay_loop,게임플레이 루프,negative,minions AI seems much worse than it used to be
2,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,ui_ux,UI/UX,negative,parts sorting in inventory is confusing and needs sorting options
3,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,bug,버그,negative,order of parts in sections is inconsistent/not sorted as expected
4,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,positive_praise,긍정 칭찬,positive,"improvements over the first game, new spells, titan creation is satisfying"

필수 컬럼 확인 완료
리뷰 단위 전처리 결과: (324, 28)
최신 리뷰일: 2026-04-22 23:28:08

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,steam_positive_flag,steam_negative_flag,playtime_at_review_hours,playtime_stage,early_playtime_flag,recent_30d_flag,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_negative_or_mixed_flag,llm_positive_flag,llm_primary_issue,llm_urgency_candidate,high_urgency_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,161594776,2277320,Necrosmith 2,2024-03-27 17:08:08,2024-03-27,0,D0-D30,older_90d,positive,True,False,0.333333,0-1h,True,False,7,0.350343,positive,5,False,True,positive_praise,low,False,전작의 매력을 잘 계승한 매우 훌륭하고 몰입감 있는 게임이라고 평가함.,"현재의 게임 플레이 경험과 몰입감을 유지하고, 전작 팬들이 기대하는 핵심 재미 요소를 지속적으로 강화할 것.",exact_match
1,success,161596192,2277320,Necrosmith 2,2024-03-27 17:32:24,2024-03-27,0,D0-D30,older_90d,positive,True,False,0.550000,0-1h,True,False,79,0.812617,mixed,3,True,False,ui_ux,medium,False,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match
2,success,161597154,2277320,Necrosmith 2,2024-03-27 17:48:54,2024-03-27,0,D0-D30,older_90d,positive,True,False,1.000000,1-5h,True,False,8,0.497289,positive,5,False,True,positive_praise,low,False,"고품질의 로그라이크 게임이며, 유머러스한 요소와 음악이 매우 만족스럽다고 평가함.","현재의 아트 스타일, 유머 요소, 음악적 분위기를 유지하며 플레이어의 긍정적인 경험을 지속할 것.",exact_match
3,success,161601521,2277320,Necrosmith 2,2024-03-27 19:02:15,2024-03-27,0,D0-D30,older_90d,positive,True,False,1.833333,1-5h,True,False,8,0.501608,positive,4,False,True,ui_ux,medium,False,"다양한 장르가 혼합된 게임 플레이는 만족스러우나, 신체 부위 필터링 및 세트 보너스 시스템의 가시성이 부족하여 개선이 필요함.",신체 부위 필터링 기능 추가 및 세트 보너스 효과를 직관적으로 확인할 수 있는 UI/UX 개선 검토.,exact_match
4,success,161601777,2277320,Necrosmith 2,2024-03-27 19:06:50,2024-03-27,0,D0-D30,older_90d,positive,True,False,1.983333,1-5h,True,False,6,0.523810,mixed,3,True,False,control,high,True,전작 대비 소환수 조작 방식이 퇴보함. 유닛이 한 번에 하나의 작업만 수행하는 현재 시스템 대신 다중 작업 허용 또는 이전 시스템 복구를 요청함.,소환수 조작 시스템에 대한 사용자 피드백 재검토 및 다중 작업 수행 가능 여부 또는 이전 조작 방식 도입 고려.,partial_match

이슈 태그 원본 행 수: 630
리뷰-이슈 중복 제거 후 행 수: 615

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence,review_datetime,release_date,days_from_release,review_recency_group,playtime_stage,steam_negative_flag,steam_positive_flag,llm_negative_or_mixed_flag,llm_positive_flag,high_urgency_flag,early_playtime_flag,recent_30d_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation,issue_positive_flag,issue_negative_or_mixed_flag,issue_negative_flag,issue_mixed_flag
0,161594776,2277320,Necrosmith 2,positive,positive,positive_praise,low,D0-D30,0.333333,7,0.350343,positive_praise,긍정 칭찬,positive,"extraordinary, captivating allure, immersive world",2024-03-27 17:08:08,2024-03-27,0,older_90d,0-1h,False,True,False,True,False,True,False,전작의 매력을 잘 계승한 매우 훌륭하고 몰입감 있는 게임이라고 평가함.,"현재의 게임 플레이 경험과 몰입감을 유지하고, 전작 팬들이 기대하는 핵심 재미 요소를 지속적으로 강화할 것.",exact_match,True,False,False,False
1,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,gameplay_loop,게임플레이 루프,negative,minions AI seems much worse than it used to be,2024-03-27 17:32:24,2024-03-27,0,older_90d,0-1h,False,True,True,False,False,True,False,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match,False,True,True,False
2,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,ui_ux,UI/UX,negative,parts sorting in inventory is confusing and needs sorting options,2024-03-27 17:32:24,2024-03-27,0,older_90d,0-1h,False,True,True,False,False,True,False,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match,False,True,True,False
3,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,bug,버그,negative,order of parts in sections is inconsistent/not sorted as expected,2024-03-27 17:32:24,2024-03-27,0,older_90d,0-1h,False,True,True,False,False,True,False,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match,False,True,True,False
4,161596192,2277320,Necrosmith 2,positive,mixed,ui_ux,medium,D0-D30,0.550000,79,0.812617,positive_praise,긍정 칭찬,positive,"improvements over the first game, new spells, titan creation is satisfying",2024-03-27 17:32:24,2024-03-27,0,older_90d,0-1h,False,True,True,False,False,True,False,전작 대비 개선점은 있으나 미니언 AI 저하와 파츠 정렬 UI의 불편함이 있음. 정렬 기능 추가 및 자동 판매 기능 제안.,"미니언 AI 로직 검토 및 무기 조합별 행동 패턴 확인. 인벤토리 파츠 정렬 기능(마나, 속도, HP 등) 추가 및 자동 판매 편의 기능 검토.",partial_match,True,False,False,False

게임 단위 요약: (1, 16)

,appid,game_name,review_count,issue_tag_count,steam_positive_review_count,steam_negative_review_count,steam_positive_rate,llm_positive_review_count,llm_negative_mixed_review_count,llm_negative_mixed_rate,high_urgency_review_count,high_urgency_rate,first_review_datetime,last_review_datetime,mean_playtime_at_review_hours,median_playtime_at_review_hours
0,2277320,Necrosmith 2,324,615,236,88,0.7284,174,150,0.463,60,0.1852,2024-03-27 17:08:08,2026-04-22 23:28:08,14.95,9.37

이슈 단위 요약: (21, 28)
최종 우선 검토 수준 분포

  rule_priority_hint  issue_count
0                  하           11
1                  중            7
2                  상            3

절대 기준 후보 분포

  priority_candidate  issue_count
0                  하           11
1                  중            7
2                  상            3

,llm_issue_category,appid,game_name,issue_name_kor,affected_review_count,positive_review_count,negative_review_count,mixed_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_negative_mixed_review_count,recent_30d_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,avg_playtime_at_review_hours,median_playtime_at_review_hours,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_rate,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,patch_ops_note
13,performance,2277320,Necrosmith 2,성능,18,1,17,0,17,13,16,16,0,0,3,15.81,12.27,0.8889,0.9444,0.7222,0.0,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 18개, 부정·혼합 17개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 16개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
7,gameplay_loop,2277320,Necrosmith 2,게임플레이 루프,77,8,60,2,62,36,17,15,3,3,25,14.94,8.02,0.2208,0.8052,0.4675,1.0,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 77개, 부정·혼합 62개, Steam 비추천 맥락 36개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 25개, High urgency 후보 17개(보조 참고), 절대 기준 후보 상,...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
2,content_volume,2277320,Necrosmith 2,콘텐츠 분량,61,7,39,1,40,15,5,4,3,3,3,21.12,16.87,0.0820,0.6557,0.2459,1.0,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 61개, 부정·혼합 40개, Steam 비추천 맥락 15개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 5개(보조 참고), 절대 기준 후보 상, 규...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
17,save_progression,2277320,Necrosmith 2,저장/진행,14,0,14,0,14,8,11,11,0,0,3,25.37,8.32,0.7857,1.0000,0.5714,0.0,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 14개, 부정·혼합 14개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 11개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
1,bug,2277320,Necrosmith 2,버그,15,2,13,0,13,6,10,10,0,0,5,11.84,11.67,0.6667,0.8667,0.4000,0.0,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 15개, 부정·혼합 13개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
0,balance,2277320,Necrosmith 2,밸런스,36,1,32,0,32,16,10,10,2,2,4,17.52,16.15,0.2778,0.8889,0.4444,1.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 36개, 부정·혼합 32개, Steam 비추천 맥락 16개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, ...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
20,ui_ux,2277320,Necrosmith 2,UI/UX,39,0,32,0,32,15,14,13,1,1,14,14.63,7.68,0.3590,0.8205,0.3846,1.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 39개, 부정·혼합 32개, Steam 비추천 맥락 15개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 14개(보조 참고), 절대 기준 후보 중,...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
16,progression_grind,2277320,Necrosmith 2,성장/반복 노가다,31,0,27,1,28,17,15,15,2,2,7,16.13,15.23,0.4839,0.9032,0.5484,1.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 31개, 부정·혼합 28개, Steam 비추천 맥락 17개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 7개, High urgency 후보 15개(보조 참고), 절대 기준 후보 중, ...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
6,difficulty,2277320,Necrosmith 2,난이도,31,1,24,0,24,12,10,10,0,0,5,15.27,8.02,0.3226,0.7742,0.3871,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 31개, 부정·혼합 24개, Steam 비추천 맥락 12개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
3,control,2277320,Necrosmith 2,조작감,25,1,19,0,19,8,8,8,0,0,7,13.46,7.68,0.3200,0.7600,0.3200,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 25개, 부정·혼합 19개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 7개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
4,crash,2277320,Necrosmith 2,크래시,7,0,7,0,7,7,7,7,0,0,5,5.82,0.15,1.0000,1.0000,1.0000,0.0,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 7개, 부정·혼합 7개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 7개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
5,developer_communication,2277320,Necrosmith 2,개발사 소통,9,2,7,0,7,6,5,5,0,0,3,17.12,14.20,0.5556,0.7778,0.6667,0.0,운영 커뮤니케이션 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 9개, 부정·혼합 7개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
8,graphics_audio,2277320,Necrosmith 2,그래픽/사운드,7,1,5,0,5,5,0,0,0,0,4,17.90,2.48,0.0000,0.7143,0.7143,0.0,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 7개, 부정·혼합 5개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 4개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
18,story,2277320,Necrosmith 2,스토리,10,2,5,0,5,3,0,0,1,1,1,23.96,18.43,0.0000,0.5000,0.3000,1.0,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 10개, 부정·혼합 5개, Steam 비추천 맥락 3개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
12,other,2277320,Necrosmith 2,기타,7,0,2,0,2,1,0,0,0,0,0,39.66,22.95,0.0000,0.2857,0.1429,0.0,검토 필요,하,하,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,"영향 리뷰 7개, 부정·혼합 2개, Steam 비추천 맥락 1개, 절대 기준 후보 하, 규칙 근거: 기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
11,optimization,2277320,Necrosmith 2,최적화,2,0,2,0,2,0,1,1,0,0,0,17.54,17.54,0.5000,1.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 0개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
9,monetization,2277320,Necrosmith 2,과금,1,0,1,0,1,1,0,0,0,0,0,6.10,6.10,0.0000,1.0000,1.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
19,translation_localization,2277320,Necrosmith 2,번역/현지화,1,0,1,0,1,0,0,0,0,0,0,6.60,6.60,0.0000,1.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",번역/현지화 불만이 실제 이해도와 진행 경험에 영향을 주는지 검토한다.
10,multiplayer_network,2277320,Necrosmith 2,멀티/네트워크,1,0,0,0,0,0,0,0,0,0,0,24.07,24.07,0.0000,0.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 0개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
15,price_value,2277320,Necrosmith 2,가격/가치,17,13,3,0,3,2,0,0,1,1,1,13.60,8.10,0.0000,0.1765,0.1176,1.0,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 17개, 부정·혼합 3개, Steam 비추천 맥락 2개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 ...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.

플레이타임 구간별 이슈 요약: (79, 7)

,playtime_stage,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
6,0-1h,gameplay_loop,게임플레이 루프,9,8,1,7
3,0-1h,crash,크래시,5,5,5,5
11,0-1h,ui_ux,UI/UX,6,5,2,4
4,0-1h,developer_communication,개발사 소통,2,2,2,2
8,0-1h,performance,성능,2,2,2,2
0,0-1h,bug,버그,2,2,1,0
5,0-1h,difficulty,난이도,2,1,1,1
10,0-1h,progression_grind,성장/반복 노가다,1,1,1,1
1,0-1h,content_volume,콘텐츠 분량,1,1,0,1
2,0-1h,control,조작감,1,1,0,1
7,0-1h,graphics_audio,그래픽/사운드,1,1,0,1
9,0-1h,positive_praise,긍정 칭찬,11,0,0,0
18,1-5h,gameplay_loop,게임플레이 루프,21,17,7,13
26,1-5h,ui_ux,UI/UX,10,9,4,4
23,1-5h,progression_grind,성장/반복 노가다,6,6,4,4
15,1-5h,control,조작감,8,6,3,2
12,1-5h,balance,밸런스,4,4,3,3
17,1-5h,difficulty,난이도,5,4,2,3
24,1-5h,save_progression,저장/진행,3,3,3,3
13,1-5h,bug,버그,3,3,2,2

최근성 구간별 이슈 요약: (36, 7)

,review_recency_group,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
8,last_30d,content_volume,콘텐츠 분량,3,3,1,1
9,last_30d,gameplay_loop,게임플레이 루프,3,3,1,0
12,last_30d,progression_grind,성장/반복 노가다,2,2,2,1
7,last_30d,balance,밸런스,2,2,1,1
14,last_30d,ui_ux,UI/UX,1,1,1,0
11,last_30d,price_value,가격/가치,1,1,0,0
13,last_30d,story,스토리,1,1,0,0
10,last_30d,positive_praise,긍정 칭찬,3,0,0,0
2,31-60d,gameplay_loop,게임플레이 루프,3,3,1,2
0,31-60d,bug,버그,1,1,1,1
5,31-60d,save_progression,저장/진행,1,1,1,1
1,31-60d,content_volume,콘텐츠 분량,1,1,0,0
6,31-60d,ui_ux,UI/UX,1,1,0,0
3,31-60d,positive_praise,긍정 칭찬,5,0,0,0
4,31-60d,progression_grind,성장/반복 노가다,1,0,0,0
22,older_90d,gameplay_loop,게임플레이 루프,71,56,15,34
17,older_90d,content_volume,콘텐츠 분량,57,36,4,14
35,older_90d,ui_ux,UI/UX,37,30,13,15
15,older_90d,balance,밸런스,34,30,9,15
31,older_90d,progression_grind,성장/반복 노가다,28,26,13,16

패치·운영 전략 생성용 근거 테이블: (21, 29)

,llm_issue_category,issue_name_kor,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,priority_reason,patch_ops_note
13,performance,성능,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,18,17,13,16,0,3,"영향 리뷰 18개, 부정·혼합 17개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 16개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
7,gameplay_loop,게임플레이 루프,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,77,62,36,17,3,25,"영향 리뷰 77개, 부정·혼합 62개, Steam 비추천 맥락 36개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 25개, High urgency 후보 17개(보조 참고), 절대 기준 후보 상,...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
2,content_volume,콘텐츠 분량,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,61,40,15,5,3,3,"영향 리뷰 61개, 부정·혼합 40개, Steam 비추천 맥락 15개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 5개(보조 참고), 절대 기준 후보 상, 규...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
17,save_progression,저장/진행,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,14,14,8,11,0,3,"영향 리뷰 14개, 부정·혼합 14개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 11개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
1,bug,버그,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,15,13,6,10,0,5,"영향 리뷰 15개, 부정·혼합 13개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
0,balance,밸런스,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,36,32,16,10,2,4,"영향 리뷰 36개, 부정·혼합 32개, Steam 비추천 맥락 16개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, ...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
20,ui_ux,UI/UX,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,39,32,15,14,1,14,"영향 리뷰 39개, 부정·혼합 32개, Steam 비추천 맥락 15개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 14개(보조 참고), 절대 기준 후보 중,...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
16,progression_grind,성장/반복 노가다,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,31,28,17,15,2,7,"영향 리뷰 31개, 부정·혼합 28개, Steam 비추천 맥락 17개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 7개, High urgency 후보 15개(보조 참고), 절대 기준 후보 중, ...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
6,difficulty,난이도,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,31,24,12,10,0,5,"영향 리뷰 31개, 부정·혼합 24개, Steam 비추천 맥락 12개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 ...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
3,control,조작감,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,25,19,8,8,0,7,"영향 리뷰 25개, 부정·혼합 19개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 7개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
4,crash,크래시,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,7,7,7,7,0,5,"영향 리뷰 7개, 부정·혼합 7개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 7개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
5,developer_communication,개발사 소통,운영 커뮤니케이션 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,9,7,6,5,0,3,"영향 리뷰 9개, 부정·혼합 7개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
8,graphics_audio,그래픽/사운드,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,7,5,5,0,0,4,"영향 리뷰 7개, 부정·혼합 5개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 4개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
18,story,스토리,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,10,5,3,0,1,1,"영향 리뷰 10개, 부정·혼합 5개, Steam 비추천 맥락 3개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
12,other,기타,검토 필요,하,하,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,7,2,1,0,0,0,"영향 리뷰 7개, 부정·혼합 2개, Steam 비추천 맥락 1개, 절대 기준 후보 하, 규칙 근거: 기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
11,optimization,최적화,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,2,2,0,1,0,0,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 0개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
9,monetization,과금,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,1,0,0,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
19,translation_localization,번역/현지화,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,0,0,0,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",번역/현지화 불만이 실제 이해도와 진행 경험에 영향을 주는지 검토한다.
10,multiplayer_network,멀티/네트워크,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,0,0,0,0,0,"영향 리뷰 1개, 부정·혼합 0개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
15,price_value,가격/가치,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,17,3,2,0,1,1,"영향 리뷰 17개, 부정·혼합 3개, Steam 비추천 맥락 2개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 ...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.

Tableau/보고서 원천 데이터: (615, 40)

,appid,game_name,recommendationid,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,llm_sentiment,steam_llm_sentiment_relation,playtime_at_review_hours,playtime_stage,early_playtime_flag,votes_up,weighted_vote_score,llm_urgency_candidate,high_urgency_flag,llm_issue_category,issue_name_kor,llm_issue_sentiment,issue_positive_flag,issue_negative_or_mixed_flag,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,patch_ops_note,llm_issue_evidence
0,2277320,Necrosmith 2,161594776,2024-03-27 17:08:08,2024-03-27,0,D0-D30,older_90d,positive,positive,exact_match,0.333333,0-1h,True,7,0.350343,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 206개, 부정·혼합 0개, Steam 비추천 맥락 6개, High urgency 후보 8개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",206,0,6,8,0.0388,0.0000,0.0291,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","extraordinary, captivating allure, immersive world"
1,2277320,Necrosmith 2,161596192,2024-03-27 17:32:24,2024-03-27,0,D0-D30,older_90d,positive,mixed,partial_match,0.550000,0-1h,True,79,0.812617,medium,False,gameplay_loop,게임플레이 루프,negative,False,True,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 77개, 부정·혼합 62개, Steam 비추천 맥락 36개, 최근 30일 부정·혼합 3개, 초반 플레이타임 부정·혼합 25개, High urgency 후보 17개(보조 참고), 절대 기준 후보 상,...",77,62,36,17,0.2208,0.8052,0.4675,3,25,"반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다.",minions AI seems much worse than it used to be
2,2277320,Necrosmith 2,161596192,2024-03-27 17:32:24,2024-03-27,0,D0-D30,older_90d,positive,mixed,partial_match,0.550000,0-1h,True,79,0.812617,medium,False,ui_ux,UI/UX,negative,False,True,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 39개, 부정·혼합 32개, Steam 비추천 맥락 15개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 14개(보조 참고), 절대 기준 후보 중,...",39,32,15,14,0.3590,0.8205,0.3846,1,14,"메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다.",parts sorting in inventory is confusing and needs sorting options
3,2277320,Necrosmith 2,161596192,2024-03-27 17:32:24,2024-03-27,0,D0-D30,older_90d,positive,mixed,partial_match,0.550000,0-1h,True,79,0.812617,medium,False,bug,버그,negative,False,True,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 15개, 부정·혼합 13개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 10개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...",15,13,6,10,0.6667,0.8667,0.4000,0,5,"반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다.",order of parts in sections is inconsistent/not sorted as expected
4,2277320,Necrosmith 2,161596192,2024-03-27 17:32:24,2024-03-27,0,D0-D30,older_90d,positive,mixed,partial_match,0.550000,0-1h,True,79,0.812617,medium,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 206개, 부정·혼합 0개, Steam 비추천 맥락 6개, High urgency 후보 8개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",206,0,6,8,0.0388,0.0000,0.0291,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","improvements over the first game, new spells, titan creation is satisfying"

저장 완료
저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_preprocess_data

,파일명,행 수,역할
0,postlaunch_review_base.csv,324,리뷰 1개 단위 전처리 결과
1,postlaunch_issue_summary.csv,21,이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약
2,postlaunch_patch_ops_evidence_base.csv,21,03-2 LLM 패치·운영 전략 생성용 근거 데이터
3,tableau_postlaunch_patch_ops_source.csv,615,Tableau/보고서용 원천 데이터

검증 통과
리뷰 수: 324
리뷰-이슈 수: 615
이슈 종류 수: 21
절대 기준 후보 분포:

  priority_candidate  issue_count
0                  하           11
1                  중            7
2                  상            3

최종 우선 검토 수준 분포:

  rule_priority_hint  issue_count
0                  하           11
1                  중            7
2                  상            3

최종 '상' 제한 기준: 최대 6개
High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.

==========================================================================================
03-1번 출시 후 전처리 실행: children_of_the_sun
==========================================================================================
리뷰 단위 LLM 결과: (883, 20)
이슈 태그 단위 결과: (1578, 15)

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,steam_label_text,playtime_at_review_hours,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_primary_issue,llm_issue_tags,llm_urgency_candidate,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,162551168,1309950,Children of the Sun,2024-04-09 16:16:12,2024-04-09,0,D0-D30,positive,0.433333,7,0.558690,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""Art Style, Music, Atmosphere, 21:9 support ar...",low,"아트 스타일, 음악, 분위기가 훌륭하며 21:9 울트라와이드 해상도를 지원하는 점에 만족함.","현재의 독특한 아트 스타일과 분위기를 유지하고, 향후 업데이트에서도 울트라와이드 해상도 지원을 지속적으로 관리할 것.",exact_match
1,success,162551849,1309950,Children of the Sun,2024-04-09 16:27:50,2024-04-09,0,D0-D30,positive,0.533333,3,0.476679,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""Great game.""}]",low,게임이 매우 독특하고 재미있다는 긍정적인 평가.,현재의 독특한 게임 컨셉과 분위기를 유지하며 플레이어들에게 긍정적인 경험을 지속적으로 제공할 것.,exact_match
2,success,162552645,1309950,Children of the Sun,2024-04-09 16:41:02,2024-04-09,0,D0-D30,positive,1.200000,28,0.735037,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""Short but sweet puzzle shooter, fun gameplay ...",low,퍼즐 슈팅 게임으로서의 재미와 리플레이 가치를 높게 평가함.,"현재의 퍼즐 슈팅 메커니즘과 리플레이 가치를 강화하고, 리더보드 시스템이 원활하게 작동하도록 유지할 것.",exact_match
3,success,162552871,1309950,Children of the Sun,2024-04-09 16:44:51,2024-04-09,0,D0-D30,positive,0.416667,77,0.756212,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""Amazing art style, simple but satisfying game...",low,"Killer7와 Sniper Elite를 섞은 듯한 독특한 게임성, 훌륭한 아트 스타일과 만족스러운 게임 플레이를 갖춘 가성비 좋은 게임.",현재의 독특한 아트 스타일과 만족스러운 게임 플레이 루프를 유지 및 강화할 것.,exact_match
4,success,162556466,1309950,Children of the Sun,2024-04-09 17:41:22,2024-04-09,0,D0-D30,positive,1.766667,4,0.583224,positive,4,control,"[{""category"": ""control"", ""sentiment"": ""negative"", ""evidence"": ""controls to some extent. missed the \""SINGLE RIGHT CL...",medium,전반적으로 좋은 게임이나 조작법에 다소 아쉬움이 있음. 튜토리얼 안내가 명확하지 않다고 느낄 수 있음.,튜토리얼의 핵심 조작 안내(예: 우클릭)가 더 직관적으로 보이도록 UI/UX 가독성 개선 검토.,exact_match

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence
0,162551168,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.433333,7,0.558690,positive_praise,긍정 칭찬,positive,"Art Style, Music, Atmosphere, 21:9 support are great."
1,162551849,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.533333,3,0.476679,positive_praise,긍정 칭찬,positive,Great game.
2,162552645,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,1.200000,28,0.735037,positive_praise,긍정 칭찬,positive,"Short but sweet puzzle shooter, fun gameplay loop."
3,162552871,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.416667,77,0.756212,positive_praise,긍정 칭찬,positive,"Amazing art style, simple but satisfying gameplay. Fairly priced."
4,162556466,1309950,Children of the Sun,positive,positive,control,medium,D0-D30,1.766667,4,0.583224,control,조작감,negative,"controls to some extent. missed the ""SINGLE RIGHT CLICK"" prompted in RED"

필수 컬럼 확인 완료
리뷰 단위 전처리 결과: (883, 28)
최신 리뷰일: 2026-04-28 06:21:38

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,steam_positive_flag,steam_negative_flag,playtime_at_review_hours,playtime_stage,early_playtime_flag,recent_30d_flag,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_negative_or_mixed_flag,llm_positive_flag,llm_primary_issue,llm_urgency_candidate,high_urgency_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,162551168,1309950,Children of the Sun,2024-04-09 16:16:12,2024-04-09,0,D0-D30,older_90d,positive,True,False,0.433333,0-1h,True,False,7,0.558690,positive,5,False,True,positive_praise,low,False,"아트 스타일, 음악, 분위기가 훌륭하며 21:9 울트라와이드 해상도를 지원하는 점에 만족함.","현재의 독특한 아트 스타일과 분위기를 유지하고, 향후 업데이트에서도 울트라와이드 해상도 지원을 지속적으로 관리할 것.",exact_match
1,success,162551849,1309950,Children of the Sun,2024-04-09 16:27:50,2024-04-09,0,D0-D30,older_90d,positive,True,False,0.533333,0-1h,True,False,3,0.476679,positive,5,False,True,positive_praise,low,False,게임이 매우 독특하고 재미있다는 긍정적인 평가.,현재의 독특한 게임 컨셉과 분위기를 유지하며 플레이어들에게 긍정적인 경험을 지속적으로 제공할 것.,exact_match
2,success,162552645,1309950,Children of the Sun,2024-04-09 16:41:02,2024-04-09,0,D0-D30,older_90d,positive,True,False,1.200000,1-5h,True,False,28,0.735037,positive,5,False,True,positive_praise,low,False,퍼즐 슈팅 게임으로서의 재미와 리플레이 가치를 높게 평가함.,"현재의 퍼즐 슈팅 메커니즘과 리플레이 가치를 강화하고, 리더보드 시스템이 원활하게 작동하도록 유지할 것.",exact_match
3,success,162552871,1309950,Children of the Sun,2024-04-09 16:44:51,2024-04-09,0,D0-D30,older_90d,positive,True,False,0.416667,0-1h,True,False,77,0.756212,positive,5,False,True,positive_praise,low,False,"Killer7와 Sniper Elite를 섞은 듯한 독특한 게임성, 훌륭한 아트 스타일과 만족스러운 게임 플레이를 갖춘 가성비 좋은 게임.",현재의 독특한 아트 스타일과 만족스러운 게임 플레이 루프를 유지 및 강화할 것.,exact_match
4,success,162556466,1309950,Children of the Sun,2024-04-09 17:41:22,2024-04-09,0,D0-D30,older_90d,positive,True,False,1.766667,1-5h,True,False,4,0.583224,positive,4,False,True,control,medium,False,전반적으로 좋은 게임이나 조작법에 다소 아쉬움이 있음. 튜토리얼 안내가 명확하지 않다고 느낄 수 있음.,튜토리얼의 핵심 조작 안내(예: 우클릭)가 더 직관적으로 보이도록 UI/UX 가독성 개선 검토.,exact_match

이슈 태그 원본 행 수: 1578
리뷰-이슈 중복 제거 후 행 수: 1567

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence,review_datetime,release_date,days_from_release,review_recency_group,playtime_stage,steam_negative_flag,steam_positive_flag,llm_negative_or_mixed_flag,llm_positive_flag,high_urgency_flag,early_playtime_flag,recent_30d_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation,issue_positive_flag,issue_negative_or_mixed_flag,issue_negative_flag,issue_mixed_flag
0,162551168,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.433333,7,0.558690,positive_praise,긍정 칭찬,positive,"Art Style, Music, Atmosphere, 21:9 support are great.",2024-04-09 16:16:12,2024-04-09,0,older_90d,0-1h,False,True,False,True,False,True,False,"아트 스타일, 음악, 분위기가 훌륭하며 21:9 울트라와이드 해상도를 지원하는 점에 만족함.","현재의 독특한 아트 스타일과 분위기를 유지하고, 향후 업데이트에서도 울트라와이드 해상도 지원을 지속적으로 관리할 것.",exact_match,True,False,False,False
1,162551849,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.533333,3,0.476679,positive_praise,긍정 칭찬,positive,Great game.,2024-04-09 16:27:50,2024-04-09,0,older_90d,0-1h,False,True,False,True,False,True,False,게임이 매우 독특하고 재미있다는 긍정적인 평가.,현재의 독특한 게임 컨셉과 분위기를 유지하며 플레이어들에게 긍정적인 경험을 지속적으로 제공할 것.,exact_match,True,False,False,False
2,162552645,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,1.200000,28,0.735037,positive_praise,긍정 칭찬,positive,"Short but sweet puzzle shooter, fun gameplay loop.",2024-04-09 16:41:02,2024-04-09,0,older_90d,1-5h,False,True,False,True,False,True,False,퍼즐 슈팅 게임으로서의 재미와 리플레이 가치를 높게 평가함.,"현재의 퍼즐 슈팅 메커니즘과 리플레이 가치를 강화하고, 리더보드 시스템이 원활하게 작동하도록 유지할 것.",exact_match,True,False,False,False
3,162552871,1309950,Children of the Sun,positive,positive,positive_praise,low,D0-D30,0.416667,77,0.756212,positive_praise,긍정 칭찬,positive,"Amazing art style, simple but satisfying gameplay. Fairly priced.",2024-04-09 16:44:51,2024-04-09,0,older_90d,0-1h,False,True,False,True,False,True,False,"Killer7와 Sniper Elite를 섞은 듯한 독특한 게임성, 훌륭한 아트 스타일과 만족스러운 게임 플레이를 갖춘 가성비 좋은 게임.",현재의 독특한 아트 스타일과 만족스러운 게임 플레이 루프를 유지 및 강화할 것.,exact_match,True,False,False,False
4,162556466,1309950,Children of the Sun,positive,positive,control,medium,D0-D30,1.766667,4,0.583224,control,조작감,negative,"controls to some extent. missed the ""SINGLE RIGHT CLICK"" prompted in RED",2024-04-09 17:41:22,2024-04-09,0,older_90d,1-5h,False,True,False,True,False,True,False,전반적으로 좋은 게임이나 조작법에 다소 아쉬움이 있음. 튜토리얼 안내가 명확하지 않다고 느낄 수 있음.,튜토리얼의 핵심 조작 안내(예: 우클릭)가 더 직관적으로 보이도록 UI/UX 가독성 개선 검토.,exact_match,False,True,True,False

게임 단위 요약: (1, 16)

,appid,game_name,review_count,issue_tag_count,steam_positive_review_count,steam_negative_review_count,steam_positive_rate,llm_positive_review_count,llm_negative_mixed_review_count,llm_negative_mixed_rate,high_urgency_review_count,high_urgency_rate,first_review_datetime,last_review_datetime,mean_playtime_at_review_hours,median_playtime_at_review_hours
0,1309950,Children of the Sun,883,1567,809,74,0.9162,700,177,0.2005,31,0.0351,2024-04-09 16:16:12,2026-04-28 06:21:38,4.3,3.7

이슈 단위 요약: (19, 28)
최종 우선 검토 수준 분포

  rule_priority_hint  issue_count
0                  하           10
1                  상            6
2                  중            3

절대 기준 후보 분포

  priority_candidate  issue_count
0                  하           10
1                  상            6
2                  중            3

,llm_issue_category,appid,game_name,issue_name_kor,affected_review_count,positive_review_count,negative_review_count,mixed_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_negative_mixed_review_count,recent_30d_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,avg_playtime_at_review_hours,median_playtime_at_review_hours,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_rate,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,patch_ops_note
7,gameplay_loop,1309950,Children of the Sun,게임플레이 루프,179,63,93,6,99,50,11,11,5,2,87,3.86,3.55,0.0615,0.5531,0.2793,0.4,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 179개, 부정·혼합 99개, Steam 비추천 맥락 50개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 87개, High urgency 후보 11개(보조 참고), 절대 기준 후보 상...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
6,difficulty,1309950,Children of the Sun,난이도,97,18,46,4,50,10,4,4,1,1,37,5.01,3.93,0.0412,0.5155,0.1031,1.0,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 97개, 부정·혼합 50개, Steam 비추천 맥락 10개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 37개, High urgency 후보 4개(보조 참고), 절대 기준 후보 상, ...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
2,content_volume,1309950,Children of the Sun,콘텐츠 분량,208,25,52,4,56,13,2,2,1,0,40,4.12,3.81,0.0096,0.2692,0.0625,0.0,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 208개, 부정·혼합 56개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 40개, High urgency 후보 2개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
8,graphics_audio,1309950,Children of the Sun,그래픽/사운드,87,34,36,5,41,21,7,6,2,2,29,3.96,3.50,0.0805,0.4713,0.2414,1.0,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 87개, 부정·혼합 41개, Steam 비추천 맥락 21개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 29개, High urgency 후보 7개(보조 참고), 절대 기준 후보 상, ...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
14,price_value,1309950,Children of the Sun,가격/가치,58,13,27,3,30,13,0,0,1,0,27,3.39,3.43,0.0000,0.5172,0.2241,0.0,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 58개, 부정·혼합 30개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 27개, 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
17,story,1309950,Children of the Sun,스토리,65,14,22,1,23,11,0,0,0,0,15,4.04,4.03,0.0000,0.3538,0.1692,0.0,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 65개, 부정·혼합 23개, Steam 비추천 맥락 11개, 초반 플레이타임 부정·혼합 15개, 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
18,ui_ux,1309950,Children of the Sun,UI/UX,33,3,27,1,28,7,6,6,2,2,20,4.92,3.25,0.1818,0.8485,0.2121,1.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 33개, 부정·혼합 28개, Steam 비추천 맥락 7개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 20개, High urgency 후보 6개(보조 참고), 절대 기준 후보 중, 규...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
3,control,1309950,Children of the Sun,조작감,30,5,20,1,21,7,5,5,0,0,14,4.14,3.29,0.1667,0.7000,0.2333,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 5개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
11,other,1309950,Children of the Sun,기타,38,2,11,0,11,6,2,2,0,0,10,3.06,2.88,0.0526,0.2895,0.1579,0.0,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,"영향 리뷰 38개, 부정·혼합 11개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 10개, High urgency 후보 2개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 범...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
1,bug,1309950,Children of the Sun,버그,10,0,10,0,10,4,6,6,0,0,8,4.31,3.47,0.6000,1.0000,0.4000,0.0,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 10개, 부정·혼합 10개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
16,save_progression,1309950,Children of the Sun,저장/진행,5,0,5,0,5,3,5,5,0,0,5,2.01,1.43,1.0000,1.0000,0.6000,0.0,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 5개, 부정·혼합 5개, Steam 비추천 맥락 3개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
4,crash,1309950,Children of the Sun,크래시,5,0,5,0,5,0,5,5,0,0,5,1.99,2.57,1.0000,1.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 5개, 부정·혼합 5개, Steam 비추천 맥락 0개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
0,balance,1309950,Children of the Sun,밸런스,4,0,3,1,4,1,0,0,0,0,2,5.31,4.87,0.0000,1.0000,0.2500,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 4개, 부정·혼합 4개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
15,progression_grind,1309950,Children of the Sun,성장/반복 노가다,5,2,2,0,2,1,0,0,0,0,2,4.27,3.65,0.0000,0.4000,0.2000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 5개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
10,optimization,1309950,Children of the Sun,최적화,2,0,2,0,2,0,1,1,0,0,0,5.96,5.96,0.5000,1.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 0개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
9,multiplayer_network,1309950,Children of the Sun,멀티/네트워크,2,0,1,0,1,1,0,0,0,0,1,3.14,3.14,0.0000,0.5000,0.5000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 2개, 부정·혼합 1개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
5,developer_communication,1309950,Children of the Sun,개발사 소통,1,0,1,0,1,1,0,0,0,0,1,0.10,0.10,0.0000,1.0000,1.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
12,performance,1309950,Children of the Sun,성능,2,1,0,0,0,0,0,0,0,0,0,7.22,7.22,0.0000,0.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 2개, 부정·혼합 0개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
13,positive_praise,1309950,Children of the Sun,긍정 칭찬,736,736,0,0,0,11,6,0,10,0,0,4.40,3.86,0.0082,0.0000,0.0149,0.0,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

플레이타임 구간별 이슈 요약: (49, 7)

,playtime_stage,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
5,0-1h,gameplay_loop,게임플레이 루프,28,23,4,21
6,0-1h,graphics_audio,그래픽/사운드,13,9,2,10
2,0-1h,control,조작감,5,5,1,3
12,0-1h,story,스토리,5,5,0,5
7,0-1h,other,기타,8,4,1,3
9,0-1h,price_value,가격/가치,5,4,0,3
0,0-1h,bug,버그,2,2,1,0
1,0-1h,content_volume,콘텐츠 분량,3,2,0,2
13,0-1h,ui_ux,UI/UX,2,2,0,0
3,0-1h,crash,크래시,1,1,1,0
11,0-1h,save_progression,저장/진행,1,1,1,0
4,0-1h,developer_communication,개발사 소통,1,1,0,1
10,0-1h,progression_grind,성장/반복 노가다,1,1,0,1
8,0-1h,positive_praise,긍정 칭찬,48,0,1,3
20,1-5h,gameplay_loop,게임플레이 루프,112,64,7,27
16,1-5h,content_volume,콘텐츠 분량,160,38,1,10
19,1-5h,difficulty,난이도,67,37,4,10
25,1-5h,price_value,가격/가치,45,23,0,8
21,1-5h,graphics_audio,그래픽/사운드,48,20,3,10
29,1-5h,ui_ux,UI/UX,21,18,6,6

최근성 구간별 이슈 요약: (39, 7)

,review_recency_group,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
15,last_30d,gameplay_loop,게임플레이 루프,5,2,0,1
16,last_30d,graphics_audio,그래픽/사운드,2,2,0,1
19,last_30d,ui_ux,UI/UX,2,2,0,0
14,last_30d,difficulty,난이도,1,1,0,0
13,last_30d,content_volume,콘텐츠 분량,1,0,0,0
17,last_30d,positive_praise,긍정 칭찬,10,0,0,0
18,last_30d,price_value,가격/가치,1,0,0,0
2,31-60d,gameplay_loop,게임플레이 루프,1,1,0,0
0,31-60d,content_volume,콘텐츠 분량,3,0,0,0
1,31-60d,difficulty,난이도,1,0,0,0
3,31-60d,graphics_audio,그래픽/사운드,1,0,0,0
4,31-60d,positive_praise,긍정 칭찬,8,0,0,0
6,61-90d,control,조작감,2,1,0,0
7,61-90d,difficulty,난이도,2,1,0,0
8,61-90d,gameplay_loop,게임플레이 루프,2,1,0,0
12,61-90d,ui_ux,UI/UX,1,1,0,0
5,61-90d,content_volume,콘텐츠 분량,1,0,0,0
9,61-90d,graphics_audio,그래픽/사운드,2,0,0,0
10,61-90d,positive_praise,긍정 칭찬,12,0,0,0
11,61-90d,story,스토리,1,0,0,0

패치·운영 전략 생성용 근거 테이블: (19, 29)

,llm_issue_category,issue_name_kor,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,priority_reason,patch_ops_note
7,gameplay_loop,게임플레이 루프,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,179,99,50,11,2,87,"영향 리뷰 179개, 부정·혼합 99개, Steam 비추천 맥락 50개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 87개, High urgency 후보 11개(보조 참고), 절대 기준 후보 상...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
6,difficulty,난이도,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,97,50,10,4,1,37,"영향 리뷰 97개, 부정·혼합 50개, Steam 비추천 맥락 10개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 37개, High urgency 후보 4개(보조 참고), 절대 기준 후보 상, ...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
2,content_volume,콘텐츠 분량,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,208,56,13,2,0,40,"영향 리뷰 208개, 부정·혼합 56개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 40개, High urgency 후보 2개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
8,graphics_audio,그래픽/사운드,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,87,41,21,7,2,29,"영향 리뷰 87개, 부정·혼합 41개, Steam 비추천 맥락 21개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 29개, High urgency 후보 7개(보조 참고), 절대 기준 후보 상, ...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
14,price_value,가격/가치,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,58,30,13,0,0,27,"영향 리뷰 58개, 부정·혼합 30개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 27개, 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
17,story,스토리,장기 검토,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,65,23,11,0,0,15,"영향 리뷰 65개, 부정·혼합 23개, Steam 비추천 맥락 11개, 초반 플레이타임 부정·혼합 15개, 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
18,ui_ux,UI/UX,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,33,28,7,6,2,20,"영향 리뷰 33개, 부정·혼합 28개, Steam 비추천 맥락 7개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 20개, High urgency 후보 6개(보조 참고), 절대 기준 후보 중, 규...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
3,control,조작감,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,30,21,7,5,0,14,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 5개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
11,other,기타,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,38,11,6,2,0,10,"영향 리뷰 38개, 부정·혼합 11개, Steam 비추천 맥락 6개, 초반 플레이타임 부정·혼합 10개, High urgency 후보 2개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 범...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
1,bug,버그,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,10,10,4,6,0,8,"영향 리뷰 10개, 부정·혼합 10개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
16,save_progression,저장/진행,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,5,5,3,5,0,5,"영향 리뷰 5개, 부정·혼합 5개, Steam 비추천 맥락 3개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
4,crash,크래시,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,5,5,0,5,0,5,"영향 리뷰 5개, 부정·혼합 5개, Steam 비추천 맥락 0개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 5개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
0,balance,밸런스,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,4,4,1,0,0,2,"영향 리뷰 4개, 부정·혼합 4개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
15,progression_grind,성장/반복 노가다,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,5,2,1,0,0,2,"영향 리뷰 5개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
10,optimization,최적화,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,2,2,0,1,0,0,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 0개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
9,multiplayer_network,멀티/네트워크,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,2,1,1,0,0,1,"영향 리뷰 2개, 부정·혼합 1개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
5,developer_communication,개발사 소통,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,1,0,0,1,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
12,performance,성능,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,2,0,0,0,0,0,"영향 리뷰 2개, 부정·혼합 0개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
13,positive_praise,긍정 칭찬,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,736,0,11,6,0,0,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

Tableau/보고서 원천 데이터: (1567, 40)

,appid,game_name,recommendationid,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,llm_sentiment,steam_llm_sentiment_relation,playtime_at_review_hours,playtime_stage,early_playtime_flag,votes_up,weighted_vote_score,llm_urgency_candidate,high_urgency_flag,llm_issue_category,issue_name_kor,llm_issue_sentiment,issue_positive_flag,issue_negative_or_mixed_flag,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,patch_ops_note,llm_issue_evidence
0,1309950,Children of the Sun,162551168,2024-04-09 16:16:12,2024-04-09,0,D0-D30,older_90d,positive,positive,exact_match,0.433333,0-1h,True,7,0.558690,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",736,0,11,6,0.0082,0.0,0.0149,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","Art Style, Music, Atmosphere, 21:9 support are great."
1,1309950,Children of the Sun,162551849,2024-04-09 16:27:50,2024-04-09,0,D0-D30,older_90d,positive,positive,exact_match,0.533333,0-1h,True,3,0.476679,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",736,0,11,6,0.0082,0.0,0.0149,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",Great game.
2,1309950,Children of the Sun,162552645,2024-04-09 16:41:02,2024-04-09,0,D0-D30,older_90d,positive,positive,exact_match,1.200000,1-5h,True,28,0.735037,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",736,0,11,6,0.0082,0.0,0.0149,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","Short but sweet puzzle shooter, fun gameplay loop."
3,1309950,Children of the Sun,162552871,2024-04-09 16:44:51,2024-04-09,0,D0-D30,older_90d,positive,positive,exact_match,0.416667,0-1h,True,77,0.756212,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 736개, 부정·혼합 0개, Steam 비추천 맥락 11개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",736,0,11,6,0.0082,0.0,0.0149,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","Amazing art style, simple but satisfying gameplay. Fairly priced."
4,1309950,Children of the Sun,162556466,2024-04-09 17:41:22,2024-04-09,0,D0-D30,older_90d,positive,positive,exact_match,1.766667,1-5h,True,4,0.583224,medium,False,control,조작감,negative,False,True,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 14개, High urgency 후보 5개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 S...",30,21,7,5,0.1667,0.7,0.2333,0,14,"이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다.","controls to some extent. missed the ""SINGLE RIGHT CLICK"" prompted in RED"

저장 완료
저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunch_preprocess_data

,파일명,행 수,역할
0,postlaunch_review_base.csv,883,리뷰 1개 단위 전처리 결과
1,postlaunch_issue_summary.csv,19,이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약
2,postlaunch_patch_ops_evidence_base.csv,19,03-2 LLM 패치·운영 전략 생성용 근거 데이터
3,tableau_postlaunch_patch_ops_source.csv,1567,Tableau/보고서용 원천 데이터

검증 통과
리뷰 수: 883
리뷰-이슈 수: 1567
이슈 종류 수: 19
절대 기준 후보 분포:

  priority_candidate  issue_count
0                  하           10
1                  상            6
2                  중            3

최종 우선 검토 수준 분포:

  rule_priority_hint  issue_count
0                  하           10
1                  상            6
2                  중            3

최종 '상' 제한 기준: 최대 6개
High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.

==========================================================================================
03-1번 출시 후 전처리 실행: laundry_store_simulator
==========================================================================================
리뷰 단위 LLM 결과: (575, 20)
이슈 태그 단위 결과: (1084, 15)

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,steam_label_text,playtime_at_review_hours,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_primary_issue,llm_issue_tags,llm_urgency_candidate,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,182347230,3150440,Laundry Store Simulator,2024-12-09 15:56:21,2024-12-09,0,D0-D30,positive,0.450000,3,0.518011,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""great sim game, love it""}, {""category"": ""game...",low,"게임에 대한 전반적인 만족감을 표현하며, 데모를 통해 미리 경험해보고 구매를 결정할 수 있는 점을 긍정적으로 평가함.","현재의 게임 플레이 루프와 데모 버전의 긍정적인 경험을 유지하고, 초반 난이도(직원 고용 전)에 대한 튜토리얼 보강을 고려할 것.",exact_match
1,success,182348696,3150440,Laundry Store Simulator,2024-12-09 16:18:17,2024-12-09,0,D0-D30,positive,0.950000,4,0.538090,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""turn your brain off, gas station sim vibe""}]",low,"아무 생각 없이 즐길 수 있는 힐링 시뮬레이션 게임으로, 유사 장르 게임과 비교하여 긍정적인 분위기를 언급함.","현재의 편안하고 몰입감 있는 게임 분위기를 유지하고, 시뮬레이션 장르 팬들에게 어필할 수 있는 요소들을 지속적으로 강화할 것.",exact_match
2,success,182363078,3150440,Laundry Store Simulator,2024-12-09 20:01:00,2024-12-09,0,D0-D30,positive,3.450000,1,0.498008,mixed,3,bug,"[{""category"": ""bug"", ""sentiment"": ""negative"", ""evidence"": ""Items hover in air, amount shows 0, slippery floors not f...",high,"전반적으로는 만족하나 미니마트 아이템 배치 버그, 업그레이드 UI 불편함, 바구니 배치 관련 소프트락 가능성 등 기술적 문제와 편의성 개선이 필요함.","미니마트 아이템 배치 버그 수정, 업그레이드 UI 프로세스 간소화, 바구니 배치 공간 확보 및 소프트락 방지 로직 검토 필요.",partial_match
3,success,182369738,3150440,Laundry Store Simulator,2024-12-09 21:46:50,2024-12-09,0,D0-D30,positive,1.350000,1,0.498008,positive,4,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""A good base with loads of potential, good con...",low,"게임의 잠재력과 컨셉을 긍정적으로 평가하며, 사소한 버그는 있으나 향후 업데이트를 기대함.","현재의 게임 컨셉과 로드맵을 유지하며, 언급된 사소한 버그들을 수정하여 안정성을 높일 것.",exact_match
4,success,182381083,3150440,Laundry Store Simulator,2024-12-10 01:20:29,2024-12-09,1,D0-D30,positive,2.083333,1,0.498008,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""many features and soothing music, GOAT Christ...",low,"다양한 기능과 편안한 음악에 만족하며, 올해 최고의 크리스마스 선물이라고 극찬함.","현재의 게임 기능과 분위기(음악 등)를 유지하고, 긍정적인 사용자 경험을 지속할 수 있도록 관리할 것.",exact_match

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence
0,182347230,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.45,3,0.518011,positive_praise,긍정 칭찬,positive,"great sim game, love it"
1,182347230,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.45,3,0.518011,gameplay_loop,게임플레이 루프,neutral,chaotic before getting employees
2,182348696,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.95,4,0.538090,positive_praise,긍정 칭찬,positive,"turn your brain off, gas station sim vibe"
3,182363078,3150440,Laundry Store Simulator,positive,mixed,bug,high,D0-D30,3.45,1,0.498008,bug,버그,negative,"Items hover in air, amount shows 0, slippery floors not found"
4,182363078,3150440,Laundry Store Simulator,positive,mixed,bug,high,D0-D30,3.45,1,0.498008,ui_ux,UI/UX,negative,switch out of pc everytime to upgrade

필수 컬럼 확인 완료
리뷰 단위 전처리 결과: (575, 28)
최신 리뷰일: 2026-05-02 21:01:43

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,steam_positive_flag,steam_negative_flag,playtime_at_review_hours,playtime_stage,early_playtime_flag,recent_30d_flag,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_negative_or_mixed_flag,llm_positive_flag,llm_primary_issue,llm_urgency_candidate,high_urgency_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,182347230,3150440,Laundry Store Simulator,2024-12-09 15:56:21,2024-12-09,0,D0-D30,older_90d,positive,True,False,0.450000,0-1h,True,False,3,0.518011,positive,5,False,True,positive_praise,low,False,"게임에 대한 전반적인 만족감을 표현하며, 데모를 통해 미리 경험해보고 구매를 결정할 수 있는 점을 긍정적으로 평가함.","현재의 게임 플레이 루프와 데모 버전의 긍정적인 경험을 유지하고, 초반 난이도(직원 고용 전)에 대한 튜토리얼 보강을 고려할 것.",exact_match
1,success,182348696,3150440,Laundry Store Simulator,2024-12-09 16:18:17,2024-12-09,0,D0-D30,older_90d,positive,True,False,0.950000,0-1h,True,False,4,0.538090,positive,5,False,True,positive_praise,low,False,"아무 생각 없이 즐길 수 있는 힐링 시뮬레이션 게임으로, 유사 장르 게임과 비교하여 긍정적인 분위기를 언급함.","현재의 편안하고 몰입감 있는 게임 분위기를 유지하고, 시뮬레이션 장르 팬들에게 어필할 수 있는 요소들을 지속적으로 강화할 것.",exact_match
2,success,182363078,3150440,Laundry Store Simulator,2024-12-09 20:01:00,2024-12-09,0,D0-D30,older_90d,positive,True,False,3.450000,1-5h,True,False,1,0.498008,mixed,3,True,False,bug,high,True,"전반적으로는 만족하나 미니마트 아이템 배치 버그, 업그레이드 UI 불편함, 바구니 배치 관련 소프트락 가능성 등 기술적 문제와 편의성 개선이 필요함.","미니마트 아이템 배치 버그 수정, 업그레이드 UI 프로세스 간소화, 바구니 배치 공간 확보 및 소프트락 방지 로직 검토 필요.",partial_match
3,success,182369738,3150440,Laundry Store Simulator,2024-12-09 21:46:50,2024-12-09,0,D0-D30,older_90d,positive,True,False,1.350000,1-5h,True,False,1,0.498008,positive,4,False,True,positive_praise,low,False,"게임의 잠재력과 컨셉을 긍정적으로 평가하며, 사소한 버그는 있으나 향후 업데이트를 기대함.","현재의 게임 컨셉과 로드맵을 유지하며, 언급된 사소한 버그들을 수정하여 안정성을 높일 것.",exact_match
4,success,182381083,3150440,Laundry Store Simulator,2024-12-10 01:20:29,2024-12-09,1,D0-D30,older_90d,positive,True,False,2.083333,1-5h,True,False,1,0.498008,positive,5,False,True,positive_praise,low,False,"다양한 기능과 편안한 음악에 만족하며, 올해 최고의 크리스마스 선물이라고 극찬함.","현재의 게임 기능과 분위기(음악 등)를 유지하고, 긍정적인 사용자 경험을 지속할 수 있도록 관리할 것.",exact_match

이슈 태그 원본 행 수: 1084
리뷰-이슈 중복 제거 후 행 수: 1064

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence,review_datetime,release_date,days_from_release,review_recency_group,playtime_stage,steam_negative_flag,steam_positive_flag,llm_negative_or_mixed_flag,llm_positive_flag,high_urgency_flag,early_playtime_flag,recent_30d_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation,issue_positive_flag,issue_negative_or_mixed_flag,issue_negative_flag,issue_mixed_flag
0,182347230,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.45,3,0.518011,positive_praise,긍정 칭찬,positive,"great sim game, love it",2024-12-09 15:56:21,2024-12-09,0,older_90d,0-1h,False,True,False,True,False,True,False,"게임에 대한 전반적인 만족감을 표현하며, 데모를 통해 미리 경험해보고 구매를 결정할 수 있는 점을 긍정적으로 평가함.","현재의 게임 플레이 루프와 데모 버전의 긍정적인 경험을 유지하고, 초반 난이도(직원 고용 전)에 대한 튜토리얼 보강을 고려할 것.",exact_match,True,False,False,False
1,182347230,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.45,3,0.518011,gameplay_loop,게임플레이 루프,neutral,chaotic before getting employees,2024-12-09 15:56:21,2024-12-09,0,older_90d,0-1h,False,True,False,True,False,True,False,"게임에 대한 전반적인 만족감을 표현하며, 데모를 통해 미리 경험해보고 구매를 결정할 수 있는 점을 긍정적으로 평가함.","현재의 게임 플레이 루프와 데모 버전의 긍정적인 경험을 유지하고, 초반 난이도(직원 고용 전)에 대한 튜토리얼 보강을 고려할 것.",exact_match,False,False,False,False
2,182348696,3150440,Laundry Store Simulator,positive,positive,positive_praise,low,D0-D30,0.95,4,0.538090,positive_praise,긍정 칭찬,positive,"turn your brain off, gas station sim vibe",2024-12-09 16:18:17,2024-12-09,0,older_90d,0-1h,False,True,False,True,False,True,False,"아무 생각 없이 즐길 수 있는 힐링 시뮬레이션 게임으로, 유사 장르 게임과 비교하여 긍정적인 분위기를 언급함.","현재의 편안하고 몰입감 있는 게임 분위기를 유지하고, 시뮬레이션 장르 팬들에게 어필할 수 있는 요소들을 지속적으로 강화할 것.",exact_match,True,False,False,False
3,182363078,3150440,Laundry Store Simulator,positive,mixed,bug,high,D0-D30,3.45,1,0.498008,bug,버그,negative,"Items hover in air, amount shows 0, slippery floors not found",2024-12-09 20:01:00,2024-12-09,0,older_90d,1-5h,False,True,True,False,True,True,False,"전반적으로는 만족하나 미니마트 아이템 배치 버그, 업그레이드 UI 불편함, 바구니 배치 관련 소프트락 가능성 등 기술적 문제와 편의성 개선이 필요함.","미니마트 아이템 배치 버그 수정, 업그레이드 UI 프로세스 간소화, 바구니 배치 공간 확보 및 소프트락 방지 로직 검토 필요.",partial_match,False,True,True,False
4,182363078,3150440,Laundry Store Simulator,positive,mixed,bug,high,D0-D30,3.45,1,0.498008,ui_ux,UI/UX,negative,switch out of pc everytime to upgrade,2024-12-09 20:01:00,2024-12-09,0,older_90d,1-5h,False,True,True,False,True,True,False,"전반적으로는 만족하나 미니마트 아이템 배치 버그, 업그레이드 UI 불편함, 바구니 배치 관련 소프트락 가능성 등 기술적 문제와 편의성 개선이 필요함.","미니마트 아이템 배치 버그 수정, 업그레이드 UI 프로세스 간소화, 바구니 배치 공간 확보 및 소프트락 방지 로직 검토 필요.",partial_match,False,True,True,False

게임 단위 요약: (1, 16)

,appid,game_name,review_count,issue_tag_count,steam_positive_review_count,steam_negative_review_count,steam_positive_rate,llm_positive_review_count,llm_negative_mixed_review_count,llm_negative_mixed_rate,high_urgency_review_count,high_urgency_rate,first_review_datetime,last_review_datetime,mean_playtime_at_review_hours,median_playtime_at_review_hours
0,3150440,Laundry Store Simulator,575,1064,486,89,0.8452,358,213,0.3704,99,0.1722,2024-12-09 15:56:21,2026-05-02 21:01:43,20.68,14.2

이슈 단위 요약: (21, 28)
최종 우선 검토 수준 분포

  rule_priority_hint  issue_count
0                  하           10
1                  중            6
2                  상            5

절대 기준 후보 분포

  priority_candidate  issue_count
0                  하           10
1                  중            6
2                  상            5

,llm_issue_category,appid,game_name,issue_name_kor,affected_review_count,positive_review_count,negative_review_count,mixed_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_negative_mixed_review_count,recent_30d_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,avg_playtime_at_review_hours,median_playtime_at_review_hours,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_rate,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,patch_ops_note
1,bug,3150440,Laundry Store Simulator,버그,121,3,111,2,113,37,64,64,4,4,21,20.01,12.88,0.5289,0.9339,0.3058,1.00,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 121개, 부정·혼합 113개, Steam 비추천 맥락 37개, 최근 30일 부정·혼합 4개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 64개(보조 참고), 절대 기준 후보 ...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
17,save_progression,3150440,Laundry Store Simulator,저장/진행,17,0,17,0,17,12,17,17,1,1,8,5.70,5.03,1.0000,1.0000,0.7059,1.00,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 17개, 부정·혼합 17개, Steam 비추천 맥락 12개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 17개(보조 참고), 절대 기준 후보 상, ...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
7,gameplay_loop,3150440,Laundry Store Simulator,게임플레이 루프,154,35,88,4,92,35,37,33,4,1,13,23.64,17.52,0.2403,0.5974,0.2273,0.25,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 154개, 부정·혼합 92개, Steam 비추천 맥락 35개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 13개, High urgency 후보 37개(보조 참고), 절대 기준 후보 상...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
16,progression_grind,3150440,Laundry Store Simulator,성장/반복 노가다,54,2,42,2,44,17,14,14,4,4,3,34.57,28.16,0.2593,0.8148,0.3148,1.00,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 54개, 부정·혼합 44개, Steam 비추천 맥락 17개, 최근 30일 부정·혼합 4개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 14개(보조 참고), 절대 기준 후보 상, ...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
20,ui_ux,3150440,Laundry Store Simulator,UI/UX,57,0,42,0,42,11,12,11,2,2,3,27.07,23.27,0.2105,0.7368,0.1930,1.00,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 57개, 부정·혼합 42개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 12개(보조 참고), 절대 기준 후보 상, ...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
13,performance,3150440,Laundry Store Simulator,성능,14,3,11,0,11,6,9,9,1,1,2,26.67,14.40,0.6429,0.7857,0.4286,1.00,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 14개, 부정·혼합 11개, Steam 비추천 맥락 6개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
0,balance,3150440,Laundry Store Simulator,밸런스,36,3,30,0,30,10,8,8,1,1,2,23.11,18.83,0.2222,0.8333,0.2778,1.00,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 36개, 부정·혼합 30개, Steam 비추천 맥락 10개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
3,control,3150440,Laundry Store Simulator,조작감,19,1,18,0,18,8,7,7,1,1,6,14.10,10.72,0.3684,0.9474,0.4211,1.00,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 19개, 부정·혼합 18개, Steam 비추천 맥락 8개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 6개, High urgency 후보 7개(보조 참고), 절대 기준 후보 중, 규칙...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
5,developer_communication,3150440,Laundry Store Simulator,개발사 소통,20,6,13,0,13,9,8,8,0,0,0,31.52,23.43,0.4000,0.6500,0.4500,0.00,운영 커뮤니케이션 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 20개, 부정·혼합 13개, Steam 비추천 맥락 9개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
2,content_volume,3150440,Laundry Store Simulator,콘텐츠 분량,59,14,20,0,20,8,9,7,1,0,2,26.74,24.68,0.1525,0.3390,0.1356,0.00,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 59개, 부정·혼합 20개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
12,other,3150440,Laundry Store Simulator,기타,30,1,21,0,21,16,9,8,0,0,6,18.32,12.58,0.3000,0.7000,0.5333,0.00,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 16개, 초반 플레이타임 부정·혼합 6개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 범...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
4,crash,3150440,Laundry Store Simulator,크래시,7,0,7,0,7,5,7,7,0,0,0,21.55,9.22,1.0000,1.0000,0.7143,0.00,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 7개, 부정·혼합 7개, Steam 비추천 맥락 5개, High urgency 후보 7개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
6,difficulty,3150440,Laundry Store Simulator,난이도,11,1,5,1,6,4,4,4,0,0,0,16.08,10.83,0.3636,0.5455,0.3636,0.00,단기 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 11개, 부정·혼합 6개, Steam 비추천 맥락 4개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
8,graphics_audio,3150440,Laundry Store Simulator,그래픽/사운드,19,4,12,0,12,2,4,3,0,0,2,14.90,10.68,0.2105,0.6316,0.1053,0.00,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 19개, 부정·혼합 12개, Steam 비추천 맥락 2개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
15,price_value,3150440,Laundry Store Simulator,가격/가치,14,8,6,0,6,2,0,0,0,0,1,20.37,18.83,0.0000,0.4286,0.1429,0.00,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 14개, 부정·혼합 6개, Steam 비추천 맥락 2개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
11,optimization,3150440,Laundry Store Simulator,최적화,8,2,4,0,4,1,1,1,0,0,0,29.34,21.39,0.1250,0.5000,0.1250,0.00,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 8개, 부정·혼합 4개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
18,story,3150440,Laundry Store Simulator,스토리,8,3,3,1,4,0,0,0,1,0,0,30.00,36.23,0.0000,0.5000,0.0000,0.00,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 8개, 부정·혼합 4개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
9,monetization,3150440,Laundry Store Simulator,과금,4,0,2,0,2,2,1,1,0,0,0,25.98,23.02,0.2500,0.5000,0.5000,0.00,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 4개, 부정·혼합 2개, Steam 비추천 맥락 2개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
10,multiplayer_network,3150440,Laundry Store Simulator,멀티/네트워크,6,1,2,0,2,0,0,0,0,0,2,5.57,6.25,0.0000,0.3333,0.0000,0.00,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 6개, 부정·혼합 2개, Steam 비추천 맥락 0개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
19,translation_localization,3150440,Laundry Store Simulator,번역/현지화,1,0,1,0,1,0,1,1,1,1,0,26.68,26.68,1.0000,1.0000,0.0000,1.00,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 최근 30일 부정·혼합 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천...",번역/현지화 불만이 실제 이해도와 진행 경험에 영향을 주는지 검토한다.

플레이타임 구간별 이슈 요약: (80, 7)

,playtime_stage,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
2,0-1h,control,조작감,4,4,3,4
5,0-1h,other,기타,3,2,0,2
0,0-1h,bug,버그,1,1,1,1
8,0-1h,save_progression,저장/진행,1,1,1,1
9,0-1h,ui_ux,UI/UX,1,1,1,1
1,0-1h,content_volume,콘텐츠 분량,1,1,0,1
3,0-1h,gameplay_loop,게임플레이 루프,2,1,0,1
4,0-1h,multiplayer_network,멀티/네트워크,1,1,0,0
7,0-1h,price_value,가격/가치,1,1,0,1
6,0-1h,positive_praise,긍정 칭찬,5,0,0,0
11,1-5h,bug,버그,22,20,17,9
14,1-5h,gameplay_loop,게임플레이 루프,16,12,4,5
22,1-5h,save_progression,저장/진행,7,7,7,3
17,1-5h,other,기타,5,4,1,3
21,1-5h,progression_grind,성장/반복 노가다,5,3,2,3
18,1-5h,performance,성능,3,2,2,1
24,1-5h,ui_ux,UI/UX,2,2,2,1
10,1-5h,balance,밸런스,3,2,0,1
13,1-5h,control,조작감,2,2,0,1
15,1-5h,graphics_audio,그래픽/사운드,3,2,0,0

최근성 구간별 이슈 요약: (49, 7)

,review_recency_group,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
18,last_30d,bug,버그,4,4,4,1
24,last_30d,progression_grind,성장/반복 노가다,4,4,1,1
28,last_30d,ui_ux,UI/UX,2,2,1,0
21,last_30d,gameplay_loop,게임플레이 루프,4,1,2,0
17,last_30d,balance,밸런스,1,1,1,0
20,last_30d,control,조작감,1,1,1,1
22,last_30d,performance,성능,1,1,1,0
25,last_30d,save_progression,저장/진행,1,1,1,0
27,last_30d,translation_localization,번역/현지화,1,1,1,0
23,last_30d,positive_praise,긍정 칭찬,10,0,1,0
19,last_30d,content_volume,콘텐츠 분량,1,0,0,0
26,last_30d,story,스토리,1,0,0,0
1,31-60d,bug,버그,4,4,1,2
5,31-60d,gameplay_loop,게임플레이 루프,6,4,1,2
3,31-60d,developer_communication,개발사 소통,1,1,1,1
2,31-60d,content_volume,콘텐츠 분량,2,1,0,1
7,31-60d,other,기타,3,1,0,0
9,31-60d,progression_grind,성장/반복 노가다,2,1,0,1
0,31-60d,balance,밸런스,2,0,0,0
4,31-60d,difficulty,난이도,1,0,0,0

패치·운영 전략 생성용 근거 테이블: (21, 29)

,llm_issue_category,issue_name_kor,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,priority_reason,patch_ops_note
1,bug,버그,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,121,113,37,64,4,21,"영향 리뷰 121개, 부정·혼합 113개, Steam 비추천 맥락 37개, 최근 30일 부정·혼합 4개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 64개(보조 참고), 절대 기준 후보 ...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
17,save_progression,저장/진행,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,17,17,12,17,1,8,"영향 리뷰 17개, 부정·혼합 17개, Steam 비추천 맥락 12개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 8개, High urgency 후보 17개(보조 참고), 절대 기준 후보 상, ...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
7,gameplay_loop,게임플레이 루프,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,154,92,35,37,1,13,"영향 리뷰 154개, 부정·혼합 92개, Steam 비추천 맥락 35개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 13개, High urgency 후보 37개(보조 참고), 절대 기준 후보 상...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
16,progression_grind,성장/반복 노가다,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,54,44,17,14,4,3,"영향 리뷰 54개, 부정·혼합 44개, Steam 비추천 맥락 17개, 최근 30일 부정·혼합 4개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 14개(보조 참고), 절대 기준 후보 상, ...",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
20,ui_ux,UI/UX,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,57,42,11,12,2,3,"영향 리뷰 57개, 부정·혼합 42개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 12개(보조 참고), 절대 기준 후보 상, ...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
13,performance,성능,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,14,11,6,9,1,2,"영향 리뷰 14개, 부정·혼합 11개, Steam 비추천 맥락 6개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
0,balance,밸런스,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,36,30,10,8,1,2,"영향 리뷰 36개, 부정·혼합 30개, Steam 비추천 맥락 10개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
3,control,조작감,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,19,18,8,7,1,6,"영향 리뷰 19개, 부정·혼합 18개, Steam 비추천 맥락 8개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 6개, High urgency 후보 7개(보조 참고), 절대 기준 후보 중, 규칙...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
5,developer_communication,개발사 소통,운영 커뮤니케이션 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,20,13,9,8,0,0,"영향 리뷰 20개, 부정·혼합 13개, Steam 비추천 맥락 9개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
2,content_volume,콘텐츠 분량,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,59,20,8,9,0,2,"영향 리뷰 59개, 부정·혼합 20개, Steam 비추천 맥락 8개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
12,other,기타,검토 필요,중,중,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,30,21,16,9,0,6,"영향 리뷰 30개, 부정·혼합 21개, Steam 비추천 맥락 16개, 초반 플레이타임 부정·혼합 6개, High urgency 후보 9개(보조 참고), 절대 기준 후보 중, 규칙 근거: 기타 이슈는 원인 범...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
4,crash,크래시,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,7,7,5,7,0,0,"영향 리뷰 7개, 부정·혼합 7개, Steam 비추천 맥락 5개, High urgency 후보 7개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
6,difficulty,난이도,단기 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,11,6,4,4,0,0,"영향 리뷰 11개, 부정·혼합 6개, Steam 비추천 맥락 4개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
8,graphics_audio,그래픽/사운드,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,19,12,2,4,0,2,"영향 리뷰 19개, 부정·혼합 12개, Steam 비추천 맥락 2개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
15,price_value,가격/가치,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,14,6,2,0,0,1,"영향 리뷰 14개, 부정·혼합 6개, Steam 비추천 맥락 2개, 초반 플레이타임 부정·혼합 1개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
11,optimization,최적화,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,8,4,1,1,0,0,"영향 리뷰 8개, 부정·혼합 4개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",최적화 이슈가 특정 구간이나 사양에서 반복되는지 확인한다.
18,story,스토리,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,8,4,0,0,0,0,"영향 리뷰 8개, 부정·혼합 4개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
9,monetization,과금,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,4,2,2,1,0,0,"영향 리뷰 4개, 부정·혼합 2개, Steam 비추천 맥락 2개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","가격, DLC, 과금 관련 불만이 반복되는지 확인하고 커뮤니케이션 방식을 점검한다."
10,multiplayer_network,멀티/네트워크,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,6,2,0,0,0,2,"영향 리뷰 6개, 부정·혼합 2개, Steam 비추천 맥락 0개, 초반 플레이타임 부정·혼합 2개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",세부 리뷰 확인 후 대응 방향을 검토한다.
19,translation_localization,번역/현지화,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,0,1,1,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 최근 30일 부정·혼합 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천...",번역/현지화 불만이 실제 이해도와 진행 경험에 영향을 주는지 검토한다.

Tableau/보고서 원천 데이터: (1064, 40)

,appid,game_name,recommendationid,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,llm_sentiment,steam_llm_sentiment_relation,playtime_at_review_hours,playtime_stage,early_playtime_flag,votes_up,weighted_vote_score,llm_urgency_candidate,high_urgency_flag,llm_issue_category,issue_name_kor,llm_issue_sentiment,issue_positive_flag,issue_negative_or_mixed_flag,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,patch_ops_note,llm_issue_evidence
0,3150440,Laundry Store Simulator,182347230,2024-12-09 15:56:21,2024-12-09,0,D0-D30,older_90d,positive,positive,exact_match,0.45,0-1h,True,3,0.518011,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 405개, 부정·혼합 0개, Steam 비추천 맥락 3개, High urgency 후보 17개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",405,0,3,17,0.0420,0.0000,0.0074,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","great sim game, love it"
1,3150440,Laundry Store Simulator,182347230,2024-12-09 15:56:21,2024-12-09,0,D0-D30,older_90d,positive,positive,exact_match,0.45,0-1h,True,3,0.518011,low,False,gameplay_loop,게임플레이 루프,neutral,False,False,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 154개, 부정·혼합 92개, Steam 비추천 맥락 35개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 13개, High urgency 후보 37개(보조 참고), 절대 기준 후보 상...",154,92,35,37,0.2403,0.5974,0.2273,1,13,"반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다.",chaotic before getting employees
2,3150440,Laundry Store Simulator,182348696,2024-12-09 16:18:17,2024-12-09,0,D0-D30,older_90d,positive,positive,exact_match,0.95,0-1h,True,4,0.538090,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 405개, 부정·혼합 0개, Steam 비추천 맥락 3개, High urgency 후보 17개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",405,0,3,17,0.0420,0.0000,0.0074,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.","turn your brain off, gas station sim vibe"
3,3150440,Laundry Store Simulator,182363078,2024-12-09 20:01:00,2024-12-09,0,D0-D30,older_90d,positive,mixed,partial_match,3.45,1-5h,True,1,0.498008,high,True,bug,버그,negative,False,True,즉시 확인,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 121개, 부정·혼합 113개, Steam 비추천 맥락 37개, 최근 30일 부정·혼합 4개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 64개(보조 참고), 절대 기준 후보 ...",121,113,37,64,0.5289,0.9339,0.3058,4,21,"반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다.","Items hover in air, amount shows 0, slippery floors not found"
4,3150440,Laundry Store Simulator,182363078,2024-12-09 20:01:00,2024-12-09,0,D0-D30,older_90d,positive,mixed,partial_match,3.45,1-5h,True,1,0.498008,high,True,ui_ux,UI/UX,negative,False,True,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 6개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 57개, 부정·혼합 42개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 2개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 12개(보조 참고), 절대 기준 후보 상, ...",57,42,11,12,0.2105,0.7368,0.1930,2,3,"메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다.",switch out of pc everytime to upgrade

저장 완료
저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postlaunch_preprocess_data

,파일명,행 수,역할
0,postlaunch_review_base.csv,575,리뷰 1개 단위 전처리 결과
1,postlaunch_issue_summary.csv,21,이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약
2,postlaunch_patch_ops_evidence_base.csv,21,03-2 LLM 패치·운영 전략 생성용 근거 데이터
3,tableau_postlaunch_patch_ops_source.csv,1064,Tableau/보고서용 원천 데이터

검증 통과
리뷰 수: 575
리뷰-이슈 수: 1064
이슈 종류 수: 21
절대 기준 후보 분포:

  priority_candidate  issue_count
0                  하           10
1                  중            6
2                  상            5

최종 우선 검토 수준 분포:

  rule_priority_hint  issue_count
0                  하           10
1                  중            6
2                  상            5

최종 '상' 제한 기준: 최대 6개
High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.

==========================================================================================
03-1번 출시 후 전처리 실행: endoparasitic_2
==========================================================================================
리뷰 단위 LLM 결과: (245, 20)
이슈 태그 단위 결과: (489, 15)

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,steam_label_text,playtime_at_review_hours,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_primary_issue,llm_issue_tags,llm_urgency_candidate,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,176177053,2990640,Endoparasitic 2,2024-10-01 20:00:52,2024-10-01,0,D0-D30,positive,0.266667,6,0.510040,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""한 손으로 플레이 가능한 조작감과 훌륭한 속편이라는 점을 칭찬함""}]",low,"한 손으로 플레이 가능한 조작감이 훌륭하며, 전작을 잇는 뛰어난 속편임.",현재의 직관적인 조작 방식과 게임성을 유지 및 강화할 것.,exact_match
1,success,176177300,2990640,Endoparasitic 2,2024-10-01 20:05:29,2024-10-01,0,D0-D30,positive,0.383333,1,0.490937,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""게임이 매우 훌륭하다고 언급함""}]",low,게임을 플레이한 후 매우 훌륭하다는 첫인상을 남김.,초반 플레이 경험이 긍정적이므로 현재의 게임 디자인 방향을 유지할 것.,exact_match
2,success,176179490,2990640,Endoparasitic 2,2024-10-01 20:46:59,2024-10-01,0,D0-D30,positive,10.433333,34,0.749335,positive,4,content_volume,"[{""category"": ""content_volume"", ""sentiment"": ""neutral"", ""evidence"": ""적 유형과 무기 종류가 각각 3개뿐이라는 점을 지적함""}, {""category"": ""...",medium,"적과 무기 종류가 적은 점은 아쉽지만, 사운드트랙, 스토리, 개선된 전투 시스템 등 전반적인 게임성이 매우 뛰어남.","콘텐츠 볼륨(적/무기 종류) 확장을 고려하되, 현재의 긍정적인 사운드트랙과 스토리텔링 강점을 유지할 것.",exact_match
3,success,176179851,2990640,Endoparasitic 2,2024-10-01 20:54:30,2024-10-01,0,D0-D30,positive,1.150000,9,0.597647,positive,5,positive_praise,"[{""category"": ""positive_praise"", ""sentiment"": ""positive"", ""evidence"": ""Polished and bug free, fun additional gamepla...",low,"전작의 장점을 잘 계승한 완성도 높은 후속작으로, 버그 없이 쾌적한 플레이와 재미있는 전투 및 맵 디자인을 높게 평가함.","현재의 게임 플레이 요소와 맵 디자인의 완성도를 유지하며, 향후 업데이트에서도 안정적인 빌드 품질을 지속적으로 관리할 것.",exact_match
4,success,176181376,2990640,Endoparasitic 2,2024-10-01 21:27:57,2024-10-01,0,D0-D30,positive,2.066667,4,0.537572,positive,5,positive_praise,"[{""category"": ""gameplay_loop"", ""sentiment"": ""positive"", ""evidence"": ""stuck in a corner, out of ammo and low on healt...",low,탄약 부족과 체력 고갈 등 극한의 상황에서 오는 긴장감을 긍정적으로 평가하며 게임의 재미를 극찬함.,현재의 긴장감 넘치는 게임 플레이 루프와 난이도 밸런스를 유지하여 플레이어에게 몰입감 있는 경험을 지속적으로 제공할 것.,exact_match

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence
0,176177053,2990640,Endoparasitic 2,positive,positive,positive_praise,low,D0-D30,0.266667,6,0.510040,positive_praise,긍정 칭찬,positive,한 손으로 플레이 가능한 조작감과 훌륭한 속편이라는 점을 칭찬함
1,176177300,2990640,Endoparasitic 2,positive,positive,positive_praise,low,D0-D30,0.383333,1,0.490937,positive_praise,긍정 칭찬,positive,게임이 매우 훌륭하다고 언급함
2,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,content_volume,콘텐츠 분량,neutral,적 유형과 무기 종류가 각각 3개뿐이라는 점을 지적함
3,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,gameplay_loop,게임플레이 루프,positive,크래프팅 시스템이 단순하지만 잘 작동하고 재미있음
4,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,story,스토리,positive,스토리가 전작보다 깊이 있고 재미있음

필수 컬럼 확인 완료
리뷰 단위 전처리 결과: (245, 28)
최신 리뷰일: 2026-04-10 23:16:46

,analysis_status,recommendationid,appid,game_name,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,steam_positive_flag,steam_negative_flag,playtime_at_review_hours,playtime_stage,early_playtime_flag,recent_30d_flag,votes_up,weighted_vote_score,llm_sentiment,sentiment_score,llm_negative_or_mixed_flag,llm_positive_flag,llm_primary_issue,llm_urgency_candidate,high_urgency_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation
0,success,176177053,2990640,Endoparasitic 2,2024-10-01 20:00:52,2024-10-01,0,D0-D30,older_90d,positive,True,False,0.266667,0-1h,True,False,6,0.510040,positive,5,False,True,positive_praise,low,False,"한 손으로 플레이 가능한 조작감이 훌륭하며, 전작을 잇는 뛰어난 속편임.",현재의 직관적인 조작 방식과 게임성을 유지 및 강화할 것.,exact_match
1,success,176177300,2990640,Endoparasitic 2,2024-10-01 20:05:29,2024-10-01,0,D0-D30,older_90d,positive,True,False,0.383333,0-1h,True,False,1,0.490937,positive,5,False,True,positive_praise,low,False,게임을 플레이한 후 매우 훌륭하다는 첫인상을 남김.,초반 플레이 경험이 긍정적이므로 현재의 게임 디자인 방향을 유지할 것.,exact_match
2,success,176179490,2990640,Endoparasitic 2,2024-10-01 20:46:59,2024-10-01,0,D0-D30,older_90d,positive,True,False,10.433333,5-20h,False,False,34,0.749335,positive,4,False,True,content_volume,medium,False,"적과 무기 종류가 적은 점은 아쉽지만, 사운드트랙, 스토리, 개선된 전투 시스템 등 전반적인 게임성이 매우 뛰어남.","콘텐츠 볼륨(적/무기 종류) 확장을 고려하되, 현재의 긍정적인 사운드트랙과 스토리텔링 강점을 유지할 것.",exact_match
3,success,176179851,2990640,Endoparasitic 2,2024-10-01 20:54:30,2024-10-01,0,D0-D30,older_90d,positive,True,False,1.150000,1-5h,True,False,9,0.597647,positive,5,False,True,positive_praise,low,False,"전작의 장점을 잘 계승한 완성도 높은 후속작으로, 버그 없이 쾌적한 플레이와 재미있는 전투 및 맵 디자인을 높게 평가함.","현재의 게임 플레이 요소와 맵 디자인의 완성도를 유지하며, 향후 업데이트에서도 안정적인 빌드 품질을 지속적으로 관리할 것.",exact_match
4,success,176181376,2990640,Endoparasitic 2,2024-10-01 21:27:57,2024-10-01,0,D0-D30,older_90d,positive,True,False,2.066667,1-5h,True,False,4,0.537572,positive,5,False,True,positive_praise,low,False,탄약 부족과 체력 고갈 등 극한의 상황에서 오는 긴장감을 긍정적으로 평가하며 게임의 재미를 극찬함.,현재의 긴장감 넘치는 게임 플레이 루프와 난이도 밸런스를 유지하여 플레이어에게 몰입감 있는 경험을 지속적으로 제공할 것.,exact_match

이슈 태그 원본 행 수: 489
리뷰-이슈 중복 제거 후 행 수: 477

,recommendationid,appid,game_name,steam_label_text,llm_sentiment,llm_primary_issue,llm_urgency_candidate,release_period,playtime_at_review_hours,votes_up,weighted_vote_score,llm_issue_category,issue_name_kor,llm_issue_sentiment,llm_issue_evidence,review_datetime,release_date,days_from_release,review_recency_group,playtime_stage,steam_negative_flag,steam_positive_flag,llm_negative_or_mixed_flag,llm_positive_flag,high_urgency_flag,early_playtime_flag,recent_30d_flag,llm_review_summary,llm_suggested_action,steam_llm_sentiment_relation,issue_positive_flag,issue_negative_or_mixed_flag,issue_negative_flag,issue_mixed_flag
0,176177053,2990640,Endoparasitic 2,positive,positive,positive_praise,low,D0-D30,0.266667,6,0.510040,positive_praise,긍정 칭찬,positive,한 손으로 플레이 가능한 조작감과 훌륭한 속편이라는 점을 칭찬함,2024-10-01 20:00:52,2024-10-01,0,older_90d,0-1h,False,True,False,True,False,True,False,"한 손으로 플레이 가능한 조작감이 훌륭하며, 전작을 잇는 뛰어난 속편임.",현재의 직관적인 조작 방식과 게임성을 유지 및 강화할 것.,exact_match,True,False,False,False
1,176177300,2990640,Endoparasitic 2,positive,positive,positive_praise,low,D0-D30,0.383333,1,0.490937,positive_praise,긍정 칭찬,positive,게임이 매우 훌륭하다고 언급함,2024-10-01 20:05:29,2024-10-01,0,older_90d,0-1h,False,True,False,True,False,True,False,게임을 플레이한 후 매우 훌륭하다는 첫인상을 남김.,초반 플레이 경험이 긍정적이므로 현재의 게임 디자인 방향을 유지할 것.,exact_match,True,False,False,False
2,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,content_volume,콘텐츠 분량,neutral,적 유형과 무기 종류가 각각 3개뿐이라는 점을 지적함,2024-10-01 20:46:59,2024-10-01,0,older_90d,5-20h,False,True,False,True,False,False,False,"적과 무기 종류가 적은 점은 아쉽지만, 사운드트랙, 스토리, 개선된 전투 시스템 등 전반적인 게임성이 매우 뛰어남.","콘텐츠 볼륨(적/무기 종류) 확장을 고려하되, 현재의 긍정적인 사운드트랙과 스토리텔링 강점을 유지할 것.",exact_match,False,False,False,False
3,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,gameplay_loop,게임플레이 루프,positive,크래프팅 시스템이 단순하지만 잘 작동하고 재미있음,2024-10-01 20:46:59,2024-10-01,0,older_90d,5-20h,False,True,False,True,False,False,False,"적과 무기 종류가 적은 점은 아쉽지만, 사운드트랙, 스토리, 개선된 전투 시스템 등 전반적인 게임성이 매우 뛰어남.","콘텐츠 볼륨(적/무기 종류) 확장을 고려하되, 현재의 긍정적인 사운드트랙과 스토리텔링 강점을 유지할 것.",exact_match,True,False,False,False
4,176179490,2990640,Endoparasitic 2,positive,positive,content_volume,medium,D0-D30,10.433333,34,0.749335,story,스토리,positive,스토리가 전작보다 깊이 있고 재미있음,2024-10-01 20:46:59,2024-10-01,0,older_90d,5-20h,False,True,False,True,False,False,False,"적과 무기 종류가 적은 점은 아쉽지만, 사운드트랙, 스토리, 개선된 전투 시스템 등 전반적인 게임성이 매우 뛰어남.","콘텐츠 볼륨(적/무기 종류) 확장을 고려하되, 현재의 긍정적인 사운드트랙과 스토리텔링 강점을 유지할 것.",exact_match,True,False,False,False

게임 단위 요약: (1, 16)

,appid,game_name,review_count,issue_tag_count,steam_positive_review_count,steam_negative_review_count,steam_positive_rate,llm_positive_review_count,llm_negative_mixed_review_count,llm_negative_mixed_rate,high_urgency_review_count,high_urgency_rate,first_review_datetime,last_review_datetime,mean_playtime_at_review_hours,median_playtime_at_review_hours
0,2990640,Endoparasitic 2,245,477,198,47,0.8082,148,96,0.3918,31,0.1265,2024-10-01 20:00:52,2026-04-10 23:16:46,8.28,7.43

이슈 단위 요약: (17, 28)
최종 우선 검토 수준 분포

  rule_priority_hint  issue_count
0                  하           10
1                  중            6
2                  상            1

절대 기준 후보 분포

  priority_candidate  issue_count
0                  하           10
1                  중            6
2                  상            1

,llm_issue_category,appid,game_name,issue_name_kor,affected_review_count,positive_review_count,negative_review_count,mixed_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_negative_mixed_review_count,recent_30d_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,avg_playtime_at_review_hours,median_playtime_at_review_hours,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_rate,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,patch_ops_note
7,gameplay_loop,2990640,Endoparasitic 2,게임플레이 루프,87,20,55,4,59,35,22,21,0,0,21,7.87,6.45,0.2529,0.6782,0.4023,0.0,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 5개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 87개, 부정·혼합 59개, Steam 비추천 맥락 35개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 22개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
1,bug,2990640,Endoparasitic 2,버그,16,1,14,1,15,5,6,6,0,0,2,8.90,8.53,0.3750,0.9375,0.3125,0.0,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 16개, 부정·혼합 15개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 6개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
16,ui_ux,2990640,Endoparasitic 2,UI/UX,34,2,30,1,31,13,11,11,0,0,15,7.10,6.35,0.3235,0.9118,0.3824,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 34개, 부정·혼합 31개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 11개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
0,balance,2990640,Endoparasitic 2,밸런스,32,1,26,2,28,9,8,8,0,0,5,9.18,8.24,0.2500,0.8750,0.2812,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 32개, 부정·혼합 28개, Steam 비추천 맥락 9개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
6,difficulty,2990640,Endoparasitic 2,난이도,26,3,19,0,19,9,5,5,0,0,2,10.09,10.15,0.1923,0.7308,0.3462,0.0,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 26개, 부정·혼합 19개, Steam 비추천 맥락 9개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 5개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
2,content_volume,2990640,Endoparasitic 2,콘텐츠 분량,33,1,18,1,19,12,4,3,1,1,4,8.96,8.72,0.1212,0.5758,0.3636,1.0,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 33개, 부정·혼합 19개, Steam 비추천 맥락 12개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 4개(보조 참고), 절대 기준 후보 중, 규...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
15,story,2990640,Endoparasitic 2,스토리,32,6,19,0,19,11,7,7,1,1,1,11.02,9.38,0.2188,0.5938,0.3438,1.0,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 32개, 부정·혼합 19개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 7개(보조 참고), 절대 기준 후보 중, 규...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
14,save_progression,2990640,Endoparasitic 2,저장/진행,6,0,5,0,5,3,3,3,0,0,3,6.08,4.31,0.5000,0.8333,0.5000,0.0,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 6개, 부정·혼합 5개, Steam 비추천 맥락 3개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 3개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
3,control,2990640,Endoparasitic 2,조작감,8,2,5,0,5,4,4,4,0,0,3,8.90,5.68,0.5000,0.6250,0.5000,0.0,단기 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 8개, 부정·혼합 5개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
8,graphics_audio,2990640,Endoparasitic 2,그래픽/사운드,15,4,8,1,9,7,6,5,0,0,2,8.10,7.75,0.4000,0.6000,0.4667,0.0,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 15개, 부정·혼합 9개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam ...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
9,other,2990640,Endoparasitic 2,기타,14,0,6,0,6,6,3,3,1,1,4,6.29,4.65,0.2143,0.4286,0.4286,1.0,검토 필요,하,하,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,"영향 리뷰 14개, 부정·혼합 6개, Steam 비추천 맥락 6개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 3개(보조 참고), 절대 기준 후보 하, 규칙 ...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
12,price_value,2990640,Endoparasitic 2,가격/가치,5,2,2,0,2,1,1,1,0,0,1,6.85,7.73,0.2000,0.4000,0.2000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 5개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
10,performance,2990640,Endoparasitic 2,성능,2,0,2,0,2,1,2,2,0,0,1,14.26,14.26,1.0000,1.0000,0.5000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 2개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
4,crash,2990640,Endoparasitic 2,크래시,1,0,1,0,1,1,1,1,0,0,0,24.00,24.00,1.0000,1.0000,1.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
13,progression_grind,2990640,Endoparasitic 2,성장/반복 노가다,1,0,1,0,1,1,1,1,0,0,0,11.12,11.12,1.0000,1.0000,1.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
5,developer_communication,2990640,Endoparasitic 2,개발사 소통,1,0,1,0,1,0,0,0,0,0,0,17.52,17.52,0.0000,1.0000,0.0000,0.0,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
11,positive_praise,2990640,Endoparasitic 2,긍정 칭찬,164,164,0,0,0,4,6,0,1,0,0,8.93,8.33,0.0366,0.0000,0.0244,0.0,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 164개, 부정·혼합 0개, Steam 비추천 맥락 4개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

플레이타임 구간별 이슈 요약: (47, 7)

,playtime_stage,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
3,0-1h,gameplay_loop,게임플레이 루프,5,5,1,5
4,0-1h,other,기타,3,2,0,1
0,0-1h,content_volume,콘텐츠 분량,2,1,0,1
2,0-1h,difficulty,난이도,1,1,0,1
1,0-1h,control,조작감,1,0,0,0
5,0-1h,positive_praise,긍정 칭찬,8,0,0,0
11,1-5h,gameplay_loop,게임플레이 루프,22,16,9,14
19,1-5h,ui_ux,UI/UX,15,15,7,10
6,1-5h,balance,밸런스,6,5,3,3
9,1-5h,control,조작감,3,3,3,3
17,1-5h,save_progression,저장/진행,3,3,3,2
8,1-5h,content_volume,콘텐츠 분량,6,3,0,3
7,1-5h,bug,버그,2,2,2,1
12,1-5h,graphics_audio,그래픽/사운드,4,2,2,4
13,1-5h,other,기타,4,2,1,2
14,1-5h,performance,성능,1,1,1,0
16,1-5h,price_value,가격/가치,2,1,1,1
10,1-5h,difficulty,난이도,2,1,0,1
18,1-5h,story,스토리,2,1,0,1
15,1-5h,positive_praise,긍정 칭찬,38,0,1,0

최근성 구간별 이슈 요약: (25, 7)

,review_recency_group,llm_issue_category,issue_name_kor,affected_review_count,negative_mixed_review_count,high_urgency_review_count,steam_negative_review_count
4,last_30d,content_volume,콘텐츠 분량,1,1,0,1
5,last_30d,other,기타,1,1,0,1
7,last_30d,story,스토리,1,1,0,0
6,last_30d,positive_praise,긍정 칭찬,1,0,0,0
0,61-90d,difficulty,난이도,2,2,1,1
1,61-90d,gameplay_loop,게임플레이 루프,1,1,1,1
2,61-90d,other,기타,1,1,1,1
3,61-90d,positive_praise,긍정 칭찬,1,0,0,0
15,older_90d,gameplay_loop,게임플레이 루프,86,58,21,34
24,older_90d,ui_ux,UI/UX,34,31,11,13
8,older_90d,balance,밸런스,32,28,8,9
23,older_90d,story,스토리,31,18,7,11
10,older_90d,content_volume,콘텐츠 분량,32,18,4,11
14,older_90d,difficulty,난이도,24,17,4,8
9,older_90d,bug,버그,16,15,6,5
16,older_90d,graphics_audio,그래픽/사운드,15,9,6,7
11,older_90d,control,조작감,8,5,4,4
22,older_90d,save_progression,저장/진행,6,5,3,3
17,older_90d,other,기타,12,4,2,4
18,older_90d,performance,성능,2,2,2,1

패치·운영 전략 생성용 근거 테이블: (17, 29)

,llm_issue_category,issue_name_kor,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,priority_reason,patch_ops_note
7,gameplay_loop,게임플레이 루프,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 5개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,87,59,35,22,0,21,"영향 리뷰 87개, 부정·혼합 59개, Steam 비추천 맥락 35개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 22개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...","반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다."
1,bug,버그,즉시 확인,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,16,15,5,6,0,2,"영향 리뷰 16개, 부정·혼합 15개, Steam 비추천 맥락 5개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 6개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","반복 언급된 버그를 재현 가능성 기준으로 분류하고, 플레이 방해 수준이 큰 항목부터 수정한다."
16,ui_ux,UI/UX,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,34,31,13,11,0,15,"영향 리뷰 34개, 부정·혼합 31개, Steam 비추천 맥락 13개, 초반 플레이타임 부정·혼합 15개, High urgency 후보 11개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과...","메뉴, 인벤토리, 퀘스트 안내, 조작 안내 등 편의성 문제를 개선한다."
0,balance,밸런스,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,32,28,9,8,0,5,"영향 리뷰 32개, 부정·혼합 28개, Steam 비추천 맥락 9개, 초반 플레이타임 부정·혼합 5개, High urgency 후보 8개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...","전투, 성장, 보상, 적 난이도의 불균형 지점을 조정한다."
6,difficulty,난이도,단기 개선,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,26,19,9,5,0,2,"영향 리뷰 26개, 부정·혼합 19개, Steam 비추천 맥락 9개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 5개(보조 참고), 절대 기준 후보 중, 규칙 근거: 부정·혼합 맥락과 St...",초반 진입 장벽과 후반 난이도 피로를 구분해 난이도 옵션 또는 안내를 보강한다.
2,content_volume,콘텐츠 분량,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,33,19,12,4,1,4,"영향 리뷰 33개, 부정·혼합 19개, Steam 비추천 맥락 12개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 4개(보조 참고), 절대 기준 후보 중, 규...",콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.
15,story,스토리,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,32,19,11,7,1,1,"영향 리뷰 32개, 부정·혼합 19개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 7개(보조 참고), 절대 기준 후보 중, 규...","서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다."
14,save_progression,저장/진행,즉시 확인,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,6,5,3,3,0,3,"영향 리뷰 6개, 부정·혼합 5개, Steam 비추천 맥락 3개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 3개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","저장 손실, 진행 막힘, 퀘스트 진행 불가 여부를 우선 점검한다."
3,control,조작감,단기 개선,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,8,5,4,4,0,3,"영향 리뷰 8개, 부정·혼합 5개, Steam 비추천 맥락 4개, 초반 플레이타임 부정·혼합 3개, High urgency 후보 4개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","이동, 전투, 상호작용 조작의 반응성과 키 설정 편의성을 점검한다."
8,graphics_audio,그래픽/사운드,장기 검토,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,15,9,7,6,0,2,"영향 리뷰 15개, 부정·혼합 9개, Steam 비추천 맥락 7개, 초반 플레이타임 부정·혼합 2개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam ...",그래픽/사운드가 몰입을 방해하는지와 강점으로 작동하는지를 함께 확인한다.
9,other,기타,검토 필요,하,하,기타 이슈는 원인이 명확하지 않아 세부 리뷰 확인 대상으로 분리,기타 이슈는 원인 범주가 넓어 세부 리뷰 확인 대상으로 분리,14,6,6,3,1,4,"영향 리뷰 14개, 부정·혼합 6개, Steam 비추천 맥락 6개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 3개(보조 참고), 절대 기준 후보 하, 규칙 ...",세부 리뷰를 확인해 반복되는 하위 원인이 있는지 검토한다.
12,price_value,가격/가치,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,5,2,1,1,0,1,"영향 리뷰 5개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...",가격 대비 만족도 불만이 반복되는지 확인하고 할인/번들/콘텐츠 가치 전달을 검토한다.
10,performance,성능,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,2,2,1,2,0,1,"영향 리뷰 2개, 부정·혼합 2개, Steam 비추천 맥락 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 2개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비...","프레임 저하, 로딩, 끊김 등 성능 문제를 환경별로 점검한다."
4,crash,크래시,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,1,1,0,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","크래시 발생 조건과 로그를 우선 확인하고, 재현 가능한 오류부터 수정한다."
13,progression_grind,성장/반복 노가다,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,1,1,0,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 1개, High urgency 후보 1개(보조 참고), 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함",반복 성장과 노가다 피로를 줄일 수 있는 보상/성장 속도 조정을 검토한다.
5,developer_communication,개발사 소통,검토 필요,하,하,절대 기준상 하 또는 개선 우선순위 근거가 상대적으로 약함,반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함,1,1,0,0,0,0,"영향 리뷰 1개, 부정·혼합 1개, Steam 비추천 맥락 0개, 절대 기준 후보 하, 규칙 근거: 반복성 또는 Steam 비추천 맥락 근거가 상대적으로 약함","패치 노트, 공지, 커뮤니티 응답 등 운영 커뮤니케이션을 점검한다."
11,positive_praise,긍정 칭찬,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,164,0,4,6,0,0,"영향 리뷰 164개, 부정·혼합 0개, Steam 비추천 맥락 4개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리","긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다."

Tableau/보고서 원천 데이터: (477, 40)

,appid,game_name,recommendationid,review_datetime,release_date,days_from_release,release_period,review_recency_group,steam_label_text,llm_sentiment,steam_llm_sentiment_relation,playtime_at_review_hours,playtime_stage,early_playtime_flag,votes_up,weighted_vote_score,llm_urgency_candidate,high_urgency_flag,llm_issue_category,issue_name_kor,llm_issue_sentiment,issue_positive_flag,issue_negative_or_mixed_flag,action_group_hint,priority_candidate,rule_priority_hint,priority_selection_note,priority_rule_detail,priority_reason,affected_review_count,negative_mixed_review_count,steam_negative_review_count,high_urgency_review_count,high_urgency_rate,negative_mixed_rate,steam_negative_rate,recent_30d_negative_mixed_review_count,early_playtime_negative_mixed_review_count,patch_ops_note,llm_issue_evidence
0,2990640,Endoparasitic 2,176177053,2024-10-01 20:00:52,2024-10-01,0,D0-D30,older_90d,positive,positive,exact_match,0.266667,0-1h,True,6,0.510040,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 164개, 부정·혼합 0개, Steam 비추천 맥락 4개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",164,0,4,6,0.0366,0.0000,0.0244,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",한 손으로 플레이 가능한 조작감과 훌륭한 속편이라는 점을 칭찬함
1,2990640,Endoparasitic 2,176177300,2024-10-01 20:05:29,2024-10-01,0,D0-D30,older_90d,positive,positive,exact_match,0.383333,0-1h,True,1,0.490937,low,False,positive_praise,긍정 칭찬,positive,True,False,강점 유지,하,하,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리,"영향 리뷰 164개, 부정·혼합 0개, Steam 비추천 맥락 4개, High urgency 후보 6개(보조 참고), 절대 기준 후보 하, 규칙 근거: 강점 유지 항목이므로 개선 우선순위 산정 대상에서 분리",164,0,4,6,0.0366,0.0000,0.0244,0,0,"긍정적으로 평가된 요소를 유지하고, 업데이트와 마케팅 메시지에서 강점으로 활용한다.",게임이 매우 훌륭하다고 언급함
2,2990640,Endoparasitic 2,176179490,2024-10-01 20:46:59,2024-10-01,0,D0-D30,older_90d,positive,positive,exact_match,10.433333,5-20h,False,34,0.749335,medium,False,content_volume,콘텐츠 분량,neutral,False,False,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 33개, 부정·혼합 19개, Steam 비추천 맥락 12개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 4개, High urgency 후보 4개(보조 참고), 절대 기준 후보 중, 규...",33,19,12,4,0.1212,0.5758,0.3636,1,4,콘텐츠 부족·반복성은 단기 패치보다 업데이트 로드맵 관점에서 검토한다.,적 유형과 무기 종류가 각각 3개뿐이라는 점을 지적함
3,2990640,Endoparasitic 2,176179490,2024-10-01 20:46:59,2024-10-01,0,D0-D30,older_90d,positive,positive,exact_match,10.433333,5-20h,False,34,0.749335,medium,False,gameplay_loop,게임플레이 루프,positive,True,False,단기 개선,상,상,절대 기준 '상' 후보 중 이번 게임 내 상대 우선순위 상위 5개로 유지,절대 기준 상 후보 + 게임 내 상대 우선순위 상위 이슈,"영향 리뷰 87개, 부정·혼합 59개, Steam 비추천 맥락 35개, 초반 플레이타임 부정·혼합 21개, High urgency 후보 22개(보조 참고), 절대 기준 후보 상, 규칙 근거: 절대 기준 상 후...",87,59,35,22,0.2529,0.6782,0.4023,0,21,"반복 피로, 목표 구조, 보상 흐름을 점검하고 플레이 루프의 지루함을 줄인다.",크래프팅 시스템이 단순하지만 잘 작동하고 재미있음
4,2990640,Endoparasitic 2,176179490,2024-10-01 20:46:59,2024-10-01,0,D0-D30,older_90d,positive,positive,exact_match,10.433333,5-20h,False,34,0.749335,medium,False,story,스토리,positive,True,False,장기 검토,중,중,절대 기준상 '중' 후보로 분류,부정·혼합 맥락과 Steam 비추천 맥락이 일정 수준 확인,"영향 리뷰 32개, 부정·혼합 19개, Steam 비추천 맥락 11개, 최근 30일 부정·혼합 1개, 초반 플레이타임 부정·혼합 1개, High urgency 후보 7개(보조 참고), 절대 기준 후보 중, 규...",32,19,11,7,0.2188,0.5938,0.3438,1,1,"서사 전달, 퀘스트 흐름, 엔딩/분기 만족도를 장기 개선 후보로 검토한다.",스토리가 전작보다 깊이 있고 재미있음

저장 완료
저장 폴더: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_preprocess_data

,파일명,행 수,역할
0,postlaunch_review_base.csv,245,리뷰 1개 단위 전처리 결과
1,postlaunch_issue_summary.csv,17,이슈별 반복성/부정·혼합/Steam 비추천/High urgency 보조 지표 요약
2,postlaunch_patch_ops_evidence_base.csv,17,03-2 LLM 패치·운영 전략 생성용 근거 데이터
3,tableau_postlaunch_patch_ops_source.csv,477,Tableau/보고서용 원천 데이터

검증 통과
리뷰 수: 245
리뷰-이슈 수: 477
이슈 종류 수: 17
절대 기준 후보 분포:

  priority_candidate  issue_count
0                  하           10
1                  중            6
2                  상            1

최종 우선 검토 수준 분포:

  rule_priority_hint  issue_count
0                  하           10
1                  중            6
2                  상            1

최종 '상' 제한 기준: 최대 5개
High urgency는 rule_priority_hint 계산에는 직접 사용하지 않고, priority_reason/llm_evidence_text에서 보조 지표로만 유지한다.

==========================================================================================
03-1번 여러 게임 실행 요약
==========================================================================================
batch log 저장: c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\03-1_postlaunch_preprocess_batch_log.csv

,game_key,appid,game_name,status,review_base_rows,issue_summary_rows,patch_ops_evidence_rows,tableau_source_rows,preprocess_dir,review_base_path,issue_summary_path,patch_ops_evidence_base_path,tableau_source_path,error_message
0,heroes_of_hammerwatch_2,619820,Heroes of Hammerwatch II,success,1000,20,20,1903,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\heroes_of_hammerwatch_2\postl...,
1,necrosmith_2,2277320,Necrosmith 2,success,324,21,21,615,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_prepr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_prepr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_prepr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_prepr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\necrosmith_2\postlaunch_prepr...,
2,children_of_the_sun,1309950,Children of the Sun,success,883,19,19,1567,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunc...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunc...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunc...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunc...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\children_of_the_sun\postlaunc...,
3,laundry_store_simulator,3150440,Laundry Store Simulator,success,575,21,21,1064,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postl...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\laundry_store_simulator\postl...,
4,endoparasitic_2,2990640,Endoparasitic 2,success,245,17,17,477,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_pr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_pr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_pr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_pr...,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\runs\endoparasitic_2\postlaunch_pr...,

# 3. 게임별 산출물 통합 저장

`TARGET_GAME_KEYS`에 있는 게임별 실행 결과를 모아 `data/outputs/postlaunch/master` 폴더에 통합 저장한다.

이 셀은 위의 03-1 전처리 실행이 끝난 뒤 실행한다. 03번 LLM 원천 산출물과 03-1 전처리 산출물을 함께 master 폴더로 모으기 위한 단계이다.

In [4]:
# ============================================================
# 03-1 산출물 게임별 결과 통합
# ============================================================

from pathlib import Path
import pandas as pd

ROOT = Path.cwd()

if not (ROOT / "data" / "preprocessed").exists():
    for parent in ROOT.parents:
        if (parent / "data" / "preprocessed").exists():
            ROOT = parent
            break

POSTLAUNCH_OUTPUT_DIR = ROOT / "data" / "outputs" / "postlaunch"
RUNS_DIR = POSTLAUNCH_OUTPUT_DIR / "runs"

MASTER_DIR = POSTLAUNCH_OUTPUT_DIR / "master"
MASTER_DIR.mkdir(parents=True, exist_ok=True)

MASTER_PREPROCESS_DIR = MASTER_DIR / "postlaunch_preprocess_data"
MASTER_PREPROCESS_DIR.mkdir(parents=True, exist_ok=True)

if not RUNS_DIR.exists():
    raise FileNotFoundError(f"게임별 runs 폴더가 없습니다: {RUNS_DIR}")


def read_run_csv(run_dir, relative_path):
    path = run_dir / relative_path

    if not path.exists():
        return None

    df = pd.read_csv(path, dtype={"recommendationid": "string"})
    df["source_run"] = run_dir.name
    return df


def concat_run_csv(relative_path, drop_duplicates_subset=None):
    dfs = []

    for run_dir in sorted(RUNS_DIR.iterdir()):
        if not run_dir.is_dir():
            continue

        df = read_run_csv(run_dir, relative_path)

        if df is not None and len(df) > 0:
            dfs.append(df)

    if not dfs:
        return pd.DataFrame()

    merged = pd.concat(dfs, ignore_index=True)

    if drop_duplicates_subset:
        valid_subset = [col for col in drop_duplicates_subset if col in merged.columns]
        if valid_subset:
            merged = merged.drop_duplicates(subset=valid_subset, keep="last")

    return merged


# ============================================================
# 03번 LLM 원천 산출물 통합
# ============================================================

llm_input_reviews = concat_run_csv(
    "llm_input_reviews.csv",
    drop_duplicates_subset=["recommendationid"],
)

llm_filter_log = concat_run_csv(
    "llm_input_filter_log.csv",
)

llm_sample_summary = concat_run_csv(
    "llm_input_sample_summary.csv",
)

llm_review_result = concat_run_csv(
    "llm_review_analysis_result.csv",
    drop_duplicates_subset=["recommendationid"],
)

llm_issue_tags_flat = concat_run_csv(
    "llm_issue_tags_flat.csv",
    drop_duplicates_subset=["appid", "recommendationid", "llm_issue_category", "llm_issue_evidence"],
)

llm_input_reviews.to_csv(MASTER_DIR / "llm_input_reviews.csv", index=False, encoding="utf-8-sig")
llm_filter_log.to_csv(MASTER_DIR / "llm_input_filter_log.csv", index=False, encoding="utf-8-sig")
llm_sample_summary.to_csv(MASTER_DIR / "llm_input_sample_summary.csv", index=False, encoding="utf-8-sig")
llm_review_result.to_csv(MASTER_DIR / "llm_review_analysis_result.csv", index=False, encoding="utf-8-sig")
llm_issue_tags_flat.to_csv(MASTER_DIR / "llm_issue_tags_flat.csv", index=False, encoding="utf-8-sig")


# ============================================================
# 03-1번 게임별 전처리 산출물 통합
# ============================================================

postlaunch_review_base = concat_run_csv(
    "postlaunch_preprocess_data/postlaunch_review_base.csv",
    drop_duplicates_subset=["recommendationid"],
)

postlaunch_issue_summary = concat_run_csv(
    "postlaunch_preprocess_data/postlaunch_issue_summary.csv",
    drop_duplicates_subset=["appid", "llm_issue_category"],
)

postlaunch_patch_ops_evidence_base = concat_run_csv(
    "postlaunch_preprocess_data/postlaunch_patch_ops_evidence_base.csv",
    drop_duplicates_subset=["appid", "llm_issue_category"],
)

tableau_postlaunch_source = concat_run_csv(
    "postlaunch_preprocess_data/tableau_postlaunch_patch_ops_source.csv",
    drop_duplicates_subset=["appid", "recommendationid", "llm_issue_category"],
)

postlaunch_review_base.to_csv(
    MASTER_PREPROCESS_DIR / "postlaunch_review_base.csv",
    index=False,
    encoding="utf-8-sig",
)

postlaunch_issue_summary.to_csv(
    MASTER_PREPROCESS_DIR / "postlaunch_issue_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

postlaunch_patch_ops_evidence_base.to_csv(
    MASTER_PREPROCESS_DIR / "postlaunch_patch_ops_evidence_base.csv",
    index=False,
    encoding="utf-8-sig",
)

tableau_postlaunch_source.to_csv(
    MASTER_PREPROCESS_DIR / "tableau_postlaunch_patch_ops_source.csv",
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# 통합 결과 확인
# ============================================================

check_rows = [
    {
        "파일": "llm_input_reviews.csv",
        "행 수": len(llm_input_reviews),
        "저장 위치": str(MASTER_DIR / "llm_input_reviews.csv"),
    },
    {
        "파일": "llm_review_analysis_result.csv",
        "행 수": len(llm_review_result),
        "저장 위치": str(MASTER_DIR / "llm_review_analysis_result.csv"),
    },
    {
        "파일": "llm_issue_tags_flat.csv",
        "행 수": len(llm_issue_tags_flat),
        "저장 위치": str(MASTER_DIR / "llm_issue_tags_flat.csv"),
    },
    {
        "파일": "postlaunch_review_base.csv",
        "행 수": len(postlaunch_review_base),
        "저장 위치": str(MASTER_PREPROCESS_DIR / "postlaunch_review_base.csv"),
    },
    {
        "파일": "postlaunch_issue_summary.csv",
        "행 수": len(postlaunch_issue_summary),
        "저장 위치": str(MASTER_PREPROCESS_DIR / "postlaunch_issue_summary.csv"),
    },
    {
        "파일": "postlaunch_patch_ops_evidence_base.csv",
        "행 수": len(postlaunch_patch_ops_evidence_base),
        "저장 위치": str(MASTER_PREPROCESS_DIR / "postlaunch_patch_ops_evidence_base.csv"),
    },
    {
        "파일": "tableau_postlaunch_patch_ops_source.csv",
        "행 수": len(tableau_postlaunch_source),
        "저장 위치": str(MASTER_PREPROCESS_DIR / "tableau_postlaunch_patch_ops_source.csv"),
    },
]

check_df = pd.DataFrame(check_rows)
display(check_df)

print("통합 완료")
print("통합된 게임 수:", postlaunch_review_base["appid"].nunique() if "appid" in postlaunch_review_base.columns else 0)

if "game_name" in postlaunch_review_base.columns:
    display(
        postlaunch_review_base
        .groupby(["appid", "game_name"], dropna=False)
        .agg(review_count=("recommendationid", "nunique"))
        .reset_index()
        .sort_values("review_count", ascending=False)
    )

,파일,행 수,저장 위치
0,llm_input_reviews.csv,3027,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\llm_input_reviews.csv
1,llm_review_analysis_result.csv,3027,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\llm_review_analysis_result.csv
2,llm_issue_tags_flat.csv,5729,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\llm_issue_tags_flat.csv
3,postlaunch_review_base.csv,3027,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\postlaunch_preprocess_data\...
4,postlaunch_issue_summary.csv,98,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\postlaunch_preprocess_data\...
5,postlaunch_patch_ops_evidence_base.csv,98,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\postlaunch_preprocess_data\...
6,tableau_postlaunch_patch_ops_source.csv,5626,c:\Users\joon5\Documents\github\steam-indie-game-analysis\data\outputs\postlaunch\master\postlaunch_preprocess_data\...

통합 완료
통합된 게임 수: 5

     appid                 game_name  review_count
0   619820  Heroes of Hammerwatch II          1000
1  1309950       Children of the Sun           883
4  3150440   Laundry Store Simulator           575
2  2277320              Necrosmith 2           324
3  2990640           Endoparasitic 2           245

# 4. 산출 CSV 테이블 명세서

03-1에서는 03-2에서 실제로 사용할 산출물만 저장한다.

## 산출 파일 목록

| 파일명 | 역할 |
|---|---|
| `postlaunch_review_base.csv` | 리뷰 1개 단위 전처리 결과 |
| `postlaunch_issue_summary.csv` | 이슈별 반복성, 부정·혼합, Steam 비추천, 최근성, 플레이타임 근거 요약 |
| `postlaunch_patch_ops_evidence_base.csv` | 03-2 LLM 패치·운영 전략 생성용 근거 데이터 |
| `tableau_postlaunch_patch_ops_source.csv` | Tableau/보고서용 원천 데이터 |

추가로 게임별 runs 결과를 통합하여 아래 위치에도 저장한다.

| 저장 위치 | 파일명 | 역할 |
|---|---|---|
| `data/outputs/postlaunch/master/` | `llm_input_reviews.csv` | 03번 LLM 입력 리뷰 통합본 |
| `data/outputs/postlaunch/master/` | `llm_review_analysis_result.csv` | 03번 리뷰 단위 LLM 결과 통합본 |
| `data/outputs/postlaunch/master/` | `llm_issue_tags_flat.csv` | 03번 이슈 태그 단위 LLM 결과 통합본 |
| `data/outputs/postlaunch/master/postlaunch_preprocess_data/` | `postlaunch_review_base.csv` | 03-1 리뷰 단위 전처리 결과 통합본 |
| `data/outputs/postlaunch/master/postlaunch_preprocess_data/` | `postlaunch_issue_summary.csv` | 03-1 이슈별 근거 요약 통합본 |
| `data/outputs/postlaunch/master/postlaunch_preprocess_data/` | `postlaunch_patch_ops_evidence_base.csv` | 03-2 입력용 근거 데이터 통합본 |
| `data/outputs/postlaunch/master/postlaunch_preprocess_data/` | `tableau_postlaunch_patch_ops_source.csv` | Tableau/보고서용 원천 데이터 통합본 |

---

## postlaunch_review_base.csv

| 컬럼명 | 설명 | 예시 값 |
|---|---|---|
| `recommendationid` | Steam 리뷰 고유 ID | `221779395` |
| `appid` | Steam 게임 고유 ID | `1466060` |
| `game_name` | 게임명 | `Tainted Grail: The Fall of Avalon` |
| `review_datetime` | 리뷰 작성 일시 | `2026-04-05 16:40:12` |
| `review_recency_group` | 분석 데이터 내 최신 리뷰일 기준 최근성 구간 | `last_30d` |
| `steam_label_text` | Steam 추천/비추천 라벨 | `positive` |
| `playtime_at_review_hours` | 리뷰 작성 시점 플레이타임 | `12.5` |
| `playtime_stage` | 리뷰 작성 시점 플레이타임 구간 | `5-20h` |
| `llm_sentiment` | LLM이 리뷰 내용을 보고 분류한 감정 | `mixed` |
| `llm_urgency_candidate` | LLM이 리뷰 내용을 보고 분류한 시급도 후보 | `high` |
| `high_urgency_flag` | High urgency 여부. 우선 검토 수준 계산 기준이 아니라 보조 참고 지표 | `True` |
| `llm_review_summary` | LLM이 작성한 리뷰 요약 | `전투와 탐험은 좋지만 버그를 지적함` |
| `llm_suggested_action` | LLM이 리뷰 내용을 바탕으로 정리한 개선 방향 후보 | `진행 방해 버그를 우선 확인` |

---

## postlaunch_issue_summary.csv

| 컬럼명 | 설명 | 예시 값 |
|---|---|---|
| `llm_issue_category` | LLM이 추출한 이슈 카테고리 | `gameplay_loop` |
| `issue_name_kor` | 이슈 한글명 | `게임플레이 루프` |
| `affected_review_count` | 해당 이슈가 언급된 리뷰 수 | `239` |
| `negative_mixed_review_count` |  LLM이 이슈 태그 단위에서 부정 또는 혼합 맥락으로 분류한 리뷰 수. Steam 비추천 라벨과는 별개의 LLM 분류값 | `130` |
| `steam_negative_review_count` | Steam 비추천 리뷰 중 해당 이슈가 언급된 리뷰 수 | `64` |
| `high_urgency_review_count` | LLM이 High urgency 후보로 분류한 리뷰 수. 우선 검토 수준 계산에는 직접 사용하지 않음 | `42` |
| `high_urgency_rate` | 영향 리뷰 중 High urgency 후보 비율. 보조 참고 지표 | `0.176` |
| `negative_mixed_rate` | 영향 리뷰 중 부정/혼합 비율 | `0.544` |
| `steam_negative_rate` | 영향 리뷰 중 Steam 비추천 비율 | `0.269` |
| `recent_30d_negative_mixed_review_count` | 분석 데이터 내 최신 리뷰일 기준 최근 30일 부정/혼합 리뷰 수 | `12` |
| `early_playtime_negative_mixed_review_count` | 0~5시간 구간 부정/혼합 리뷰 수 | `8` |
| `action_group_hint` | 이슈 성격과 집계값 기반 대응 구분 | `단기 개선` |
| `rule_priority_hint` | 규칙 기반 우선 검토 수준 | `상` |
| `priority_rule_detail` | 우선 검토 수준이 부여된 규칙 설명 | `부정·혼합 반복 + Steam 비추천 맥락 + 최근 30일 반복` |
| `priority_reason` | 우선 검토 힌트의 근거 요약 | `영향 리뷰 239개, 부정·혼합 130개...` |
| `patch_ops_note` | 패치·운영 해석 메모 | `반복 피로, 목표 구조, 보상 흐름을 점검...` |

---

## postlaunch_patch_ops_evidence_base.csv

| 컬럼명 | 설명 | 예시 값 |
|---|---|---|
| `llm_issue_category` | LLM이 추출한 이슈 카테고리 | `save_progression` |
| `issue_name_kor` | 이슈 한글명 | `저장/진행` |
| `action_group_hint` | 03-1에서 계산한 대응 구분 | `즉시 확인` |
| `rule_priority_hint` | 03-1에서 계산한 고정 우선 검토 수준 | `상` |
| `priority_rule_detail` | 우선 검토 수준이 부여된 규칙 설명 | `플레이 방해 가능 이슈 + 부정·혼합 반복 + Steam 비추천 맥락` |
| `priority_reason` | 집계 기반 근거 문장 | `영향 리뷰 26개, 부정·혼합 23개...` |
| `patch_ops_note` | 이슈별 기본 대응 메모 | `저장 손실, 진행 막힘...` |
| `llm_evidence_text` | 03-2 LLM 프롬프트에 넣을 근거 블록 | `[ISSUE] ... [/ISSUE]` |

---

## tableau_postlaunch_patch_ops_source.csv

| 컬럼명 | 설명 | 예시 값 |
|---|---|---|
| `review_datetime` | 리뷰 작성 일시 | `2026-04-05 16:40:12` |
| `review_recency_group` | 최근성 구간 | `last_30d` |
| `playtime_stage` | 플레이타임 구간 | `20-50h` |
| `llm_issue_category` | 이슈 카테고리 | `performance` |
| `issue_name_kor` | 이슈 한글명 | `성능` |
| `llm_issue_sentiment` | 해당 이슈가 리뷰에서 나타난 감정 | `negative` |
| `issue_negative_or_mixed_flag` | 부정/혼합 맥락 여부 | `True` |
| `action_group_hint` | 대응 구분 힌트 | `즉시 확인` |
| `rule_priority_hint` | 우선 검토 힌트 | `상` |
| `priority_rule_detail` | 우선 검토 힌트 부여 규칙 | `부정·혼합 반복 + Steam 비추천 맥락 + 최근 30일 반복` |
| `high_urgency_rate` | 이슈별 High urgency 후보 비율. 보조 참고 지표 | `0.42` |
| `patch_ops_note` | 패치·운영 해석 메모 | `성능 저하와 프레임 드랍을 우선 확인...` |