### [Step 1] 분석 데이터 로드 및 기본 구조 파악
분석에 필요한 주요 데이터셋(`graded`, `review_summary`, `reviews`)을 불러오고, 각 파일의 컬럼명, 데이터 타입, 결측치 여부 및 샘플 데이터를 확인하여 데이터 명세를 점검합니다.

In [1]:
import pandas as pd
from IPython.display import display

# 스크린샷 기반 정확한 상대 경로 세팅
base_path = '../../../../data/preprocessed/'

# 스크린샷에 있는 실제 파일명 목록 (_2 제거)
files = [
    "steam_indie_games_graded.csv",
    "steam_indie_games.csv",
    "steam_indie_review_histogram.csv",
    "steam_indie_review_summary.csv",
    "steam_indie_reviews.csv"
]

for file_name in files:
    file_path = f"{base_path}{file_name}"
    try:
        # 데이터 불러오기
        df = pd.read_csv(file_path)
        
        # 명세서(Specification) 데이터프레임 생성
        spec_df = pd.DataFrame({
            'Column Name': df.columns,
            'Data Type': df.dtypes.astype(str).values,
            'Non-Null Count': df.notnull().sum().values,
            'Sample Value': df.iloc[0].astype(str).values if not df.empty else None
        })
        
        print(f"========== {file_name} ==========")
        display(spec_df) # df 형태로 깔끔하게 출력
        print("\n")
        
    except FileNotFoundError:
        print(f"Error: '{file_path}' 파일을 찾을 수 없습니다. 경로를 다시 확인해주세요.")
    except Exception as e:
        print(f"Error reading '{file_path}': {e}")

========== steam_indie_games_graded.csv ==========

,Column Name,Data Type,Non-Null Count,Sample Value
0,appid,int64,9692,226620
1,positive,float64,9692,1912.0
2,negative,float64,9692,364.0
3,price,float64,9692,14.99
4,total_reviews,float64,9692,2276.0
5,review_score,float64,200,NaN
6,review_score_desc,str,200,NaN
7,name,str,9692,Desktop Dungeons
8,developers,str,9692,QCF Design
9,genres,str,9692,"Adventure, Casual, Indie, RPG, Strategy"
10,release_date,str,9299,2023-04-18
11,short_description,str,9548,Each step into the unknown heals you and revea...
12,publishers,str,9689,QCF Design
13,categories,str,9548,"Single-player, Steam Achievements, Steam Tradi..."
14,windows,object,9548,True
15,mac,object,9548,True
16,linux,object,9548,True
17,recommendations_total,float64,2956,1129.0
18,achievements_total,float64,7355,35.0
19,owners_lower,int64,9692,200000
20,owners_higher,int64,9692,500000
21,tags,str,9692,"{""2D"": 36, ""RPG"": 103, ""Dwarf"": 18, ""Casual"": ..."
22,positive_rate,float64,9687,84.00702987697716
23,scale_grade,str,9692,high
24,satisfaction_grade,str,9692,high
25,performance_grade,str,9692,high_high

========== steam_indie_games.csv ==========

,Column Name,Data Type,Non-Null Count,Sample Value
0,appid,int64,9692,226620
1,positive,float64,9692,1912.0
2,negative,float64,9692,364.0
3,price,float64,9692,14.99
4,total_reviews,float64,9692,2276.0
5,review_score,float64,200,NaN
6,review_score_desc,str,200,NaN
7,name,str,9692,Desktop Dungeons
8,developers,str,9692,QCF Design
9,genres,str,9692,"Adventure, Casual, Indie, RPG, Strategy"
10,release_date,str,9299,2023-04-18
11,short_description,str,9548,Each step into the unknown heals you and revea...
12,publishers,str,9689,QCF Design
13,categories,str,9548,"Single-player, Steam Achievements, Steam Tradi..."
14,windows,object,9548,True
15,mac,object,9548,True
16,linux,object,9548,True
17,recommendations_total,float64,2956,1129.0
18,achievements_total,float64,7355,35.0
19,owners_lower,int64,9692,200000
20,owners_higher,int64,9692,500000
21,tags,str,9692,"{""2D"": 36, ""RPG"": 103, ""Dwarf"": 18, ""Casual"": ..."

========== steam_indie_review_histogram.csv ==========

             Column Name Data Type  Non-Null Count Sample Value
0                  appid     int64           11665       324470
1                   name       str           11665      SinaRun
2           release_date       str           11170   2025-11-03
3        hist_start_date       str           11665   2015-10-26
4          hist_end_date       str           11665   2026-04-26
5                   date       str           11665   2026-03-28
6     recommendations_up     int64           11665            0
7   recommendations_down     int64           11665            0
8              data_type       str           11665       recent
9  recommendations_total     int64           11665            0

========== steam_indie_review_summary.csv ==========

         Column Name Data Type  Non-Null Count     Sample Value
0              appid     int64             200           324470
1       review_score     int64             200                6
2  review_score_desc       str             200  mostly positive
3     total_positive     int64             200              118
4     total_negative     int64             200               33
5      total_reviews     int64             200              151

========== steam_indie_reviews.csv ==========

,Column Name,Data Type,Non-Null Count,Sample Value
0,recommendationid,int64,166875,18698790
1,appid,int64,166875,324470
2,language,str,166875,french
3,review,str,166875,good game for this price
4,timestamp_created,int64,166875,1445883033
5,timestamp_updated,int64,166875,1445883033
6,voted_up,bool,166875,True
7,votes_up,int64,166875,2
8,votes_funny,int64,166875,1
9,weighted_vote_score,float64,166875,0.523809552192688
10,comment_count,int64,166875,0
11,steam_purchase,bool,166875,True
12,received_for_free,bool,166875,False
13,written_during_early_access,bool,166875,True
14,author_steamid,int64,166875,76561197986244887
15,author_num_games_owned,int64,166875,0
16,author_num_reviews,int64,166875,3
17,author_last_played,int64,166875,1503258537
18,created_date,str,166875,2015-10-26 18:10:33
19,updated_date,str,166875,2015-10-26 18:10:33
20,author_last_played_date,str,166875,2017-08-20 19:48:57
21,playtime_forever_hours,float64,166875,3.4833333333333334
22,playtime_last_two_weeks_hours,float64,166875,0.0
23,playtime_at_review_hours,float64,166875,1.25