In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kruskal
import ast
#plt.rcParams['font.family'] = 'AppleGothic'    # Mac
plt.rcParams['font.family'] = 'Malgun Gothic' # Windows
plt.rcParams['axes.unicode_minus'] = False

reviews = pd.read_csv("../../../data/steam_indie_reviews.csv")

센티멘트 생성

In [ ]:
reviews["sentiment"] = reviews["voted_up"].map({
    True: "positive",
    False: "negative"
})

영어인 리뷰만 뽑아보기

In [7]:
reviews_en = reviews[
    (reviews["language"] == "english") &
    (reviews["review"].notna())
].copy()

print(reviews_en.shape)
reviews_en[["review", "sentiment"]].head()

(148915, 22)

                                               review sentiment
4   Fun fact, if you wanted to 100% this game, at ...  negative
24  i'd give it a 3.5. Not terrible, not great either  negative
27        Really fun game. Grindier as hell, but fun.  positive
29      Honestly not a bad game just kinda boring ngl  negative
31  Was having fun until I got an obnoxious rocket...  negative

In [16]:
import re
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

reviews_en["review"] = reviews_en["review"].apply(clean_text)

reviews_en[["review", "clean_review"]].head()

,review,clean_review
4,fun fact if you wanted to this game at minimum...,fun fact if you wanted to this game at minimum...
24,i d give it a not terrible not great either,i d give it a not terrible not great either
27,really fun game grindier as hell but fun,really fun game grindier as hell but fun
29,honestly not a bad game just kinda boring ngl,honestly not a bad game just kinda boring ngl
31,was having fun until i got an obnoxious rocket...,was having fun until i got an obnoxious rocket...

In [ ]:
reviews_en.to_csv('../../../data/processed/eng_review.csv', index=False, encoding="utf-8-sig")